//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.kirc.shared.new_tumor_event._2_7._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.AdditionalSurgeryLocoregionalProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DayOfAdditionalSurgeryLocoregionalProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToAdditionalSurgeryLocoregionalProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.MonthOfAdditionalSurgeryLocoregionalProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.YearOfAdditionalSurgeryLocoregionalProcedure;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}additional_surgery_locoregional_procedure"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}day_of_additional_surgery_locoregional_procedure"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}month_of_additional_surgery_locoregional_procedure"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}year_of_additional_surgery_locoregional_procedure"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}days_to_additional_surgery_locoregional_procedure"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "additionalSurgeryLocoregionalProcedure",
    "dayOfAdditionalSurgeryLocoregionalProcedure",
    "monthOfAdditionalSurgeryLocoregionalProcedure",
    "yearOfAdditionalSurgeryLocoregionalProcedure",
    "daysToAdditionalSurgeryLocoregionalProcedure"
})
@XmlRootElement(name = "locoregional_procedure")
public class LocoregionalProcedure {

    @XmlElement(name = "additional_surgery_locoregional_procedure", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", required = true, nillable = true)
    protected AdditionalSurgeryLocoregionalProcedure additionalSurgeryLocoregionalProcedure;
    @XmlElement(name = "day_of_additional_surgery_locoregional_procedure", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", nillable = true)
    protected DayOfAdditionalSurgeryLocoregionalProcedure dayOfAdditionalSurgeryLocoregionalProcedure;
    @XmlElement(name = "month_of_additional_surgery_locoregional_procedure", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", nillable = true)
    protected MonthOfAdditionalSurgeryLocoregionalProcedure monthOfAdditionalSurgeryLocoregionalProcedure;
    @XmlElement(name = "year_of_additional_surgery_locoregional_procedure", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", nillable = true)
    protected YearOfAdditionalSurgeryLocoregionalProcedure yearOfAdditionalSurgeryLocoregionalProcedure;
    @XmlElement(name = "days_to_additional_surgery_locoregional_procedure", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7")
    protected DaysToAdditionalSurgeryLocoregionalProcedure daysToAdditionalSurgeryLocoregionalProcedure;

    /**
     * Gets the value of the additionalSurgeryLocoregionalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public AdditionalSurgeryLocoregionalProcedure getAdditionalSurgeryLocoregionalProcedure() {
        return additionalSurgeryLocoregionalProcedure;
    }

    /**
     * Sets the value of the additionalSurgeryLocoregionalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public void setAdditionalSurgeryLocoregionalProcedure(AdditionalSurgeryLocoregionalProcedure value) {
        this.additionalSurgeryLocoregionalProcedure = value;
    }

    /**
     * Gets the value of the dayOfAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public DayOfAdditionalSurgeryLocoregionalProcedure getDayOfAdditionalSurgeryLocoregionalProcedure() {
        return dayOfAdditionalSurgeryLocoregionalProcedure;
    }

    /**
     * Sets the value of the dayOfAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public void setDayOfAdditionalSurgeryLocoregionalProcedure(DayOfAdditionalSurgeryLocoregionalProcedure value) {
        this.dayOfAdditionalSurgeryLocoregionalProcedure = value;
    }

    /**
     * Gets the value of the monthOfAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public MonthOfAdditionalSurgeryLocoregionalProcedure getMonthOfAdditionalSurgeryLocoregionalProcedure() {
        return monthOfAdditionalSurgeryLocoregionalProcedure;
    }

    /**
     * Sets the value of the monthOfAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public void setMonthOfAdditionalSurgeryLocoregionalProcedure(MonthOfAdditionalSurgeryLocoregionalProcedure value) {
        this.monthOfAdditionalSurgeryLocoregionalProcedure = value;
    }

    /**
     * Gets the value of the yearOfAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public YearOfAdditionalSurgeryLocoregionalProcedure getYearOfAdditionalSurgeryLocoregionalProcedure() {
        return yearOfAdditionalSurgeryLocoregionalProcedure;
    }

    /**
     * Sets the value of the yearOfAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public void setYearOfAdditionalSurgeryLocoregionalProcedure(YearOfAdditionalSurgeryLocoregionalProcedure value) {
        this.yearOfAdditionalSurgeryLocoregionalProcedure = value;
    }

    /**
     * Gets the value of the daysToAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public DaysToAdditionalSurgeryLocoregionalProcedure getDaysToAdditionalSurgeryLocoregionalProcedure() {
        return daysToAdditionalSurgeryLocoregionalProcedure;
    }

    /**
     * Sets the value of the daysToAdditionalSurgeryLocoregionalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToAdditionalSurgeryLocoregionalProcedure }
     *     
     */
    public void setDaysToAdditionalSurgeryLocoregionalProcedure(DaysToAdditionalSurgeryLocoregionalProcedure value) {
        this.daysToAdditionalSurgeryLocoregionalProcedure = value;
    }

}
