//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.kirc.shared.new_tumor_event._2_7._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.AdditionalPharmaceuticalTherapy;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.AdditionalRadiationTherapy;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DayOfNewTumorEventAfterInitialTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToNewTumorEventAfterInitialTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.MonthOfNewTumorEventAfterInitialTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.YearOfNewTumorEventAfterInitialTreatment;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}day_of_new_tumor_event_after_initial_treatment"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}month_of_new_tumor_event_after_initial_treatment"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}year_of_new_tumor_event_after_initial_treatment"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}days_to_new_tumor_event_after_initial_treatment"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/kirc/shared/new_tumor_event/2.7/1.0}locoregional_procedure"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/kirc/shared/new_tumor_event/2.7/1.0}metastatic_procedure"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}additional_radiation_therapy"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}additional_pharmaceutical_therapy"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dayOfNewTumorEventAfterInitialTreatment",
    "monthOfNewTumorEventAfterInitialTreatment",
    "yearOfNewTumorEventAfterInitialTreatment",
    "daysToNewTumorEventAfterInitialTreatment",
    "locoregionalProcedure",
    "metastaticProcedure",
    "additionalRadiationTherapy",
    "additionalPharmaceuticalTherapy"
})
@XmlRootElement(name = "new_tumor_event")
public class NewTumorEvent {

    @XmlElement(name = "day_of_new_tumor_event_after_initial_treatment", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", nillable = true)
    protected DayOfNewTumorEventAfterInitialTreatment dayOfNewTumorEventAfterInitialTreatment;
    @XmlElement(name = "month_of_new_tumor_event_after_initial_treatment", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", nillable = true)
    protected MonthOfNewTumorEventAfterInitialTreatment monthOfNewTumorEventAfterInitialTreatment;
    @XmlElement(name = "year_of_new_tumor_event_after_initial_treatment", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", nillable = true)
    protected YearOfNewTumorEventAfterInitialTreatment yearOfNewTumorEventAfterInitialTreatment;
    @XmlElement(name = "days_to_new_tumor_event_after_initial_treatment", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7")
    protected DaysToNewTumorEventAfterInitialTreatment daysToNewTumorEventAfterInitialTreatment;
    @XmlElement(name = "locoregional_procedure", required = true)
    protected LocoregionalProcedure locoregionalProcedure;
    @XmlElement(name = "metastatic_procedure", required = true)
    protected MetastaticProcedure metastaticProcedure;
    @XmlElement(name = "additional_radiation_therapy", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", required = true, nillable = true)
    protected AdditionalRadiationTherapy additionalRadiationTherapy;
    @XmlElement(name = "additional_pharmaceutical_therapy", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", required = true, nillable = true)
    protected AdditionalPharmaceuticalTherapy additionalPharmaceuticalTherapy;

    /**
     * Gets the value of the dayOfNewTumorEventAfterInitialTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfNewTumorEventAfterInitialTreatment }
     *     
     */
    public DayOfNewTumorEventAfterInitialTreatment getDayOfNewTumorEventAfterInitialTreatment() {
        return dayOfNewTumorEventAfterInitialTreatment;
    }

    /**
     * Sets the value of the dayOfNewTumorEventAfterInitialTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfNewTumorEventAfterInitialTreatment }
     *     
     */
    public void setDayOfNewTumorEventAfterInitialTreatment(DayOfNewTumorEventAfterInitialTreatment value) {
        this.dayOfNewTumorEventAfterInitialTreatment = value;
    }

    /**
     * Gets the value of the monthOfNewTumorEventAfterInitialTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfNewTumorEventAfterInitialTreatment }
     *     
     */
    public MonthOfNewTumorEventAfterInitialTreatment getMonthOfNewTumorEventAfterInitialTreatment() {
        return monthOfNewTumorEventAfterInitialTreatment;
    }

    /**
     * Sets the value of the monthOfNewTumorEventAfterInitialTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfNewTumorEventAfterInitialTreatment }
     *     
     */
    public void setMonthOfNewTumorEventAfterInitialTreatment(MonthOfNewTumorEventAfterInitialTreatment value) {
        this.monthOfNewTumorEventAfterInitialTreatment = value;
    }

    /**
     * Gets the value of the yearOfNewTumorEventAfterInitialTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfNewTumorEventAfterInitialTreatment }
     *     
     */
    public YearOfNewTumorEventAfterInitialTreatment getYearOfNewTumorEventAfterInitialTreatment() {
        return yearOfNewTumorEventAfterInitialTreatment;
    }

    /**
     * Sets the value of the yearOfNewTumorEventAfterInitialTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfNewTumorEventAfterInitialTreatment }
     *     
     */
    public void setYearOfNewTumorEventAfterInitialTreatment(YearOfNewTumorEventAfterInitialTreatment value) {
        this.yearOfNewTumorEventAfterInitialTreatment = value;
    }

    /**
     * Gets the value of the daysToNewTumorEventAfterInitialTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToNewTumorEventAfterInitialTreatment }
     *     
     */
    public DaysToNewTumorEventAfterInitialTreatment getDaysToNewTumorEventAfterInitialTreatment() {
        return daysToNewTumorEventAfterInitialTreatment;
    }

    /**
     * Sets the value of the daysToNewTumorEventAfterInitialTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToNewTumorEventAfterInitialTreatment }
     *     
     */
    public void setDaysToNewTumorEventAfterInitialTreatment(DaysToNewTumorEventAfterInitialTreatment value) {
        this.daysToNewTumorEventAfterInitialTreatment = value;
    }

    /**
     * Gets the value of the locoregionalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link LocoregionalProcedure }
     *     
     */
    public LocoregionalProcedure getLocoregionalProcedure() {
        return locoregionalProcedure;
    }

    /**
     * Sets the value of the locoregionalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocoregionalProcedure }
     *     
     */
    public void setLocoregionalProcedure(LocoregionalProcedure value) {
        this.locoregionalProcedure = value;
    }

    /**
     * Gets the value of the metastaticProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link MetastaticProcedure }
     *     
     */
    public MetastaticProcedure getMetastaticProcedure() {
        return metastaticProcedure;
    }

    /**
     * Sets the value of the metastaticProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetastaticProcedure }
     *     
     */
    public void setMetastaticProcedure(MetastaticProcedure value) {
        this.metastaticProcedure = value;
    }

    /**
     * Gets the value of the additionalRadiationTherapy property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalRadiationTherapy }
     *     
     */
    public AdditionalRadiationTherapy getAdditionalRadiationTherapy() {
        return additionalRadiationTherapy;
    }

    /**
     * Sets the value of the additionalRadiationTherapy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalRadiationTherapy }
     *     
     */
    public void setAdditionalRadiationTherapy(AdditionalRadiationTherapy value) {
        this.additionalRadiationTherapy = value;
    }

    /**
     * Gets the value of the additionalPharmaceuticalTherapy property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalPharmaceuticalTherapy }
     *     
     */
    public AdditionalPharmaceuticalTherapy getAdditionalPharmaceuticalTherapy() {
        return additionalPharmaceuticalTherapy;
    }

    /**
     * Sets the value of the additionalPharmaceuticalTherapy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalPharmaceuticalTherapy }
     *     
     */
    public void setAdditionalPharmaceuticalTherapy(AdditionalPharmaceuticalTherapy value) {
        this.additionalPharmaceuticalTherapy = value;
    }

}
