//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_tumor_progression"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_tumor_progression"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_tumor_progression"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_tumor_progression" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_patient_progression_free"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_patient_progression_free"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_patient_progression_free"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_patient_progression_free"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "monthOfTumorProgression",
    "dayOfTumorProgression",
    "yearOfTumorProgression",
    "daysToTumorProgression",
    "monthOfPatientProgressionFree",
    "dayOfPatientProgressionFree",
    "yearOfPatientProgressionFree",
    "daysToPatientProgressionFree"
})
@XmlRootElement(name = "progression_dates")
public class ProgressionDates {

    @XmlElement(name = "month_of_tumor_progression", nillable = true)
    protected MonthOfTumorProgression monthOfTumorProgression;
    @XmlElement(name = "day_of_tumor_progression", nillable = true)
    protected DayOfTumorProgression dayOfTumorProgression;
    @XmlElement(name = "year_of_tumor_progression", nillable = true)
    protected YearOfTumorProgression yearOfTumorProgression;
    @XmlElement(name = "days_to_tumor_progression")
    protected DaysToTumorProgression daysToTumorProgression;
    @XmlElement(name = "month_of_patient_progression_free", nillable = true)
    protected MonthOfPatientProgressionFree monthOfPatientProgressionFree;
    @XmlElement(name = "day_of_patient_progression_free", nillable = true)
    protected DayOfPatientProgressionFree dayOfPatientProgressionFree;
    @XmlElement(name = "year_of_patient_progression_free", nillable = true)
    protected YearOfPatientProgressionFree yearOfPatientProgressionFree;
    @XmlElement(name = "days_to_patient_progression_free")
    protected DaysToPatientProgressionFree daysToPatientProgressionFree;

    /**
     * Gets the value of the monthOfTumorProgression property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfTumorProgression }
     *     
     */
    public MonthOfTumorProgression getMonthOfTumorProgression() {
        return monthOfTumorProgression;
    }

    /**
     * Sets the value of the monthOfTumorProgression property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfTumorProgression }
     *     
     */
    public void setMonthOfTumorProgression(MonthOfTumorProgression value) {
        this.monthOfTumorProgression = value;
    }

    /**
     * Gets the value of the dayOfTumorProgression property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfTumorProgression }
     *     
     */
    public DayOfTumorProgression getDayOfTumorProgression() {
        return dayOfTumorProgression;
    }

    /**
     * Sets the value of the dayOfTumorProgression property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfTumorProgression }
     *     
     */
    public void setDayOfTumorProgression(DayOfTumorProgression value) {
        this.dayOfTumorProgression = value;
    }

    /**
     * Gets the value of the yearOfTumorProgression property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfTumorProgression }
     *     
     */
    public YearOfTumorProgression getYearOfTumorProgression() {
        return yearOfTumorProgression;
    }

    /**
     * Sets the value of the yearOfTumorProgression property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfTumorProgression }
     *     
     */
    public void setYearOfTumorProgression(YearOfTumorProgression value) {
        this.yearOfTumorProgression = value;
    }

    /**
     * Gets the value of the daysToTumorProgression property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToTumorProgression }
     *     
     */
    public DaysToTumorProgression getDaysToTumorProgression() {
        return daysToTumorProgression;
    }

    /**
     * Sets the value of the daysToTumorProgression property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToTumorProgression }
     *     
     */
    public void setDaysToTumorProgression(DaysToTumorProgression value) {
        this.daysToTumorProgression = value;
    }

    /**
     * Gets the value of the monthOfPatientProgressionFree property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfPatientProgressionFree }
     *     
     */
    public MonthOfPatientProgressionFree getMonthOfPatientProgressionFree() {
        return monthOfPatientProgressionFree;
    }

    /**
     * Sets the value of the monthOfPatientProgressionFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfPatientProgressionFree }
     *     
     */
    public void setMonthOfPatientProgressionFree(MonthOfPatientProgressionFree value) {
        this.monthOfPatientProgressionFree = value;
    }

    /**
     * Gets the value of the dayOfPatientProgressionFree property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfPatientProgressionFree }
     *     
     */
    public DayOfPatientProgressionFree getDayOfPatientProgressionFree() {
        return dayOfPatientProgressionFree;
    }

    /**
     * Sets the value of the dayOfPatientProgressionFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfPatientProgressionFree }
     *     
     */
    public void setDayOfPatientProgressionFree(DayOfPatientProgressionFree value) {
        this.dayOfPatientProgressionFree = value;
    }

    /**
     * Gets the value of the yearOfPatientProgressionFree property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfPatientProgressionFree }
     *     
     */
    public YearOfPatientProgressionFree getYearOfPatientProgressionFree() {
        return yearOfPatientProgressionFree;
    }

    /**
     * Sets the value of the yearOfPatientProgressionFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfPatientProgressionFree }
     *     
     */
    public void setYearOfPatientProgressionFree(YearOfPatientProgressionFree value) {
        this.yearOfPatientProgressionFree = value;
    }

    /**
     * Gets the value of the daysToPatientProgressionFree property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToPatientProgressionFree }
     *     
     */
    public DaysToPatientProgressionFree getDaysToPatientProgressionFree() {
        return daysToPatientProgressionFree;
    }

    /**
     * Sets the value of the daysToPatientProgressionFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToPatientProgressionFree }
     *     
     */
    public void setDaysToPatientProgressionFree(DaysToPatientProgressionFree value) {
        this.daysToPatientProgressionFree = value;
    }

}
