//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.HistologicalType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.TumorMorphologyPercentage;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}histological_type"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}tumor_morphology_percentage"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "histologicalType",
    "tumorMorphologyPercentage"
})
@XmlRootElement(name = "tumor_morphology")
public class TumorMorphology {

    @XmlElement(name = "histological_type", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true, nillable = true)
    protected HistologicalType histologicalType;
    @XmlElement(name = "tumor_morphology_percentage", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true, nillable = true)
    protected TumorMorphologyPercentage tumorMorphologyPercentage;

    /**
     * Gets the value of the histologicalType property.
     * 
     * @return
     *     possible object is
     *     {@link HistologicalType }
     *     
     */
    public HistologicalType getHistologicalType() {
        return histologicalType;
    }

    /**
     * Sets the value of the histologicalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistologicalType }
     *     
     */
    public void setHistologicalType(HistologicalType value) {
        this.histologicalType = value;
    }

    /**
     * Gets the value of the tumorMorphologyPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link TumorMorphologyPercentage }
     *     
     */
    public TumorMorphologyPercentage getTumorMorphologyPercentage() {
        return tumorMorphologyPercentage;
    }

    /**
     * Sets the value of the tumorMorphologyPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TumorMorphologyPercentage }
     *     
     */
    public void setTumorMorphologyPercentage(TumorMorphologyPercentage value) {
        this.tumorMorphologyPercentage = value;
    }

}
