//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MonthOfChemotherapyEnd_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "month_of_chemotherapy_end");
    private final static QName _DayOfChemotherapyStart_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "day_of_chemotherapy_start");
    private final static QName _DayOfChemotherapyEnd_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "day_of_chemotherapy_end");
    private final static QName _YearOfChemotherapyStart_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "year_of_chemotherapy_start");
    private final static QName _LdhLevel_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "ldh_level");
    private final static QName _LdhNormRangeUpper_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "ldh_norm_range_upper");
    private final static QName _YearOfChemotherapyEnd_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "year_of_chemotherapy_end");
    private final static QName _MaximumTumorBulkAnatomicLocation_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "maximum_tumor_bulk_anatomic_location");
    private final static QName _MonthOfChemotherapyStart_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "month_of_chemotherapy_start");
    private final static QName _ExtranodalInvolvmentSiteOther_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "extranodal_involvment_site_other");
    private final static QName _BoneMarrowSampleHistology_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "bone_marrow_sample_histology");
    private final static QName _ExtranodalSitesInvolvementNumber_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "extranodal_sites_involvement_number");
    private final static QName _PosLymphNodeLocationOther_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "pos_lymph_node_location_other");
    private final static QName _PosLymphNodeLocation_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", "pos_lymph_node_location");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DayOfStemCellTransplantation }
     * 
     */
    public DayOfStemCellTransplantation createDayOfStemCellTransplantation() {
        return new DayOfStemCellTransplantation();
    }

    /**
     * Create an instance of {@link MonthOfStemCellTransplantation }
     * 
     */
    public MonthOfStemCellTransplantation createMonthOfStemCellTransplantation() {
        return new MonthOfStemCellTransplantation();
    }

    /**
     * Create an instance of {@link YearOfStemCellTransplantation }
     * 
     */
    public YearOfStemCellTransplantation createYearOfStemCellTransplantation() {
        return new YearOfStemCellTransplantation();
    }

    /**
     * Create an instance of {@link DaysToStemCellTransplantation }
     * 
     */
    public DaysToStemCellTransplantation createDaysToStemCellTransplantation() {
        return new DaysToStemCellTransplantation();
    }

    /**
     * Create an instance of {@link MaximumTumorBulkAnatomicSite }
     * 
     */
    public MaximumTumorBulkAnatomicSite createMaximumTumorBulkAnatomicSite() {
        return new MaximumTumorBulkAnatomicSite();
    }

    /**
     * Create an instance of {@link IgkGenotypeResults }
     * 
     */
    public IgkGenotypeResults createIgkGenotypeResults() {
        return new IgkGenotypeResults();
    }

    /**
     * Create an instance of {@link MonthOfChemotherapyEnd }
     * 
     */
    public MonthOfChemotherapyEnd createMonthOfChemotherapyEnd() {
        return new MonthOfChemotherapyEnd();
    }

    /**
     * Create an instance of {@link EbvPositiveMalignantCellsPercent }
     * 
     */
    public EbvPositiveMalignantCellsPercent createEbvPositiveMalignantCellsPercent() {
        return new EbvPositiveMalignantCellsPercent();
    }

    /**
     * Create an instance of {@link MaximumTumorBulkAnatomicLocation }
     * 
     */
    public MaximumTumorBulkAnatomicLocation createMaximumTumorBulkAnatomicLocation() {
        return new MaximumTumorBulkAnatomicLocation();
    }

    /**
     * Create an instance of {@link PosLymphNodeLocationOther }
     * 
     */
    public PosLymphNodeLocationOther createPosLymphNodeLocationOther() {
        return new PosLymphNodeLocationOther();
    }

    /**
     * Create an instance of {@link Cd4CountsAtDiagnosis }
     * 
     */
    public Cd4CountsAtDiagnosis createCd4CountsAtDiagnosis() {
        return new Cd4CountsAtDiagnosis();
    }

    /**
     * Create an instance of {@link YearOfCancerDebulkingSurgery }
     * 
     */
    public YearOfCancerDebulkingSurgery createYearOfCancerDebulkingSurgery() {
        return new YearOfCancerDebulkingSurgery();
    }

    /**
     * Create an instance of {@link MonthOfChemotherapyStart }
     * 
     */
    public MonthOfChemotherapyStart createMonthOfChemotherapyStart() {
        return new MonthOfChemotherapyStart();
    }

    /**
     * Create an instance of {@link BoneMarrowSampleHistology }
     * 
     */
    public BoneMarrowSampleHistology createBoneMarrowSampleHistology() {
        return new BoneMarrowSampleHistology();
    }

    /**
     * Create an instance of {@link DayOfChemotherapyStart }
     * 
     */
    public DayOfChemotherapyStart createDayOfChemotherapyStart() {
        return new DayOfChemotherapyStart();
    }

    /**
     * Create an instance of {@link YearOfChemotherapyEnd }
     * 
     */
    public YearOfChemotherapyEnd createYearOfChemotherapyEnd() {
        return new YearOfChemotherapyEnd();
    }

    /**
     * Create an instance of {@link PriorAidsConditions }
     * 
     */
    public PriorAidsConditions createPriorAidsConditions() {
        return new PriorAidsConditions();
    }

    /**
     * Create an instance of {@link FollicularComponentPercent }
     * 
     */
    public FollicularComponentPercent createFollicularComponentPercent() {
        return new FollicularComponentPercent();
    }

    /**
     * Create an instance of {@link OnHaartTherapyAtCancerDiagnosis }
     * 
     */
    public OnHaartTherapyAtCancerDiagnosis createOnHaartTherapyAtCancerDiagnosis() {
        return new OnHaartTherapyAtCancerDiagnosis();
    }

    /**
     * Create an instance of {@link DaysToChemotherapyStart }
     * 
     */
    public DaysToChemotherapyStart createDaysToChemotherapyStart() {
        return new DaysToChemotherapyStart();
    }

    /**
     * Create an instance of {@link HistoryImmunosuppressiveRxOther }
     * 
     */
    public HistoryImmunosuppressiveRxOther createHistoryImmunosuppressiveRxOther() {
        return new HistoryImmunosuppressiveRxOther();
    }

    /**
     * Create an instance of {@link HistoryOfOtherMalignancy }
     * 
     */
    public HistoryOfOtherMalignancy createHistoryOfOtherMalignancy() {
        return new HistoryOfOtherMalignancy();
    }

    /**
     * Create an instance of {@link LdhNormRangeUpper }
     * 
     */
    public LdhNormRangeUpper createLdhNormRangeUpper() {
        return new LdhNormRangeUpper();
    }

    /**
     * Create an instance of {@link HistoryImmunologicalDisease }
     * 
     */
    public HistoryImmunologicalDisease createHistoryImmunologicalDisease() {
        return new HistoryImmunologicalDisease();
    }

    /**
     * Create an instance of {@link DaysToCancerDebulkingSurgery }
     * 
     */
    public DaysToCancerDebulkingSurgery createDaysToCancerDebulkingSurgery() {
        return new DaysToCancerDebulkingSurgery();
    }

    /**
     * Create an instance of {@link HivRnaLoadAtDiagnosis }
     * 
     */
    public HivRnaLoadAtDiagnosis createHivRnaLoadAtDiagnosis() {
        return new HivRnaLoadAtDiagnosis();
    }

    /**
     * Create an instance of {@link MonthOfCancerDebulkingSurgery }
     * 
     */
    public MonthOfCancerDebulkingSurgery createMonthOfCancerDebulkingSurgery() {
        return new MonthOfCancerDebulkingSurgery();
    }

    /**
     * Create an instance of {@link OnHaartTherapyPriorToCancerDiagnosis }
     * 
     */
    public OnHaartTherapyPriorToCancerDiagnosis createOnHaartTherapyPriorToCancerDiagnosis() {
        return new OnHaartTherapyPriorToCancerDiagnosis();
    }

    /**
     * Create an instance of {@link ExtranodalInvolvmentSiteOther }
     * 
     */
    public ExtranodalInvolvmentSiteOther createExtranodalInvolvmentSiteOther() {
        return new ExtranodalInvolvmentSiteOther();
    }

    /**
     * Create an instance of {@link HcvTest }
     * 
     */
    public HcvTest createHcvTest() {
        return new HcvTest();
    }

    /**
     * Create an instance of {@link DaysToHivDiagnosis }
     * 
     */
    public DaysToHivDiagnosis createDaysToHivDiagnosis() {
        return new DaysToHivDiagnosis();
    }

    /**
     * Create an instance of {@link EbvStatusMalignantCellsMethod }
     * 
     */
    public EbvStatusMalignantCellsMethod createEbvStatusMalignantCellsMethod() {
        return new EbvStatusMalignantCellsMethod();
    }

    /**
     * Create an instance of {@link BoneMarrowBiopsyDone }
     * 
     */
    public BoneMarrowBiopsyDone createBoneMarrowBiopsyDone() {
        return new BoneMarrowBiopsyDone();
    }

    /**
     * Create an instance of {@link BoneMarrowInvolvement }
     * 
     */
    public BoneMarrowInvolvement createBoneMarrowInvolvement() {
        return new BoneMarrowInvolvement();
    }

    /**
     * Create an instance of {@link LymphNodeInvolvementSite }
     * 
     */
    public LymphNodeInvolvementSite createLymphNodeInvolvementSite() {
        return new LymphNodeInvolvementSite();
    }

    /**
     * Create an instance of {@link HpvTest }
     * 
     */
    public HpvTest createHpvTest() {
        return new HpvTest();
    }

    /**
     * Create an instance of {@link ExtranodalInvolvementSite }
     * 
     */
    public ExtranodalInvolvementSite createExtranodalInvolvementSite() {
        return new ExtranodalInvolvementSite();
    }

    /**
     * Create an instance of {@link NadirCd4Counts }
     * 
     */
    public NadirCd4Counts createNadirCd4Counts() {
        return new NadirCd4Counts();
    }

    /**
     * Create an instance of {@link HistoryRelevantInfectiousDxOther }
     * 
     */
    public HistoryRelevantInfectiousDxOther createHistoryRelevantInfectiousDxOther() {
        return new HistoryRelevantInfectiousDxOther();
    }

    /**
     * Create an instance of {@link Mib1PositivePercentageRange }
     * 
     */
    public Mib1PositivePercentageRange createMib1PositivePercentageRange() {
        return new Mib1PositivePercentageRange();
    }

    /**
     * Create an instance of {@link BLymphocyteGenotypingMethod }
     * 
     */
    public BLymphocyteGenotypingMethod createBLymphocyteGenotypingMethod() {
        return new BLymphocyteGenotypingMethod();
    }

    /**
     * Create an instance of {@link HistoryImmunosuppresiveRx }
     * 
     */
    public HistoryImmunosuppresiveRx createHistoryImmunosuppresiveRx() {
        return new HistoryImmunosuppresiveRx();
    }

    /**
     * Create an instance of {@link PosLymphNodeLocation }
     * 
     */
    public PosLymphNodeLocation createPosLymphNodeLocation() {
        return new PosLymphNodeLocation();
    }

    /**
     * Create an instance of {@link HistoryImmunologicalDiseaseOther }
     * 
     */
    public HistoryImmunologicalDiseaseOther createHistoryImmunologicalDiseaseOther() {
        return new HistoryImmunologicalDiseaseOther();
    }

    /**
     * Create an instance of {@link HistoryRelevantInfectiousDx }
     * 
     */
    public HistoryRelevantInfectiousDx createHistoryRelevantInfectiousDx() {
        return new HistoryRelevantInfectiousDx();
    }

    /**
     * Create an instance of {@link HbvTest }
     * 
     */
    public HbvTest createHbvTest() {
        return new HbvTest();
    }

    /**
     * Create an instance of {@link MonthOfHivDiagnosis }
     * 
     */
    public MonthOfHivDiagnosis createMonthOfHivDiagnosis() {
        return new MonthOfHivDiagnosis();
    }

    /**
     * Create an instance of {@link YearOfChemotherapyStart }
     * 
     */
    public YearOfChemotherapyStart createYearOfChemotherapyStart() {
        return new YearOfChemotherapyStart();
    }

    /**
     * Create an instance of {@link CdcHivRiskGroup }
     * 
     */
    public CdcHivRiskGroup createCdcHivRiskGroup() {
        return new CdcHivRiskGroup();
    }

    /**
     * Create an instance of {@link ExtranodalSitesInvolvementNumber }
     * 
     */
    public ExtranodalSitesInvolvementNumber createExtranodalSitesInvolvementNumber() {
        return new ExtranodalSitesInvolvementNumber();
    }

    /**
     * Create an instance of {@link EpsteinBarrViralStatus }
     * 
     */
    public EpsteinBarrViralStatus createEpsteinBarrViralStatus() {
        return new EpsteinBarrViralStatus();
    }

    /**
     * Create an instance of {@link YearOfHivDiagnosis }
     * 
     */
    public YearOfHivDiagnosis createYearOfHivDiagnosis() {
        return new YearOfHivDiagnosis();
    }

    /**
     * Create an instance of {@link IghGenotypeResults }
     * 
     */
    public IghGenotypeResults createIghGenotypeResults() {
        return new IghGenotypeResults();
    }

    /**
     * Create an instance of {@link DayOfCancerDebulkingSurgery }
     * 
     */
    public DayOfCancerDebulkingSurgery createDayOfCancerDebulkingSurgery() {
        return new DayOfCancerDebulkingSurgery();
    }

    /**
     * Create an instance of {@link KshvHhv8Test }
     * 
     */
    public KshvHhv8Test createKshvHhv8Test() {
        return new KshvHhv8Test();
    }

    /**
     * Create an instance of {@link LdhLevel }
     * 
     */
    public LdhLevel createLdhLevel() {
        return new LdhLevel();
    }

    /**
     * Create an instance of {@link DayOfChemotherapyEnd }
     * 
     */
    public DayOfChemotherapyEnd createDayOfChemotherapyEnd() {
        return new DayOfChemotherapyEnd();
    }

    /**
     * Create an instance of {@link DaysToChemotherapyEnd }
     * 
     */
    public DaysToChemotherapyEnd createDaysToChemotherapyEnd() {
        return new DaysToChemotherapyEnd();
    }

    /**
     * Create an instance of {@link DayOfHivDiagnosis }
     * 
     */
    public DayOfHivDiagnosis createDayOfHivDiagnosis() {
        return new DayOfHivDiagnosis();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonthOfChemotherapyEnd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "month_of_chemotherapy_end")
    public JAXBElement<MonthOfChemotherapyEnd> createMonthOfChemotherapyEnd(MonthOfChemotherapyEnd value) {
        return new JAXBElement<MonthOfChemotherapyEnd>(_MonthOfChemotherapyEnd_QNAME, MonthOfChemotherapyEnd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DayOfChemotherapyStart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "day_of_chemotherapy_start")
    public JAXBElement<DayOfChemotherapyStart> createDayOfChemotherapyStart(DayOfChemotherapyStart value) {
        return new JAXBElement<DayOfChemotherapyStart>(_DayOfChemotherapyStart_QNAME, DayOfChemotherapyStart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DayOfChemotherapyEnd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "day_of_chemotherapy_end")
    public JAXBElement<DayOfChemotherapyEnd> createDayOfChemotherapyEnd(DayOfChemotherapyEnd value) {
        return new JAXBElement<DayOfChemotherapyEnd>(_DayOfChemotherapyEnd_QNAME, DayOfChemotherapyEnd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YearOfChemotherapyStart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "year_of_chemotherapy_start")
    public JAXBElement<YearOfChemotherapyStart> createYearOfChemotherapyStart(YearOfChemotherapyStart value) {
        return new JAXBElement<YearOfChemotherapyStart>(_YearOfChemotherapyStart_QNAME, YearOfChemotherapyStart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdhLevel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "ldh_level")
    public JAXBElement<LdhLevel> createLdhLevel(LdhLevel value) {
        return new JAXBElement<LdhLevel>(_LdhLevel_QNAME, LdhLevel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdhNormRangeUpper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "ldh_norm_range_upper")
    public JAXBElement<LdhNormRangeUpper> createLdhNormRangeUpper(LdhNormRangeUpper value) {
        return new JAXBElement<LdhNormRangeUpper>(_LdhNormRangeUpper_QNAME, LdhNormRangeUpper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YearOfChemotherapyEnd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "year_of_chemotherapy_end")
    public JAXBElement<YearOfChemotherapyEnd> createYearOfChemotherapyEnd(YearOfChemotherapyEnd value) {
        return new JAXBElement<YearOfChemotherapyEnd>(_YearOfChemotherapyEnd_QNAME, YearOfChemotherapyEnd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaximumTumorBulkAnatomicLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "maximum_tumor_bulk_anatomic_location")
    public JAXBElement<MaximumTumorBulkAnatomicLocation> createMaximumTumorBulkAnatomicLocation(MaximumTumorBulkAnatomicLocation value) {
        return new JAXBElement<MaximumTumorBulkAnatomicLocation>(_MaximumTumorBulkAnatomicLocation_QNAME, MaximumTumorBulkAnatomicLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonthOfChemotherapyStart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "month_of_chemotherapy_start")
    public JAXBElement<MonthOfChemotherapyStart> createMonthOfChemotherapyStart(MonthOfChemotherapyStart value) {
        return new JAXBElement<MonthOfChemotherapyStart>(_MonthOfChemotherapyStart_QNAME, MonthOfChemotherapyStart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtranodalInvolvmentSiteOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "extranodal_involvment_site_other")
    public JAXBElement<ExtranodalInvolvmentSiteOther> createExtranodalInvolvmentSiteOther(ExtranodalInvolvmentSiteOther value) {
        return new JAXBElement<ExtranodalInvolvmentSiteOther>(_ExtranodalInvolvmentSiteOther_QNAME, ExtranodalInvolvmentSiteOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoneMarrowSampleHistology }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "bone_marrow_sample_histology")
    public JAXBElement<BoneMarrowSampleHistology> createBoneMarrowSampleHistology(BoneMarrowSampleHistology value) {
        return new JAXBElement<BoneMarrowSampleHistology>(_BoneMarrowSampleHistology_QNAME, BoneMarrowSampleHistology.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtranodalSitesInvolvementNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "extranodal_sites_involvement_number")
    public JAXBElement<ExtranodalSitesInvolvementNumber> createExtranodalSitesInvolvementNumber(ExtranodalSitesInvolvementNumber value) {
        return new JAXBElement<ExtranodalSitesInvolvementNumber>(_ExtranodalSitesInvolvementNumber_QNAME, ExtranodalSitesInvolvementNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PosLymphNodeLocationOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "pos_lymph_node_location_other")
    public JAXBElement<PosLymphNodeLocationOther> createPosLymphNodeLocationOther(PosLymphNodeLocationOther value) {
        return new JAXBElement<PosLymphNodeLocationOther>(_PosLymphNodeLocationOther_QNAME, PosLymphNodeLocationOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PosLymphNodeLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7", name = "pos_lymph_node_location")
    public JAXBElement<PosLymphNodeLocation> createPosLymphNodeLocation(PosLymphNodeLocation value) {
        return new JAXBElement<PosLymphNodeLocation>(_PosLymphNodeLocation_QNAME, PosLymphNodeLocation.class, null, value);
    }

}
