//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_patient_canonical_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_patient_canonical_reasons" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bcrPatientCanonicalStatus",
    "bcrPatientCanonicalReasons"
})
@XmlRootElement(name = "bcr_canonical_check")
public class BcrCanonicalCheck {

    @XmlElement(name = "bcr_patient_canonical_status", required = true)
    protected BcrPatientCanonicalStatus bcrPatientCanonicalStatus;
    @XmlElement(name = "bcr_patient_canonical_reasons")
    protected BcrPatientCanonicalReasons bcrPatientCanonicalReasons;

    /**
     * Gets the value of the bcrPatientCanonicalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BcrPatientCanonicalStatus }
     *     
     */
    public BcrPatientCanonicalStatus getBcrPatientCanonicalStatus() {
        return bcrPatientCanonicalStatus;
    }

    /**
     * Sets the value of the bcrPatientCanonicalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrPatientCanonicalStatus }
     *     
     */
    public void setBcrPatientCanonicalStatus(BcrPatientCanonicalStatus value) {
        this.bcrPatientCanonicalStatus = value;
    }

    /**
     * Gets the value of the bcrPatientCanonicalReasons property.
     * 
     * @return
     *     possible object is
     *     {@link BcrPatientCanonicalReasons }
     *     
     */
    public BcrPatientCanonicalReasons getBcrPatientCanonicalReasons() {
        return bcrPatientCanonicalReasons;
    }

    /**
     * Sets the value of the bcrPatientCanonicalReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrPatientCanonicalReasons }
     *     
     */
    public void setBcrPatientCanonicalReasons(BcrPatientCanonicalReasons value) {
        this.bcrPatientCanonicalReasons = value;
    }

}
