//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}normal_tumor_genotype_match"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}pcr_amplification_successful"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "normalTumorGenotypeMatch",
    "pcrAmplificationSuccessful"
})
@XmlRootElement(name = "dna")
public class Dna {

    @XmlElement(name = "normal_tumor_genotype_match", required = true)
    protected NormalTumorGenotypeMatch normalTumorGenotypeMatch;
    @XmlElement(name = "pcr_amplification_successful", required = true)
    protected PcrAmplificationSuccessful pcrAmplificationSuccessful;

    /**
     * Gets the value of the normalTumorGenotypeMatch property.
     * 
     * @return
     *     possible object is
     *     {@link NormalTumorGenotypeMatch }
     *     
     */
    public NormalTumorGenotypeMatch getNormalTumorGenotypeMatch() {
        return normalTumorGenotypeMatch;
    }

    /**
     * Sets the value of the normalTumorGenotypeMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link NormalTumorGenotypeMatch }
     *     
     */
    public void setNormalTumorGenotypeMatch(NormalTumorGenotypeMatch value) {
        this.normalTumorGenotypeMatch = value;
    }

    /**
     * Gets the value of the pcrAmplificationSuccessful property.
     * 
     * @return
     *     possible object is
     *     {@link PcrAmplificationSuccessful }
     *     
     */
    public PcrAmplificationSuccessful getPcrAmplificationSuccessful() {
        return pcrAmplificationSuccessful;
    }

    /**
     * Sets the value of the pcrAmplificationSuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcrAmplificationSuccessful }
     *     
     */
    public void setPcrAmplificationSuccessful(PcrAmplificationSuccessful value) {
        this.pcrAmplificationSuccessful = value;
    }

}
