//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}hpv_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}hpv_call" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hpvStatus",
    "hpvCall"
})
@XmlRootElement(name = "hpv_test_result")
public class HpvTestResult {

    @XmlElement(name = "hpv_status", required = true)
    protected HpvStatus hpvStatus;
    @XmlElement(name = "hpv_call")
    protected List<HpvCall> hpvCall;

    /**
     * Gets the value of the hpvStatus property.
     * 
     * @return
     *     possible object is
     *     {@link HpvStatus }
     *     
     */
    public HpvStatus getHpvStatus() {
        return hpvStatus;
    }

    /**
     * Sets the value of the hpvStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HpvStatus }
     *     
     */
    public void setHpvStatus(HpvStatus value) {
        this.hpvStatus = value;
    }

    /**
     * Gets the value of the hpvCall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hpvCall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHpvCall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HpvCall }
     * 
     * 
     */
    public List<HpvCall> getHpvCall() {
        if (hpvCall == null) {
            hpvCall = new ArrayList<HpvCall>();
        }
        return this.hpvCall;
    }

}
