//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.utility._2.CommonResAttributes;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}histologic_nuclear_grade"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tumor_sample_anatomic_location"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tumor_sample_anatomic_location"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_stage_grouping"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_tumor_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_lymphnode_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_metastatic_status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "lung_pathology")
public class LungPathology {

    @XmlElementRefs({
        @XmlElementRef(name = "tnm_pathology_metastatic_status", namespace = "http://tcga.nci/bcr/xml/biospecimen/2.7", type = TnmPathologyMetastaticStatus.class, required = false),
        @XmlElementRef(name = "tumor_sample_anatomic_location", namespace = "http://tcga.nci/bcr/xml/biospecimen/2.7", type = TumorSampleAnatomicLocation.class, required = false),
        @XmlElementRef(name = "tnm_pathology_lymphnode_status", namespace = "http://tcga.nci/bcr/xml/biospecimen/2.7", type = TnmPathologyLymphnodeStatus.class, required = false),
        @XmlElementRef(name = "tnm_pathology_stage_grouping", namespace = "http://tcga.nci/bcr/xml/biospecimen/2.7", type = TnmPathologyStageGrouping.class, required = false),
        @XmlElementRef(name = "histologic_nuclear_grade", namespace = "http://tcga.nci/bcr/xml/biospecimen/2.7", type = HistologicNuclearGrade.class, required = false),
        @XmlElementRef(name = "tnm_pathology_tumor_status", namespace = "http://tcga.nci/bcr/xml/biospecimen/2.7", type = TnmPathologyTumorStatus.class, required = false)
    })
    protected List<CommonResAttributes> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "TumorSampleAnatomicLocation" is used by two different parts of a schema. See: 
     * line 1489 of file:/Users/Dixit/Documents/github/gsoc/data/biospecimen_xsd/tcga_bcr_biospecimen.xml
     * line 1488 of file:/Users/Dixit/Documents/github/gsoc/data/biospecimen_xsd/tcga_bcr_biospecimen.xml
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TnmPathologyLymphnodeStatus }
     * {@link TnmPathologyStageGrouping }
     * {@link TnmPathologyMetastaticStatus }
     * {@link HistologicNuclearGrade }
     * {@link TnmPathologyTumorStatus }
     * {@link TumorSampleAnatomicLocation }
     * 
     * 
     */
    public List<CommonResAttributes> getContent() {
        if (content == null) {
            content = new ArrayList<CommonResAttributes>();
        }
        return this.content;
    }

}
