//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}histologic_nuclear_grade"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tumor_sample_anatomic_location"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_stage_grouping"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_tumor_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_lymphnode_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tnm_pathology_metastatic_status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "histologicNuclearGrade",
    "tumorSampleAnatomicLocation",
    "tnmPathologyStageGrouping",
    "tnmPathologyTumorStatus",
    "tnmPathologyLymphnodeStatus",
    "tnmPathologyMetastaticStatus"
})
@XmlRootElement(name = "ovarian_pathology")
public class OvarianPathology {

    @XmlElement(name = "histologic_nuclear_grade", required = true)
    protected HistologicNuclearGrade histologicNuclearGrade;
    @XmlElement(name = "tumor_sample_anatomic_location", required = true)
    protected TumorSampleAnatomicLocation tumorSampleAnatomicLocation;
    @XmlElement(name = "tnm_pathology_stage_grouping", required = true)
    protected TnmPathologyStageGrouping tnmPathologyStageGrouping;
    @XmlElement(name = "tnm_pathology_tumor_status", required = true)
    protected TnmPathologyTumorStatus tnmPathologyTumorStatus;
    @XmlElement(name = "tnm_pathology_lymphnode_status", required = true)
    protected TnmPathologyLymphnodeStatus tnmPathologyLymphnodeStatus;
    @XmlElement(name = "tnm_pathology_metastatic_status", required = true)
    protected TnmPathologyMetastaticStatus tnmPathologyMetastaticStatus;

    /**
     * Gets the value of the histologicNuclearGrade property.
     * 
     * @return
     *     possible object is
     *     {@link HistologicNuclearGrade }
     *     
     */
    public HistologicNuclearGrade getHistologicNuclearGrade() {
        return histologicNuclearGrade;
    }

    /**
     * Sets the value of the histologicNuclearGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistologicNuclearGrade }
     *     
     */
    public void setHistologicNuclearGrade(HistologicNuclearGrade value) {
        this.histologicNuclearGrade = value;
    }

    /**
     * Gets the value of the tumorSampleAnatomicLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TumorSampleAnatomicLocation }
     *     
     */
    public TumorSampleAnatomicLocation getTumorSampleAnatomicLocation() {
        return tumorSampleAnatomicLocation;
    }

    /**
     * Sets the value of the tumorSampleAnatomicLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TumorSampleAnatomicLocation }
     *     
     */
    public void setTumorSampleAnatomicLocation(TumorSampleAnatomicLocation value) {
        this.tumorSampleAnatomicLocation = value;
    }

    /**
     * Gets the value of the tnmPathologyStageGrouping property.
     * 
     * @return
     *     possible object is
     *     {@link TnmPathologyStageGrouping }
     *     
     */
    public TnmPathologyStageGrouping getTnmPathologyStageGrouping() {
        return tnmPathologyStageGrouping;
    }

    /**
     * Sets the value of the tnmPathologyStageGrouping property.
     * 
     * @param value
     *     allowed object is
     *     {@link TnmPathologyStageGrouping }
     *     
     */
    public void setTnmPathologyStageGrouping(TnmPathologyStageGrouping value) {
        this.tnmPathologyStageGrouping = value;
    }

    /**
     * Gets the value of the tnmPathologyTumorStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TnmPathologyTumorStatus }
     *     
     */
    public TnmPathologyTumorStatus getTnmPathologyTumorStatus() {
        return tnmPathologyTumorStatus;
    }

    /**
     * Sets the value of the tnmPathologyTumorStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TnmPathologyTumorStatus }
     *     
     */
    public void setTnmPathologyTumorStatus(TnmPathologyTumorStatus value) {
        this.tnmPathologyTumorStatus = value;
    }

    /**
     * Gets the value of the tnmPathologyLymphnodeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TnmPathologyLymphnodeStatus }
     *     
     */
    public TnmPathologyLymphnodeStatus getTnmPathologyLymphnodeStatus() {
        return tnmPathologyLymphnodeStatus;
    }

    /**
     * Sets the value of the tnmPathologyLymphnodeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TnmPathologyLymphnodeStatus }
     *     
     */
    public void setTnmPathologyLymphnodeStatus(TnmPathologyLymphnodeStatus value) {
        this.tnmPathologyLymphnodeStatus = value;
    }

    /**
     * Gets the value of the tnmPathologyMetastaticStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TnmPathologyMetastaticStatus }
     *     
     */
    public TnmPathologyMetastaticStatus getTnmPathologyMetastaticStatus() {
        return tnmPathologyMetastaticStatus;
    }

    /**
     * Sets the value of the tnmPathologyMetastaticStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TnmPathologyMetastaticStatus }
     *     
     */
    public void setTnmPathologyMetastaticStatus(TnmPathologyMetastaticStatus value) {
        this.tnmPathologyMetastaticStatus = value;
    }

}
