//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2.AdditionalStudies;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2.AlternateIdentifiers;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.Notes;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}notes" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/administration/2.7}additional_studies" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/administration/2.7}alternate_identifiers" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}portion_number"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}portion_sequence" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}day_of_creation"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}month_of_creation"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}year_of_creation"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}weight"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_portion_barcode"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_portion_uuid"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}is_ffpe" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_biospecimen_canonical_reasons" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}analytes"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}slides"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}LCE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notes",
    "additionalStudies",
    "alternateIdentifiers",
    "portionNumber",
    "portionSequence",
    "dayOfCreation",
    "monthOfCreation",
    "yearOfCreation",
    "weight",
    "bcrPortionBarcode",
    "bcrPortionUuid",
    "isFfpe",
    "bcrBiospecimenCanonicalReasons",
    "analytes",
    "slides",
    "lce"
})
@XmlRootElement(name = "portion")
public class Portion {

    @XmlElement(namespace = "http://tcga.nci/bcr/xml/shared/2.7")
    protected Notes notes;
    @XmlElement(name = "additional_studies", namespace = "http://tcga.nci/bcr/xml/administration/2.7")
    protected AdditionalStudies additionalStudies;
    @XmlElement(name = "alternate_identifiers", namespace = "http://tcga.nci/bcr/xml/administration/2.7")
    protected AlternateIdentifiers alternateIdentifiers;
    @XmlElement(name = "portion_number", required = true, nillable = true)
    protected PortionNumber portionNumber;
    @XmlElement(name = "portion_sequence", nillable = true)
    protected PortionSequence portionSequence;
    @XmlElement(name = "day_of_creation", required = true)
    protected DayOfCreation dayOfCreation;
    @XmlElement(name = "month_of_creation", required = true)
    protected MonthOfCreation monthOfCreation;
    @XmlElement(name = "year_of_creation", required = true)
    protected YearOfCreation yearOfCreation;
    @XmlElement(required = true)
    protected Weight weight;
    @XmlElement(name = "bcr_portion_barcode", required = true)
    protected BcrPortionBarcode bcrPortionBarcode;
    @XmlElement(name = "bcr_portion_uuid", required = true)
    protected BcrPortionUuid bcrPortionUuid;
    @XmlElement(name = "is_ffpe")
    protected IsFfpe isFfpe;
    @XmlElement(name = "bcr_biospecimen_canonical_reasons")
    protected BcrBiospecimenCanonicalReasons bcrBiospecimenCanonicalReasons;
    @XmlElement(required = true)
    protected Analytes analytes;
    @XmlElement(required = true)
    protected Slides slides;
    @XmlElement(name = "LCE", required = true)
    protected LCE lce;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the additionalStudies property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStudies }
     *     
     */
    public AdditionalStudies getAdditionalStudies() {
        return additionalStudies;
    }

    /**
     * Sets the value of the additionalStudies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStudies }
     *     
     */
    public void setAdditionalStudies(AdditionalStudies value) {
        this.additionalStudies = value;
    }

    /**
     * Gets the value of the alternateIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateIdentifiers }
     *     
     */
    public AlternateIdentifiers getAlternateIdentifiers() {
        return alternateIdentifiers;
    }

    /**
     * Sets the value of the alternateIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateIdentifiers }
     *     
     */
    public void setAlternateIdentifiers(AlternateIdentifiers value) {
        this.alternateIdentifiers = value;
    }

    /**
     * Gets the value of the portionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PortionNumber }
     *     
     */
    public PortionNumber getPortionNumber() {
        return portionNumber;
    }

    /**
     * Sets the value of the portionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortionNumber }
     *     
     */
    public void setPortionNumber(PortionNumber value) {
        this.portionNumber = value;
    }

    /**
     * Gets the value of the portionSequence property.
     * 
     * @return
     *     possible object is
     *     {@link PortionSequence }
     *     
     */
    public PortionSequence getPortionSequence() {
        return portionSequence;
    }

    /**
     * Sets the value of the portionSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortionSequence }
     *     
     */
    public void setPortionSequence(PortionSequence value) {
        this.portionSequence = value;
    }

    /**
     * Gets the value of the dayOfCreation property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfCreation }
     *     
     */
    public DayOfCreation getDayOfCreation() {
        return dayOfCreation;
    }

    /**
     * Sets the value of the dayOfCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfCreation }
     *     
     */
    public void setDayOfCreation(DayOfCreation value) {
        this.dayOfCreation = value;
    }

    /**
     * Gets the value of the monthOfCreation property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfCreation }
     *     
     */
    public MonthOfCreation getMonthOfCreation() {
        return monthOfCreation;
    }

    /**
     * Sets the value of the monthOfCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfCreation }
     *     
     */
    public void setMonthOfCreation(MonthOfCreation value) {
        this.monthOfCreation = value;
    }

    /**
     * Gets the value of the yearOfCreation property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfCreation }
     *     
     */
    public YearOfCreation getYearOfCreation() {
        return yearOfCreation;
    }

    /**
     * Sets the value of the yearOfCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfCreation }
     *     
     */
    public void setYearOfCreation(YearOfCreation value) {
        this.yearOfCreation = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

    /**
     * Gets the value of the bcrPortionBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link BcrPortionBarcode }
     *     
     */
    public BcrPortionBarcode getBcrPortionBarcode() {
        return bcrPortionBarcode;
    }

    /**
     * Sets the value of the bcrPortionBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrPortionBarcode }
     *     
     */
    public void setBcrPortionBarcode(BcrPortionBarcode value) {
        this.bcrPortionBarcode = value;
    }

    /**
     * Gets the value of the bcrPortionUuid property.
     * 
     * @return
     *     possible object is
     *     {@link BcrPortionUuid }
     *     
     */
    public BcrPortionUuid getBcrPortionUuid() {
        return bcrPortionUuid;
    }

    /**
     * Sets the value of the bcrPortionUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrPortionUuid }
     *     
     */
    public void setBcrPortionUuid(BcrPortionUuid value) {
        this.bcrPortionUuid = value;
    }

    /**
     * Gets the value of the isFfpe property.
     * 
     * @return
     *     possible object is
     *     {@link IsFfpe }
     *     
     */
    public IsFfpe getIsFfpe() {
        return isFfpe;
    }

    /**
     * Sets the value of the isFfpe property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsFfpe }
     *     
     */
    public void setIsFfpe(IsFfpe value) {
        this.isFfpe = value;
    }

    /**
     * Gets the value of the bcrBiospecimenCanonicalReasons property.
     * 
     * @return
     *     possible object is
     *     {@link BcrBiospecimenCanonicalReasons }
     *     
     */
    public BcrBiospecimenCanonicalReasons getBcrBiospecimenCanonicalReasons() {
        return bcrBiospecimenCanonicalReasons;
    }

    /**
     * Sets the value of the bcrBiospecimenCanonicalReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrBiospecimenCanonicalReasons }
     *     
     */
    public void setBcrBiospecimenCanonicalReasons(BcrBiospecimenCanonicalReasons value) {
        this.bcrBiospecimenCanonicalReasons = value;
    }

    /**
     * Gets the value of the analytes property.
     * 
     * @return
     *     possible object is
     *     {@link Analytes }
     *     
     */
    public Analytes getAnalytes() {
        return analytes;
    }

    /**
     * Sets the value of the analytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Analytes }
     *     
     */
    public void setAnalytes(Analytes value) {
        this.analytes = value;
    }

    /**
     * Gets the value of the slides property.
     * 
     * @return
     *     possible object is
     *     {@link Slides }
     *     
     */
    public Slides getSlides() {
        return slides;
    }

    /**
     * Sets the value of the slides property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slides }
     *     
     */
    public void setSlides(Slides value) {
        this.slides = value;
    }

    /**
     * Gets the value of the lce property.
     * 
     * @return
     *     possible object is
     *     {@link LCE }
     *     
     */
    public LCE getLCE() {
        return lce;
    }

    /**
     * Sets the value of the lce property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCE }
     *     
     */
    public void setLCE(LCE value) {
        this.lce = value;
    }

}
