//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}ratio_28s_18s"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}rinvalue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ratio28S18S",
    "rinvalue"
})
@XmlRootElement(name = "rna")
public class Rna {

    @XmlElement(name = "ratio_28s_18s", required = true)
    protected Ratio28S18S ratio28S18S;
    @XmlElement(required = true)
    protected Rinvalue rinvalue;

    /**
     * Gets the value of the ratio28S18S property.
     * 
     * @return
     *     possible object is
     *     {@link Ratio28S18S }
     *     
     */
    public Ratio28S18S getRatio28S18S() {
        return ratio28S18S;
    }

    /**
     * Sets the value of the ratio28S18S property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ratio28S18S }
     *     
     */
    public void setRatio28S18S(Ratio28S18S value) {
        this.ratio28S18S = value;
    }

    /**
     * Gets the value of the rinvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Rinvalue }
     *     
     */
    public Rinvalue getRinvalue() {
        return rinvalue;
    }

    /**
     * Sets the value of the rinvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rinvalue }
     *     
     */
    public void setRinvalue(Rinvalue value) {
        this.rinvalue = value;
    }

}
