//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 07:06:08 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2.AdditionalStudies;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2.AlternateIdentifiers;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.biospecimen.shared._2.OtherMethodOfSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.DayOfSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.DaysToSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.MonthOfSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.Notes;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.YearOfSampleProcurement;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}notes" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/administration/2.7}additional_studies" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/administration/2.7}alternate_identifiers" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}specimen_fraction_ordinal" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}sample_type_id"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}vial_number"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}biospecimen_sequence" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}sample_type"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}longest_dimension"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}intermediate_dimension"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}shortest_dimension"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}initial_weight"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}current_weight"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}freezing_method"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}oct_embedded"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}preservation_method" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tissue_type" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}composition" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tumor_descriptor" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}day_of_collection"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}month_of_collection"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}year_of_collection"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}days_to_collection"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}time_between_clamping_and_freezing"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}time_between_excision_and_freezing"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_sample_barcode"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_sample_uuid"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}is_ffpe" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}bcr_biospecimen_canonical_reasons" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}portions"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}tumor_pathology"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}method_of_sample_procurement"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/shared/2.7}other_method_of_sample_procurement" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}day_of_sample_procurement"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}month_of_sample_procurement"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}year_of_sample_procurement"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}days_to_sample_procurement"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}pathology_report_uuid"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}pathology_report_file_name" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/biospecimen/2.7}diagnostic_slides"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notes",
    "additionalStudies",
    "alternateIdentifiers",
    "specimenFractionOrdinal",
    "sampleTypeId",
    "vialNumber",
    "biospecimenSequence",
    "sampleType",
    "longestDimension",
    "intermediateDimension",
    "shortestDimension",
    "initialWeight",
    "currentWeight",
    "freezingMethod",
    "octEmbedded",
    "preservationMethod",
    "tissueType",
    "composition",
    "tumorDescriptor",
    "dayOfCollection",
    "monthOfCollection",
    "yearOfCollection",
    "daysToCollection",
    "timeBetweenClampingAndFreezing",
    "timeBetweenExcisionAndFreezing",
    "bcrSampleBarcode",
    "bcrSampleUuid",
    "isFfpe",
    "bcrBiospecimenCanonicalReasons",
    "portions",
    "tumorPathology",
    "methodOfSampleProcurement",
    "otherMethodOfSampleProcurement",
    "dayOfSampleProcurement",
    "monthOfSampleProcurement",
    "yearOfSampleProcurement",
    "daysToSampleProcurement",
    "pathologyReportUuid",
    "pathologyReportFileName",
    "diagnosticSlides"
})
@XmlRootElement(name = "sample")
public class Sample {

    @XmlElement(namespace = "http://tcga.nci/bcr/xml/shared/2.7")
    protected Notes notes;
    @XmlElement(name = "additional_studies", namespace = "http://tcga.nci/bcr/xml/administration/2.7")
    protected AdditionalStudies additionalStudies;
    @XmlElement(name = "alternate_identifiers", namespace = "http://tcga.nci/bcr/xml/administration/2.7")
    protected AlternateIdentifiers alternateIdentifiers;
    @XmlElement(name = "specimen_fraction_ordinal", nillable = true)
    protected SpecimenFractionOrdinal specimenFractionOrdinal;
    @XmlElement(name = "sample_type_id", required = true)
    protected SampleTypeId sampleTypeId;
    @XmlElement(name = "vial_number", required = true)
    protected VialNumber vialNumber;
    @XmlElement(name = "biospecimen_sequence", nillable = true)
    protected BiospecimenSequence biospecimenSequence;
    @XmlElement(name = "sample_type", required = true)
    protected SampleType sampleType;
    @XmlElement(name = "longest_dimension", required = true)
    protected LongestDimension longestDimension;
    @XmlElement(name = "intermediate_dimension", required = true)
    protected IntermediateDimension intermediateDimension;
    @XmlElement(name = "shortest_dimension", required = true)
    protected ShortestDimension shortestDimension;
    @XmlElement(name = "initial_weight", required = true)
    protected InitialWeight initialWeight;
    @XmlElement(name = "current_weight", required = true)
    protected CurrentWeight currentWeight;
    @XmlElement(name = "freezing_method", required = true)
    protected FreezingMethod freezingMethod;
    @XmlElement(name = "oct_embedded", required = true)
    protected OctEmbedded octEmbedded;
    @XmlElement(name = "preservation_method", nillable = true)
    protected PreservationMethod preservationMethod;
    @XmlElement(name = "tissue_type", nillable = true)
    protected TissueType tissueType;
    @XmlElement(nillable = true)
    protected Composition composition;
    @XmlElement(name = "tumor_descriptor", nillable = true)
    protected TumorDescriptor tumorDescriptor;
    @XmlElement(name = "day_of_collection")
    protected DayOfCollection dayOfCollection;
    @XmlElement(name = "month_of_collection")
    protected MonthOfCollection monthOfCollection;
    @XmlElement(name = "year_of_collection")
    protected YearOfCollection yearOfCollection;
    @XmlElement(name = "days_to_collection")
    protected DaysToCollection daysToCollection;
    @XmlElement(name = "time_between_clamping_and_freezing", required = true)
    protected TimeBetweenClampingAndFreezing timeBetweenClampingAndFreezing;
    @XmlElement(name = "time_between_excision_and_freezing", required = true)
    protected TimeBetweenExcisionAndFreezing timeBetweenExcisionAndFreezing;
    @XmlElement(name = "bcr_sample_barcode", required = true)
    protected BcrSampleBarcode bcrSampleBarcode;
    @XmlElement(name = "bcr_sample_uuid", required = true)
    protected BcrSampleUuid bcrSampleUuid;
    @XmlElement(name = "is_ffpe")
    protected IsFfpe isFfpe;
    @XmlElement(name = "bcr_biospecimen_canonical_reasons")
    protected BcrBiospecimenCanonicalReasons bcrBiospecimenCanonicalReasons;
    @XmlElement(required = true)
    protected Portions portions;
    @XmlElement(name = "tumor_pathology", required = true)
    protected TumorPathology tumorPathology;
    @XmlElement(name = "method_of_sample_procurement", required = true)
    protected MethodOfSampleProcurement methodOfSampleProcurement;
    @XmlElement(name = "other_method_of_sample_procurement", namespace = "http://tcga.nci/bcr/xml/biospecimen/shared/2.7", defaultValue = "", nillable = true)
    protected OtherMethodOfSampleProcurement otherMethodOfSampleProcurement;
    @XmlElement(name = "day_of_sample_procurement", namespace = "http://tcga.nci/bcr/xml/shared/2.7")
    protected DayOfSampleProcurement dayOfSampleProcurement;
    @XmlElement(name = "month_of_sample_procurement", namespace = "http://tcga.nci/bcr/xml/shared/2.7")
    protected MonthOfSampleProcurement monthOfSampleProcurement;
    @XmlElement(name = "year_of_sample_procurement", namespace = "http://tcga.nci/bcr/xml/shared/2.7")
    protected YearOfSampleProcurement yearOfSampleProcurement;
    @XmlElement(name = "days_to_sample_procurement", namespace = "http://tcga.nci/bcr/xml/shared/2.7")
    protected DaysToSampleProcurement daysToSampleProcurement;
    @XmlElement(name = "pathology_report_uuid", required = true, nillable = true)
    protected PathologyReportUuid pathologyReportUuid;
    @XmlElement(name = "pathology_report_file_name", nillable = true)
    protected PathologyReportFileName pathologyReportFileName;
    @XmlElement(name = "diagnostic_slides", required = true)
    protected DiagnosticSlides diagnosticSlides;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the additionalStudies property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStudies }
     *     
     */
    public AdditionalStudies getAdditionalStudies() {
        return additionalStudies;
    }

    /**
     * Sets the value of the additionalStudies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStudies }
     *     
     */
    public void setAdditionalStudies(AdditionalStudies value) {
        this.additionalStudies = value;
    }

    /**
     * Gets the value of the alternateIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateIdentifiers }
     *     
     */
    public AlternateIdentifiers getAlternateIdentifiers() {
        return alternateIdentifiers;
    }

    /**
     * Sets the value of the alternateIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateIdentifiers }
     *     
     */
    public void setAlternateIdentifiers(AlternateIdentifiers value) {
        this.alternateIdentifiers = value;
    }

    /**
     * Gets the value of the specimenFractionOrdinal property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenFractionOrdinal }
     *     
     */
    public SpecimenFractionOrdinal getSpecimenFractionOrdinal() {
        return specimenFractionOrdinal;
    }

    /**
     * Sets the value of the specimenFractionOrdinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenFractionOrdinal }
     *     
     */
    public void setSpecimenFractionOrdinal(SpecimenFractionOrdinal value) {
        this.specimenFractionOrdinal = value;
    }

    /**
     * Gets the value of the sampleTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link SampleTypeId }
     *     
     */
    public SampleTypeId getSampleTypeId() {
        return sampleTypeId;
    }

    /**
     * Sets the value of the sampleTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleTypeId }
     *     
     */
    public void setSampleTypeId(SampleTypeId value) {
        this.sampleTypeId = value;
    }

    /**
     * Gets the value of the vialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link VialNumber }
     *     
     */
    public VialNumber getVialNumber() {
        return vialNumber;
    }

    /**
     * Sets the value of the vialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link VialNumber }
     *     
     */
    public void setVialNumber(VialNumber value) {
        this.vialNumber = value;
    }

    /**
     * Gets the value of the biospecimenSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BiospecimenSequence }
     *     
     */
    public BiospecimenSequence getBiospecimenSequence() {
        return biospecimenSequence;
    }

    /**
     * Sets the value of the biospecimenSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiospecimenSequence }
     *     
     */
    public void setBiospecimenSequence(BiospecimenSequence value) {
        this.biospecimenSequence = value;
    }

    /**
     * Gets the value of the sampleType property.
     * 
     * @return
     *     possible object is
     *     {@link SampleType }
     *     
     */
    public SampleType getSampleType() {
        return sampleType;
    }

    /**
     * Sets the value of the sampleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleType }
     *     
     */
    public void setSampleType(SampleType value) {
        this.sampleType = value;
    }

    /**
     * Gets the value of the longestDimension property.
     * 
     * @return
     *     possible object is
     *     {@link LongestDimension }
     *     
     */
    public LongestDimension getLongestDimension() {
        return longestDimension;
    }

    /**
     * Sets the value of the longestDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongestDimension }
     *     
     */
    public void setLongestDimension(LongestDimension value) {
        this.longestDimension = value;
    }

    /**
     * Gets the value of the intermediateDimension property.
     * 
     * @return
     *     possible object is
     *     {@link IntermediateDimension }
     *     
     */
    public IntermediateDimension getIntermediateDimension() {
        return intermediateDimension;
    }

    /**
     * Sets the value of the intermediateDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermediateDimension }
     *     
     */
    public void setIntermediateDimension(IntermediateDimension value) {
        this.intermediateDimension = value;
    }

    /**
     * Gets the value of the shortestDimension property.
     * 
     * @return
     *     possible object is
     *     {@link ShortestDimension }
     *     
     */
    public ShortestDimension getShortestDimension() {
        return shortestDimension;
    }

    /**
     * Sets the value of the shortestDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortestDimension }
     *     
     */
    public void setShortestDimension(ShortestDimension value) {
        this.shortestDimension = value;
    }

    /**
     * Gets the value of the initialWeight property.
     * 
     * @return
     *     possible object is
     *     {@link InitialWeight }
     *     
     */
    public InitialWeight getInitialWeight() {
        return initialWeight;
    }

    /**
     * Sets the value of the initialWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialWeight }
     *     
     */
    public void setInitialWeight(InitialWeight value) {
        this.initialWeight = value;
    }

    /**
     * Gets the value of the currentWeight property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentWeight }
     *     
     */
    public CurrentWeight getCurrentWeight() {
        return currentWeight;
    }

    /**
     * Sets the value of the currentWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentWeight }
     *     
     */
    public void setCurrentWeight(CurrentWeight value) {
        this.currentWeight = value;
    }

    /**
     * Gets the value of the freezingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link FreezingMethod }
     *     
     */
    public FreezingMethod getFreezingMethod() {
        return freezingMethod;
    }

    /**
     * Sets the value of the freezingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreezingMethod }
     *     
     */
    public void setFreezingMethod(FreezingMethod value) {
        this.freezingMethod = value;
    }

    /**
     * Gets the value of the octEmbedded property.
     * 
     * @return
     *     possible object is
     *     {@link OctEmbedded }
     *     
     */
    public OctEmbedded getOctEmbedded() {
        return octEmbedded;
    }

    /**
     * Sets the value of the octEmbedded property.
     * 
     * @param value
     *     allowed object is
     *     {@link OctEmbedded }
     *     
     */
    public void setOctEmbedded(OctEmbedded value) {
        this.octEmbedded = value;
    }

    /**
     * Gets the value of the preservationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PreservationMethod }
     *     
     */
    public PreservationMethod getPreservationMethod() {
        return preservationMethod;
    }

    /**
     * Sets the value of the preservationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreservationMethod }
     *     
     */
    public void setPreservationMethod(PreservationMethod value) {
        this.preservationMethod = value;
    }

    /**
     * Gets the value of the tissueType property.
     * 
     * @return
     *     possible object is
     *     {@link TissueType }
     *     
     */
    public TissueType getTissueType() {
        return tissueType;
    }

    /**
     * Sets the value of the tissueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TissueType }
     *     
     */
    public void setTissueType(TissueType value) {
        this.tissueType = value;
    }

    /**
     * Gets the value of the composition property.
     * 
     * @return
     *     possible object is
     *     {@link Composition }
     *     
     */
    public Composition getComposition() {
        return composition;
    }

    /**
     * Sets the value of the composition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition }
     *     
     */
    public void setComposition(Composition value) {
        this.composition = value;
    }

    /**
     * Gets the value of the tumorDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link TumorDescriptor }
     *     
     */
    public TumorDescriptor getTumorDescriptor() {
        return tumorDescriptor;
    }

    /**
     * Sets the value of the tumorDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TumorDescriptor }
     *     
     */
    public void setTumorDescriptor(TumorDescriptor value) {
        this.tumorDescriptor = value;
    }

    /**
     * Gets the value of the dayOfCollection property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfCollection }
     *     
     */
    public DayOfCollection getDayOfCollection() {
        return dayOfCollection;
    }

    /**
     * Sets the value of the dayOfCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfCollection }
     *     
     */
    public void setDayOfCollection(DayOfCollection value) {
        this.dayOfCollection = value;
    }

    /**
     * Gets the value of the monthOfCollection property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfCollection }
     *     
     */
    public MonthOfCollection getMonthOfCollection() {
        return monthOfCollection;
    }

    /**
     * Sets the value of the monthOfCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfCollection }
     *     
     */
    public void setMonthOfCollection(MonthOfCollection value) {
        this.monthOfCollection = value;
    }

    /**
     * Gets the value of the yearOfCollection property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfCollection }
     *     
     */
    public YearOfCollection getYearOfCollection() {
        return yearOfCollection;
    }

    /**
     * Sets the value of the yearOfCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfCollection }
     *     
     */
    public void setYearOfCollection(YearOfCollection value) {
        this.yearOfCollection = value;
    }

    /**
     * Gets the value of the daysToCollection property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToCollection }
     *     
     */
    public DaysToCollection getDaysToCollection() {
        return daysToCollection;
    }

    /**
     * Sets the value of the daysToCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToCollection }
     *     
     */
    public void setDaysToCollection(DaysToCollection value) {
        this.daysToCollection = value;
    }

    /**
     * Gets the value of the timeBetweenClampingAndFreezing property.
     * 
     * @return
     *     possible object is
     *     {@link TimeBetweenClampingAndFreezing }
     *     
     */
    public TimeBetweenClampingAndFreezing getTimeBetweenClampingAndFreezing() {
        return timeBetweenClampingAndFreezing;
    }

    /**
     * Sets the value of the timeBetweenClampingAndFreezing property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeBetweenClampingAndFreezing }
     *     
     */
    public void setTimeBetweenClampingAndFreezing(TimeBetweenClampingAndFreezing value) {
        this.timeBetweenClampingAndFreezing = value;
    }

    /**
     * Gets the value of the timeBetweenExcisionAndFreezing property.
     * 
     * @return
     *     possible object is
     *     {@link TimeBetweenExcisionAndFreezing }
     *     
     */
    public TimeBetweenExcisionAndFreezing getTimeBetweenExcisionAndFreezing() {
        return timeBetweenExcisionAndFreezing;
    }

    /**
     * Sets the value of the timeBetweenExcisionAndFreezing property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeBetweenExcisionAndFreezing }
     *     
     */
    public void setTimeBetweenExcisionAndFreezing(TimeBetweenExcisionAndFreezing value) {
        this.timeBetweenExcisionAndFreezing = value;
    }

    /**
     * Gets the value of the bcrSampleBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link BcrSampleBarcode }
     *     
     */
    public BcrSampleBarcode getBcrSampleBarcode() {
        return bcrSampleBarcode;
    }

    /**
     * Sets the value of the bcrSampleBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrSampleBarcode }
     *     
     */
    public void setBcrSampleBarcode(BcrSampleBarcode value) {
        this.bcrSampleBarcode = value;
    }

    /**
     * Gets the value of the bcrSampleUuid property.
     * 
     * @return
     *     possible object is
     *     {@link BcrSampleUuid }
     *     
     */
    public BcrSampleUuid getBcrSampleUuid() {
        return bcrSampleUuid;
    }

    /**
     * Sets the value of the bcrSampleUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrSampleUuid }
     *     
     */
    public void setBcrSampleUuid(BcrSampleUuid value) {
        this.bcrSampleUuid = value;
    }

    /**
     * Gets the value of the isFfpe property.
     * 
     * @return
     *     possible object is
     *     {@link IsFfpe }
     *     
     */
    public IsFfpe getIsFfpe() {
        return isFfpe;
    }

    /**
     * Sets the value of the isFfpe property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsFfpe }
     *     
     */
    public void setIsFfpe(IsFfpe value) {
        this.isFfpe = value;
    }

    /**
     * Gets the value of the bcrBiospecimenCanonicalReasons property.
     * 
     * @return
     *     possible object is
     *     {@link BcrBiospecimenCanonicalReasons }
     *     
     */
    public BcrBiospecimenCanonicalReasons getBcrBiospecimenCanonicalReasons() {
        return bcrBiospecimenCanonicalReasons;
    }

    /**
     * Sets the value of the bcrBiospecimenCanonicalReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrBiospecimenCanonicalReasons }
     *     
     */
    public void setBcrBiospecimenCanonicalReasons(BcrBiospecimenCanonicalReasons value) {
        this.bcrBiospecimenCanonicalReasons = value;
    }

    /**
     * Gets the value of the portions property.
     * 
     * @return
     *     possible object is
     *     {@link Portions }
     *     
     */
    public Portions getPortions() {
        return portions;
    }

    /**
     * Sets the value of the portions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portions }
     *     
     */
    public void setPortions(Portions value) {
        this.portions = value;
    }

    /**
     * Gets the value of the tumorPathology property.
     * 
     * @return
     *     possible object is
     *     {@link TumorPathology }
     *     
     */
    public TumorPathology getTumorPathology() {
        return tumorPathology;
    }

    /**
     * Sets the value of the tumorPathology property.
     * 
     * @param value
     *     allowed object is
     *     {@link TumorPathology }
     *     
     */
    public void setTumorPathology(TumorPathology value) {
        this.tumorPathology = value;
    }

    /**
     * Gets the value of the methodOfSampleProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link MethodOfSampleProcurement }
     *     
     */
    public MethodOfSampleProcurement getMethodOfSampleProcurement() {
        return methodOfSampleProcurement;
    }

    /**
     * Sets the value of the methodOfSampleProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodOfSampleProcurement }
     *     
     */
    public void setMethodOfSampleProcurement(MethodOfSampleProcurement value) {
        this.methodOfSampleProcurement = value;
    }

    /**
     * Gets the value of the otherMethodOfSampleProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link OtherMethodOfSampleProcurement }
     *     
     */
    public OtherMethodOfSampleProcurement getOtherMethodOfSampleProcurement() {
        return otherMethodOfSampleProcurement;
    }

    /**
     * Sets the value of the otherMethodOfSampleProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherMethodOfSampleProcurement }
     *     
     */
    public void setOtherMethodOfSampleProcurement(OtherMethodOfSampleProcurement value) {
        this.otherMethodOfSampleProcurement = value;
    }

    /**
     * Gets the value of the dayOfSampleProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfSampleProcurement }
     *     
     */
    public DayOfSampleProcurement getDayOfSampleProcurement() {
        return dayOfSampleProcurement;
    }

    /**
     * Sets the value of the dayOfSampleProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfSampleProcurement }
     *     
     */
    public void setDayOfSampleProcurement(DayOfSampleProcurement value) {
        this.dayOfSampleProcurement = value;
    }

    /**
     * Gets the value of the monthOfSampleProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfSampleProcurement }
     *     
     */
    public MonthOfSampleProcurement getMonthOfSampleProcurement() {
        return monthOfSampleProcurement;
    }

    /**
     * Sets the value of the monthOfSampleProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfSampleProcurement }
     *     
     */
    public void setMonthOfSampleProcurement(MonthOfSampleProcurement value) {
        this.monthOfSampleProcurement = value;
    }

    /**
     * Gets the value of the yearOfSampleProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfSampleProcurement }
     *     
     */
    public YearOfSampleProcurement getYearOfSampleProcurement() {
        return yearOfSampleProcurement;
    }

    /**
     * Sets the value of the yearOfSampleProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfSampleProcurement }
     *     
     */
    public void setYearOfSampleProcurement(YearOfSampleProcurement value) {
        this.yearOfSampleProcurement = value;
    }

    /**
     * Gets the value of the daysToSampleProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToSampleProcurement }
     *     
     */
    public DaysToSampleProcurement getDaysToSampleProcurement() {
        return daysToSampleProcurement;
    }

    /**
     * Sets the value of the daysToSampleProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToSampleProcurement }
     *     
     */
    public void setDaysToSampleProcurement(DaysToSampleProcurement value) {
        this.daysToSampleProcurement = value;
    }

    /**
     * Gets the value of the pathologyReportUuid property.
     * 
     * @return
     *     possible object is
     *     {@link PathologyReportUuid }
     *     
     */
    public PathologyReportUuid getPathologyReportUuid() {
        return pathologyReportUuid;
    }

    /**
     * Sets the value of the pathologyReportUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathologyReportUuid }
     *     
     */
    public void setPathologyReportUuid(PathologyReportUuid value) {
        this.pathologyReportUuid = value;
    }

    /**
     * Gets the value of the pathologyReportFileName property.
     * 
     * @return
     *     possible object is
     *     {@link PathologyReportFileName }
     *     
     */
    public PathologyReportFileName getPathologyReportFileName() {
        return pathologyReportFileName;
    }

    /**
     * Sets the value of the pathologyReportFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathologyReportFileName }
     *     
     */
    public void setPathologyReportFileName(PathologyReportFileName value) {
        this.pathologyReportFileName = value;
    }

    /**
     * Gets the value of the diagnosticSlides property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticSlides }
     *     
     */
    public DiagnosticSlides getDiagnosticSlides() {
        return diagnosticSlides;
    }

    /**
     * Sets the value of the diagnosticSlides property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticSlides }
     *     
     */
    public void setDiagnosticSlides(DiagnosticSlides value) {
        this.diagnosticSlides = value;
    }

}
