//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.utility._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alt_id_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="alt_id_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Aurora Sample Identifier"/>
 *     &lt;enumeration value="ER Review Panel ID"/>
 *     &lt;enumeration value="PPTC Subject Identifier"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "alt_id_type")
@XmlEnum
public enum AltIdType {

    @XmlEnumValue("Aurora Sample Identifier")
    AURORA_SAMPLE_IDENTIFIER("Aurora Sample Identifier"),
    @XmlEnumValue("ER Review Panel ID")
    ER_REVIEW_PANEL_ID("ER Review Panel ID"),
    @XmlEnumValue("PPTC Subject Identifier")
    PPTC_SUBJECT_IDENTIFIER("PPTC Subject Identifier");
    private final String value;

    AltIdType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AltIdType fromValue(String v) {
        for (AltIdType c: AltIdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
