//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.utility._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.DaysToDrugTherapyEnd;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.DaysToDrugTherapyStart;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.RouteOfAdministration;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.StemCellTransplantationType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.TherapyType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.TherapyTypeNotes;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.AnatomicTreatmentSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.DaysToRadiationTherapyEnd;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.DaysToRadiationTherapyStart;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.Numfractions;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.PriorRadiationTypeMetastasis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.RadiationDosage;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.RadiationDosageMetastasis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.RadiationType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.Units;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AcetaminophenUseCategory;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AdditionalTreatmentCompletionSuccessOutcome;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AgeAtInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AnatomicNeoplasmSubdivision;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AnatomicNeoplasmSubdivisionOther;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AspirinUseCategory;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.BirthControlPillHistoryUsageCategory;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.BirthCountry;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.BloodRelativeWithCancer;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.CancerDiagnosisCancerTypeIcd9TextName;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Comorbidity;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.CountryOfOrigin;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.CtScanFindings;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.CytogeneticAbnormality;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToBirth;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToClinicalDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToDeath;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToFirstCompleteResponse;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToFirstPartialResponse;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToFirstResponse;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToLastFollowup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToLastKnownAlive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToMostRecentDateOfLastContact;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToPatientProgressionFree;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToPerformanceStatusAssessment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToTreatmentEnd;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToTreatmentStart;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToTumorProgression;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToTumorRecurrence;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.EasternCancerOncologyGroup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ErDiseaseExtentPriorErTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ErResponseType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ErSolidTumorResponseDocumentedType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Ethnicity;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ExtranodalRadiationField;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.FamilyMemberRelationshipType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Field;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.FollowupCaseReportFormSubmissionReason;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.FollowupTreatmentSuccess;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Height;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.HighestEducationAchieved;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.HistoryPriorSurgeryType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Icd10;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.IcdO3Histology;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.IcdO3Site;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.InformedConsentVerified;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.InitialPathologicDiagnosisMethod;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.KarnofskyPerformanceScore;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Laterality;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MarginStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MaritalStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MeasureOfResponse;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MenopauseStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MetastaticSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MetastaticSiteAtDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MetforminUseCategory;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MethodOfClinicalDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MolecularAbnormalityResults;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.OtherTobaccoProductType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.OxygenUseType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PatientDeathReason;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PatientProgressionStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PatientSex;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PerformanceStatusScaleTiming;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PersonNeoplasmCancerStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PharmRegimen;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PhysicalExerciseDaysPerWeek;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PostSurgicalProcedureAssessmentThyroidGlandCarcinomaStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PrimaryTherapyOutcomeSuccess;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PrimaryTherapyOutcomeSuccessAtFollowup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PriorSystemicTherapyType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ProgressionDeterminedByNotes;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ProtocolStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Race;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RadiationTherapyTotalDosage;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RegimenIndication;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RegimenIndicationNotes;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ResidualTumor;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.SmokingCessationDurationUnits;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.SmokingFrequency;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.SmokingTimeInDayBegins;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.SourceOfPatientDeathReason;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.StatinUseCategory;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.StemCellTransplantation;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TargetedNodalRegion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TreatmentType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TumorResidualDisease;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TumorTissueSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.ViralHepatitisSerology;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.VitalStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Weight;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.ErythrocyteSedimentationRateResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.HemoglobinResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.NumberOfLymphnodesPositive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.PlateletQualitativeResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.SerumCalciumResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.WhiteCellCountResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToAdditionalSurgeryLocoregionalProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToAdditionalSurgeryMetastaticProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToNewTumorEventAdditionalSurgeryProcedure;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToNewTumorEventAfterInitialTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.DaysToNewTumorEventTransplant;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.NewEventTreatmentType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.NewNeoplasmConfirmedDiagnosisMethodName;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.NewNeoplasmEventOccurrenceAnatomicSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.NewNeoplasmEventType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.ProgressionDeterminedBy;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.ResidualDiseasePostNewTumorEventMarginStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.BLymphocyteGenotypingMethod;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.BoneMarrowSampleHistology;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.CdcHivRiskGroup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DaysToCancerDebulkingSurgery;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DaysToChemotherapyEnd;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DaysToChemotherapyStart;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DaysToHivDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DaysToStemCellTransplantation;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.EbvStatusMalignantCellsMethod;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.EpsteinBarrViralStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.ExtranodalInvolvementSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.FollicularComponentPercent;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.HbvTest;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.HcvTest;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.HistoryImmunologicalDisease;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.HistoryImmunosuppresiveRx;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.HistoryRelevantInfectiousDx;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.HpvTest;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.IghGenotypeResults;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.IgkGenotypeResults;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.KshvHhv8Test;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.LymphNodeInvolvementSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.MaximumTumorBulkAnatomicSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.Mib1PositivePercentageRange;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.PosLymphNodeLocation;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.PriorAidsConditions;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.ClinicalM;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.ClinicalN;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.ClinicalStage;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.ClinicalT;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.DaysToPsa;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.IgcccgStage;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.MasaokaStage;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.PathologicM;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.PathologicN;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.PathologicStage;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.PathologicT;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.PsaValue;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.SerumMarkers;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.SystemVersion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.ConsentOrDeathStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.DaysToConsent;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.DaysToSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.EberIshResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.FollicularPercent;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.Gender;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.GeneticAbnormalityMethod;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.GeneticAbnormalityResults;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.GeneticAbnormalityTested;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.HistologicalType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.HistoryOfNeoadjuvantTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.HivStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.ImmunophenotypicAnalysisMethod;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.ImmunophenotypicAnalysisResults;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.ImmunophenotypicAnalysisTested;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.MethodOfSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.NeoplasmHistologicGrade;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.OtherDx;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.OtherDxSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.OtherMethodOfSampleProcurement;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.RnaIntegrity;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.TobaccoSmokingHistory;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.TumorMorphologyPercentage;


/**
 * <p>Java class for clinical_res_attributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clinical_res_attributes">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attGroup ref="{http://tcga.nci/bcr/xml/utility/2.7}clinical_res_attribute_group"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clinical_res_attributes", propOrder = {
    "value"
})
@XmlSeeAlso({
    HistologicalType.class,
    IcdO3Site.class,
    IcdO3Histology.class,
    Icd10 .class,
    Ethnicity.class,
    PersonNeoplasmCancerStatus.class,
    Laterality.class,
    org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.LactateDehydrogenaseResult.class,
    SerumCalciumResult.class,
    HemoglobinResult.class,
    PlateletQualitativeResult.class,
    WhiteCellCountResult.class,
    ErythrocyteSedimentationRateResult.class,
    NumberOfLymphnodesPositive.class,
    NeoplasmHistologicGrade.class,
    TobaccoSmokingHistory.class,
    PrimaryTherapyOutcomeSuccess.class,
    MeasureOfResponse.class,
    RadiationDosageMetastasis.class,
    RadiationDosage.class,
    Numfractions.class,
    FollowupTreatmentSuccess.class,
    FollowupCaseReportFormSubmissionReason.class,
    HivStatus.class,
    OtherDxSite.class,
    TumorMorphologyPercentage.class,
    FollicularPercent.class,
    OtherMethodOfSampleProcurement.class,
    AdditionalTreatmentCompletionSuccessOutcome.class,
    CytogeneticAbnormality.class,
    PriorSystemicTherapyType.class,
    AnatomicNeoplasmSubdivision.class,
    PrimaryTherapyOutcomeSuccessAtFollowup.class,
    Height.class,
    InitialPathologicDiagnosisMethod.class,
    MetastaticSite.class,
    ErSolidTumorResponseDocumentedType.class,
    SourceOfPatientDeathReason.class,
    OxygenUseType.class,
    ViralHepatitisSerology.class,
    ErDiseaseExtentPriorErTreatment.class,
    BirthCountry.class,
    FamilyMemberRelationshipType.class,
    TumorResidualDisease.class,
    Weight.class,
    AcetaminophenUseCategory.class,
    SmokingCessationDurationUnits.class,
    ResidualTumor.class,
    HistoryPriorSurgeryType.class,
    HighestEducationAchieved.class,
    AspirinUseCategory.class,
    MolecularAbnormalityResults.class,
    BirthControlPillHistoryUsageCategory.class,
    OtherTobaccoProductType.class,
    SmokingFrequency.class,
    MarginStatus.class,
    PatientProgressionStatus.class,
    CancerDiagnosisCancerTypeIcd9TextName.class,
    AnatomicNeoplasmSubdivisionOther.class,
    RadiationTherapyTotalDosage.class,
    MetforminUseCategory.class,
    MethodOfClinicalDiagnosis.class,
    Comorbidity.class,
    PostSurgicalProcedureAssessmentThyroidGlandCarcinomaStatus.class,
    SmokingTimeInDayBegins.class,
    PhysicalExerciseDaysPerWeek.class,
    MenopauseStatus.class,
    MetastaticSiteAtDiagnosis.class,
    ErResponseType.class,
    StatinUseCategory.class,
    MaritalStatus.class,
    BloodRelativeWithCancer.class,
    BoneMarrowSampleHistology.class,
    PosLymphNodeLocation.class,
    NewNeoplasmEventOccurrenceAnatomicSite.class,
    ResidualDiseasePostNewTumorEventMarginStatus.class,
    NewEventTreatmentType.class,
    NewNeoplasmEventType.class,
    DaysToNewTumorEventTransplant.class,
    NewNeoplasmConfirmedDiagnosisMethodName.class,
    org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.TreatmentOutcome.class,
    org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.LactateDehydrogenaseResult.class,
    ProgressionDeterminedBy.class,
    DaysToNewTumorEventAdditionalSurgeryProcedure.class,
    DaysToChemotherapyEnd.class,
    KshvHhv8Test.class,
    IghGenotypeResults.class,
    EpsteinBarrViralStatus.class,
    CdcHivRiskGroup.class,
    HbvTest.class,
    HistoryRelevantInfectiousDx.class,
    HistoryImmunosuppresiveRx.class,
    BLymphocyteGenotypingMethod.class,
    Mib1PositivePercentageRange.class,
    ExtranodalInvolvementSite.class,
    HpvTest.class,
    LymphNodeInvolvementSite.class,
    EbvStatusMalignantCellsMethod.class,
    DaysToHivDiagnosis.class,
    HcvTest.class,
    DaysToCancerDebulkingSurgery.class,
    HistoryImmunologicalDisease.class,
    DaysToChemotherapyStart.class,
    FollicularComponentPercent.class,
    PriorAidsConditions.class,
    IgkGenotypeResults.class,
    MaximumTumorBulkAnatomicSite.class,
    DaysToMostRecentDateOfLastContact.class,
    ProtocolStatus.class,
    CtScanFindings.class,
    TreatmentType.class,
    DaysToTreatmentEnd.class,
    org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TreatmentOutcome.class,
    PatientSex.class,
    Field.class,
    TargetedNodalRegion.class,
    DaysToClinicalDiagnosis.class,
    PatientDeathReason.class,
    DaysToTumorRecurrence.class,
    StemCellTransplantation.class,
    DaysToFirstCompleteResponse.class,
    DaysToFirstPartialResponse.class,
    DaysToPerformanceStatusAssessment.class,
    ProgressionDeterminedByNotes.class,
    DaysToPatientProgressionFree.class,
    DaysToTumorProgression.class,
    ExtranodalRadiationField.class,
    CountryOfOrigin.class,
    DaysToFirstResponse.class,
    DaysToTreatmentStart.class,
    ImmunophenotypicAnalysisMethod.class,
    EberIshResult.class,
    GeneticAbnormalityTested.class,
    MethodOfSampleProcurement.class,
    RnaIntegrity.class,
    GeneticAbnormalityResults.class,
    ImmunophenotypicAnalysisTested.class,
    DaysToSampleProcurement.class,
    DaysToConsent.class,
    GeneticAbnormalityMethod.class,
    ImmunophenotypicAnalysisResults.class,
    ConsentOrDeathStatus.class,
    AnatomicTreatmentSite.class,
    Units.class,
    RadiationType.class,
    PriorRadiationTypeMetastasis.class,
    DaysToRadiationTherapyEnd.class,
    DaysToRadiationTherapyStart.class,
    RouteOfAdministration.class,
    RegimenIndicationNotes.class,
    RegimenIndication.class,
    PharmRegimen.class,
    DaysToStemCellTransplantation.class,
    StemCellTransplantationType.class,
    TherapyTypeNotes.class,
    TherapyType.class,
    DaysToDrugTherapyEnd.class,
    DaysToDrugTherapyStart.class,
    DaysToAdditionalSurgeryMetastaticProcedure.class,
    DaysToAdditionalSurgeryLocoregionalProcedure.class,
    DaysToNewTumorEventAfterInitialTreatment.class,
    EasternCancerOncologyGroup.class,
    KarnofskyPerformanceScore.class,
    MasaokaStage.class,
    IgcccgStage.class,
    SerumMarkers.class,
    DaysToPsa.class,
    PsaValue.class,
    PathologicM.class,
    PathologicN.class,
    PathologicT.class,
    ClinicalM.class,
    ClinicalN.class,
    ClinicalT.class,
    PathologicStage.class,
    ClinicalStage.class,
    SystemVersion.class,
    DaysToFormCompletion.class,
    AgeAtInitialPathologicDiagnosis.class,
    DaysToInitialPathologicDiagnosis.class,
    PerformanceStatusScaleTiming.class,
    InformedConsentVerified.class,
    HistoryOfNeoadjuvantTreatment.class,
    Race.class,
    DaysToLastFollowup.class,
    DaysToDeath.class,
    DaysToLastKnownAlive.class,
    DaysToBirth.class,
    VitalStatus.class,
    Gender.class,
    OtherDx.class,
    TumorTissueSite.class
})
public class ClinicalResAttributes {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "tier")
    protected String tier;
    @XmlAttribute(name = "floored")
    protected Boolean floored;
    @XmlAttribute(name = "preferred_name")
    protected String preferredName;
    @XmlAttribute(name = "display_order")
    protected BigInteger displayOrder;
    @XmlAttribute(name = "restricted")
    protected Boolean restricted;
    @XmlAttribute(name = "source_system_identifier")
    protected BigInteger sourceSystemIdentifier;
    @XmlAttribute(name = "cde")
    protected String cde;
    @XmlAttribute(name = "cde_ver")
    protected String cdeVer;
    @XmlAttribute(name = "procurement_status", required = true)
    protected String procurementStatus;
    @XmlAttribute(name = "owner", required = true)
    protected String owner;
    @XmlAttribute(name = "precision")
    protected String precision;
    @XmlAttribute(name = "xsd_ver")
    protected String xsdVer;
    @XmlAttribute(name = "units")
    protected String units;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the tier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTier() {
        if (tier == null) {
            return "";
        } else {
            return tier;
        }
    }

    /**
     * Sets the value of the tier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTier(String value) {
        this.tier = value;
    }

    /**
     * Gets the value of the floored property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFloored() {
        if (floored == null) {
            return false;
        } else {
            return floored;
        }
    }

    /**
     * Sets the value of the floored property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFloored(Boolean value) {
        this.floored = value;
    }

    /**
     * Gets the value of the preferredName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredName() {
        if (preferredName == null) {
            return "";
        } else {
            return preferredName;
        }
    }

    /**
     * Sets the value of the preferredName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredName(String value) {
        this.preferredName = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayOrder() {
        if (displayOrder == null) {
            return new BigInteger("9999");
        } else {
            return displayOrder;
        }
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayOrder(BigInteger value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the restricted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRestricted() {
        if (restricted == null) {
            return false;
        } else {
            return restricted;
        }
    }

    /**
     * Sets the value of the restricted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRestricted(Boolean value) {
        this.restricted = value;
    }

    /**
     * Gets the value of the sourceSystemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSourceSystemIdentifier() {
        return sourceSystemIdentifier;
    }

    /**
     * Sets the value of the sourceSystemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSourceSystemIdentifier(BigInteger value) {
        this.sourceSystemIdentifier = value;
    }

    /**
     * Gets the value of the cde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCde() {
        if (cde == null) {
            return "";
        } else {
            return cde;
        }
    }

    /**
     * Sets the value of the cde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCde(String value) {
        this.cde = value;
    }

    /**
     * Gets the value of the cdeVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdeVer() {
        if (cdeVer == null) {
            return "";
        } else {
            return cdeVer;
        }
    }

    /**
     * Sets the value of the cdeVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdeVer(String value) {
        this.cdeVer = value;
    }

    /**
     * Gets the value of the procurementStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcurementStatus() {
        return procurementStatus;
    }

    /**
     * Sets the value of the procurementStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcurementStatus(String value) {
        this.procurementStatus = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecision(String value) {
        this.precision = value;
    }

    /**
     * Gets the value of the xsdVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdVer() {
        if (xsdVer == null) {
            return "";
        } else {
            return xsdVer;
        }
    }

    /**
     * Sets the value of the xsdVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdVer(String value) {
        this.xsdVer = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        if (units == null) {
            return "";
        } else {
            return units;
        }
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

}
