//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tcga.nci/bcr/xml/utility/2.7")
package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.utility._2;
