//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HemoglobinResult_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "hemoglobin_result");
    private final static QName _PlateletQualitativeResult_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "platelet_qualitative_result");
    private final static QName _ErythrocyteSedimentationRateResult_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "erythrocyte_sedimentation_rate_result");
    private final static QName _NumberOfLymphnodesPositive_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "number_of_lymphnodes_positive");
    private final static QName _WhiteCellCountResult_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "white_cell_count_result");
    private final static QName _SerumCalciumResult_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "serum_calcium_result");
    private final static QName _LactateDehydrogenaseResult_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", "lactate_dehydrogenase_result");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SerumCalciumResult }
     * 
     */
    public SerumCalciumResult createSerumCalciumResult() {
        return new SerumCalciumResult();
    }

    /**
     * Create an instance of {@link HemoglobinResult }
     * 
     */
    public HemoglobinResult createHemoglobinResult() {
        return new HemoglobinResult();
    }

    /**
     * Create an instance of {@link PlateletQualitativeResult }
     * 
     */
    public PlateletQualitativeResult createPlateletQualitativeResult() {
        return new PlateletQualitativeResult();
    }

    /**
     * Create an instance of {@link WhiteCellCountResult }
     * 
     */
    public WhiteCellCountResult createWhiteCellCountResult() {
        return new WhiteCellCountResult();
    }

    /**
     * Create an instance of {@link ErythrocyteSedimentationRateResult }
     * 
     */
    public ErythrocyteSedimentationRateResult createErythrocyteSedimentationRateResult() {
        return new ErythrocyteSedimentationRateResult();
    }

    /**
     * Create an instance of {@link NumberOfLymphnodesPositive }
     * 
     */
    public NumberOfLymphnodesPositive createNumberOfLymphnodesPositive() {
        return new NumberOfLymphnodesPositive();
    }

    /**
     * Create an instance of {@link LactateDehydrogenaseResult }
     * 
     */
    public LactateDehydrogenaseResult createLactateDehydrogenaseResult() {
        return new LactateDehydrogenaseResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HemoglobinResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "hemoglobin_result")
    public JAXBElement<HemoglobinResult> createHemoglobinResult(HemoglobinResult value) {
        return new JAXBElement<HemoglobinResult>(_HemoglobinResult_QNAME, HemoglobinResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlateletQualitativeResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "platelet_qualitative_result")
    public JAXBElement<PlateletQualitativeResult> createPlateletQualitativeResult(PlateletQualitativeResult value) {
        return new JAXBElement<PlateletQualitativeResult>(_PlateletQualitativeResult_QNAME, PlateletQualitativeResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErythrocyteSedimentationRateResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "erythrocyte_sedimentation_rate_result")
    public JAXBElement<ErythrocyteSedimentationRateResult> createErythrocyteSedimentationRateResult(ErythrocyteSedimentationRateResult value) {
        return new JAXBElement<ErythrocyteSedimentationRateResult>(_ErythrocyteSedimentationRateResult_QNAME, ErythrocyteSedimentationRateResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberOfLymphnodesPositive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "number_of_lymphnodes_positive")
    public JAXBElement<NumberOfLymphnodesPositive> createNumberOfLymphnodesPositive(NumberOfLymphnodesPositive value) {
        return new JAXBElement<NumberOfLymphnodesPositive>(_NumberOfLymphnodesPositive_QNAME, NumberOfLymphnodesPositive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhiteCellCountResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "white_cell_count_result")
    public JAXBElement<WhiteCellCountResult> createWhiteCellCountResult(WhiteCellCountResult value) {
        return new JAXBElement<WhiteCellCountResult>(_WhiteCellCountResult_QNAME, WhiteCellCountResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SerumCalciumResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "serum_calcium_result")
    public JAXBElement<SerumCalciumResult> createSerumCalciumResult(SerumCalciumResult value) {
        return new JAXBElement<SerumCalciumResult>(_SerumCalciumResult_QNAME, SerumCalciumResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LactateDehydrogenaseResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", name = "lactate_dehydrogenase_result")
    public JAXBElement<LactateDehydrogenaseResult> createLactateDehydrogenaseResult(LactateDehydrogenaseResult value) {
        return new JAXBElement<LactateDehydrogenaseResult>(_LactateDehydrogenaseResult_QNAME, LactateDehydrogenaseResult.class, null, value);
    }

}
