//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.utility._2.ClinicalResAttributes;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://tcga.nci/bcr/xml/utility/2.7>clinical_res_attributes">
 *       &lt;attribute name="cde" type="{http://www.w3.org/2001/XMLSchema}string" default="3234684" />
 *       &lt;attribute name="xsd_ver" type="{http://www.w3.org/2001/XMLSchema}string" default="2.6" />
 *       &lt;attribute name="tier" type="{http://www.w3.org/2001/XMLSchema}string" default="2" />
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "genetic_abnormality_method")
public class GeneticAbnormalityMethod
    extends ClinicalResAttributes
{


}
