//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImageFileName_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "image_file_name");
    private final static QName _MaximumTumorDimension_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "maximum_tumor_dimension");
    private final static QName _HivStatus_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "hiv_status");
    private final static QName _TumorMorphologyPercentage_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "tumor_morphology_percentage");
    private final static QName _GermlineTestingPerformed_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "germline_testing_performed");
    private final static QName _TobaccoSmokingHistory_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "tobacco_smoking_history");
    private final static QName _Country_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "country");
    private final static QName _TumorNucleiPercent_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "tumor_nuclei_percent");
    private final static QName _HistologicalType_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "histological_type");
    private final static QName _Comment_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "comment");
    private final static QName _NoteText_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "note_text");
    private final static QName _OtherMethodOfSampleProcurement_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "other_method_of_sample_procurement");
    private final static QName _HistologicalTypeOther_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "histological_type_other");
    private final static QName _NeoplasmHistologicGrade_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "neoplasm_histologic_grade");
    private final static QName _TumorNecrosisPercent_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "tumor_necrosis_percent");
    private final static QName _OtherDxSite_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "other_dx_site");
    private final static QName _MetastaticDiagnosis_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "metastatic_diagnosis");
    private final static QName _DrugTxIndicator_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "drug_tx_indicator");
    private final static QName _SurgeryIndicator_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "surgery_indicator");
    private final static QName _FollicularPercent_QNAME = new QName("http://tcga.nci/bcr/xml/shared/2.7", "follicular_percent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HistologicalType }
     * 
     */
    public HistologicalType createHistologicalType() {
        return new HistologicalType();
    }

    /**
     * Create an instance of {@link OtherDx }
     * 
     */
    public OtherDx createOtherDx() {
        return new OtherDx();
    }

    /**
     * Create an instance of {@link Gender }
     * 
     */
    public Gender createGender() {
        return new Gender();
    }

    /**
     * Create an instance of {@link BcrPatientBarcode }
     * 
     */
    public BcrPatientBarcode createBcrPatientBarcode() {
        return new BcrPatientBarcode();
    }

    /**
     * Create an instance of {@link TissueSourceSite }
     * 
     */
    public TissueSourceSite createTissueSourceSite() {
        return new TissueSourceSite();
    }

    /**
     * Create an instance of {@link PatientId }
     * 
     */
    public PatientId createPatientId() {
        return new PatientId();
    }

    /**
     * Create an instance of {@link BcrPatientUuid }
     * 
     */
    public BcrPatientUuid createBcrPatientUuid() {
        return new BcrPatientUuid();
    }

    /**
     * Create an instance of {@link HistoryOfNeoadjuvantTreatment }
     * 
     */
    public HistoryOfNeoadjuvantTreatment createHistoryOfNeoadjuvantTreatment() {
        return new HistoryOfNeoadjuvantTreatment();
    }

    /**
     * Create an instance of {@link NeoplasmHistologicGrade }
     * 
     */
    public NeoplasmHistologicGrade createNeoplasmHistologicGrade() {
        return new NeoplasmHistologicGrade();
    }

    /**
     * Create an instance of {@link TobaccoSmokingHistory }
     * 
     */
    public TobaccoSmokingHistory createTobaccoSmokingHistory() {
        return new TobaccoSmokingHistory();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link NoteText }
     * 
     */
    public NoteText createNoteText() {
        return new NoteText();
    }

    /**
     * Create an instance of {@link MonthOfConsent }
     * 
     */
    public MonthOfConsent createMonthOfConsent() {
        return new MonthOfConsent();
    }

    /**
     * Create an instance of {@link GeneticAbnormalityResultsOther }
     * 
     */
    public GeneticAbnormalityResultsOther createGeneticAbnormalityResultsOther() {
        return new GeneticAbnormalityResultsOther();
    }

    /**
     * Create an instance of {@link MaximumTumorDimension }
     * 
     */
    public MaximumTumorDimension createMaximumTumorDimension() {
        return new MaximumTumorDimension();
    }

    /**
     * Create an instance of {@link GeneticAbnormalityTestedOther }
     * 
     */
    public GeneticAbnormalityTestedOther createGeneticAbnormalityTestedOther() {
        return new GeneticAbnormalityTestedOther();
    }

    /**
     * Create an instance of {@link TumorNecrosisPercent }
     * 
     */
    public TumorNecrosisPercent createTumorNecrosisPercent() {
        return new TumorNecrosisPercent();
    }

    /**
     * Create an instance of {@link ConsentOrDeathStatus }
     * 
     */
    public ConsentOrDeathStatus createConsentOrDeathStatus() {
        return new ConsentOrDeathStatus();
    }

    /**
     * Create an instance of {@link ImageFileName }
     * 
     */
    public ImageFileName createImageFileName() {
        return new ImageFileName();
    }

    /**
     * Create an instance of {@link ImmunophenotypicAnalysisResults }
     * 
     */
    public ImmunophenotypicAnalysisResults createImmunophenotypicAnalysisResults() {
        return new ImmunophenotypicAnalysisResults();
    }

    /**
     * Create an instance of {@link GeneticAbnormalityMethod }
     * 
     */
    public GeneticAbnormalityMethod createGeneticAbnormalityMethod() {
        return new GeneticAbnormalityMethod();
    }

    /**
     * Create an instance of {@link DrugTxIndicator }
     * 
     */
    public DrugTxIndicator createDrugTxIndicator() {
        return new DrugTxIndicator();
    }

    /**
     * Create an instance of {@link DaysToConsent }
     * 
     */
    public DaysToConsent createDaysToConsent() {
        return new DaysToConsent();
    }

    /**
     * Create an instance of {@link AdenocarcinomaInvasion }
     * 
     */
    public AdenocarcinomaInvasion createAdenocarcinomaInvasion() {
        return new AdenocarcinomaInvasion();
    }

    /**
     * Create an instance of {@link HivStatus }
     * 
     */
    public HivStatus createHivStatus() {
        return new HivStatus();
    }

    /**
     * Create an instance of {@link TumorNucleiPercent }
     * 
     */
    public TumorNucleiPercent createTumorNucleiPercent() {
        return new TumorNucleiPercent();
    }

    /**
     * Create an instance of {@link DayOfConsent }
     * 
     */
    public DayOfConsent createDayOfConsent() {
        return new DayOfConsent();
    }

    /**
     * Create an instance of {@link DaysToSampleProcurement }
     * 
     */
    public DaysToSampleProcurement createDaysToSampleProcurement() {
        return new DaysToSampleProcurement();
    }

    /**
     * Create an instance of {@link ImmunophenotypicAnalysisTested }
     * 
     */
    public ImmunophenotypicAnalysisTested createImmunophenotypicAnalysisTested() {
        return new ImmunophenotypicAnalysisTested();
    }

    /**
     * Create an instance of {@link OtherDxSite }
     * 
     */
    public OtherDxSite createOtherDxSite() {
        return new OtherDxSite();
    }

    /**
     * Create an instance of {@link MonthOfSampleProcurement }
     * 
     */
    public MonthOfSampleProcurement createMonthOfSampleProcurement() {
        return new MonthOfSampleProcurement();
    }

    /**
     * Create an instance of {@link MetastaticDiagnosis }
     * 
     */
    public MetastaticDiagnosis createMetastaticDiagnosis() {
        return new MetastaticDiagnosis();
    }

    /**
     * Create an instance of {@link GeneticAbnormalityResults }
     * 
     */
    public GeneticAbnormalityResults createGeneticAbnormalityResults() {
        return new GeneticAbnormalityResults();
    }

    /**
     * Create an instance of {@link YearOfConsent }
     * 
     */
    public YearOfConsent createYearOfConsent() {
        return new YearOfConsent();
    }

    /**
     * Create an instance of {@link RnaIntegrity }
     * 
     */
    public RnaIntegrity createRnaIntegrity() {
        return new RnaIntegrity();
    }

    /**
     * Create an instance of {@link BcrSlideUuid }
     * 
     */
    public BcrSlideUuid createBcrSlideUuid() {
        return new BcrSlideUuid();
    }

    /**
     * Create an instance of {@link HistologicalPercentage }
     * 
     */
    public HistologicalPercentage createHistologicalPercentage() {
        return new HistologicalPercentage();
    }

    /**
     * Create an instance of {@link YearOfSampleProcurement }
     * 
     */
    public YearOfSampleProcurement createYearOfSampleProcurement() {
        return new YearOfSampleProcurement();
    }

    /**
     * Create an instance of {@link TumorMorphologyPercentage }
     * 
     */
    public TumorMorphologyPercentage createTumorMorphologyPercentage() {
        return new TumorMorphologyPercentage();
    }

    /**
     * Create an instance of {@link MethodOfSampleProcurement }
     * 
     */
    public MethodOfSampleProcurement createMethodOfSampleProcurement() {
        return new MethodOfSampleProcurement();
    }

    /**
     * Create an instance of {@link GeneticAbnormalityTested }
     * 
     */
    public GeneticAbnormalityTested createGeneticAbnormalityTested() {
        return new GeneticAbnormalityTested();
    }

    /**
     * Create an instance of {@link PleurodesisPerformed }
     * 
     */
    public PleurodesisPerformed createPleurodesisPerformed() {
        return new PleurodesisPerformed();
    }

    /**
     * Create an instance of {@link HistologicalTypeOther }
     * 
     */
    public HistologicalTypeOther createHistologicalTypeOther() {
        return new HistologicalTypeOther();
    }

    /**
     * Create an instance of {@link DayOfSampleProcurement }
     * 
     */
    public DayOfSampleProcurement createDayOfSampleProcurement() {
        return new DayOfSampleProcurement();
    }

    /**
     * Create an instance of {@link SurgeryIndicator }
     * 
     */
    public SurgeryIndicator createSurgeryIndicator() {
        return new SurgeryIndicator();
    }

    /**
     * Create an instance of {@link GeneticAbnormalityMethodOther }
     * 
     */
    public GeneticAbnormalityMethodOther createGeneticAbnormalityMethodOther() {
        return new GeneticAbnormalityMethodOther();
    }

    /**
     * Create an instance of {@link FollicularPercent }
     * 
     */
    public FollicularPercent createFollicularPercent() {
        return new FollicularPercent();
    }

    /**
     * Create an instance of {@link GermlineTestingPerformed }
     * 
     */
    public GermlineTestingPerformed createGermlineTestingPerformed() {
        return new GermlineTestingPerformed();
    }

    /**
     * Create an instance of {@link EberIshResult }
     * 
     */
    public EberIshResult createEberIshResult() {
        return new EberIshResult();
    }

    /**
     * Create an instance of {@link BcrSlideBarcode }
     * 
     */
    public BcrSlideBarcode createBcrSlideBarcode() {
        return new BcrSlideBarcode();
    }

    /**
     * Create an instance of {@link ImmunophenotypicAnalysisTestedOther }
     * 
     */
    public ImmunophenotypicAnalysisTestedOther createImmunophenotypicAnalysisTestedOther() {
        return new ImmunophenotypicAnalysisTestedOther();
    }

    /**
     * Create an instance of {@link OtherMethodOfSampleProcurement }
     * 
     */
    public OtherMethodOfSampleProcurement createOtherMethodOfSampleProcurement() {
        return new OtherMethodOfSampleProcurement();
    }

    /**
     * Create an instance of {@link ImmunophenotypicAnalysisMethod }
     * 
     */
    public ImmunophenotypicAnalysisMethod createImmunophenotypicAnalysisMethod() {
        return new ImmunophenotypicAnalysisMethod();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageFileName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "image_file_name")
    public JAXBElement<ImageFileName> createImageFileName(ImageFileName value) {
        return new JAXBElement<ImageFileName>(_ImageFileName_QNAME, ImageFileName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaximumTumorDimension }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "maximum_tumor_dimension")
    public JAXBElement<MaximumTumorDimension> createMaximumTumorDimension(MaximumTumorDimension value) {
        return new JAXBElement<MaximumTumorDimension>(_MaximumTumorDimension_QNAME, MaximumTumorDimension.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HivStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "hiv_status")
    public JAXBElement<HivStatus> createHivStatus(HivStatus value) {
        return new JAXBElement<HivStatus>(_HivStatus_QNAME, HivStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TumorMorphologyPercentage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "tumor_morphology_percentage")
    public JAXBElement<TumorMorphologyPercentage> createTumorMorphologyPercentage(TumorMorphologyPercentage value) {
        return new JAXBElement<TumorMorphologyPercentage>(_TumorMorphologyPercentage_QNAME, TumorMorphologyPercentage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GermlineTestingPerformed }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "germline_testing_performed")
    public JAXBElement<GermlineTestingPerformed> createGermlineTestingPerformed(GermlineTestingPerformed value) {
        return new JAXBElement<GermlineTestingPerformed>(_GermlineTestingPerformed_QNAME, GermlineTestingPerformed.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TobaccoSmokingHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "tobacco_smoking_history")
    public JAXBElement<TobaccoSmokingHistory> createTobaccoSmokingHistory(TobaccoSmokingHistory value) {
        return new JAXBElement<TobaccoSmokingHistory>(_TobaccoSmokingHistory_QNAME, TobaccoSmokingHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Country }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "country")
    public JAXBElement<Country> createCountry(Country value) {
        return new JAXBElement<Country>(_Country_QNAME, Country.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TumorNucleiPercent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "tumor_nuclei_percent", defaultValue = "")
    public JAXBElement<TumorNucleiPercent> createTumorNucleiPercent(TumorNucleiPercent value) {
        return new JAXBElement<TumorNucleiPercent>(_TumorNucleiPercent_QNAME, TumorNucleiPercent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistologicalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "histological_type")
    public JAXBElement<HistologicalType> createHistologicalType(HistologicalType value) {
        return new JAXBElement<HistologicalType>(_HistologicalType_QNAME, HistologicalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Comment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "comment")
    public JAXBElement<Comment> createComment(Comment value) {
        return new JAXBElement<Comment>(_Comment_QNAME, Comment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "note_text")
    public JAXBElement<NoteText> createNoteText(NoteText value) {
        return new JAXBElement<NoteText>(_NoteText_QNAME, NoteText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherMethodOfSampleProcurement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "other_method_of_sample_procurement", defaultValue = "")
    public JAXBElement<OtherMethodOfSampleProcurement> createOtherMethodOfSampleProcurement(OtherMethodOfSampleProcurement value) {
        return new JAXBElement<OtherMethodOfSampleProcurement>(_OtherMethodOfSampleProcurement_QNAME, OtherMethodOfSampleProcurement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistologicalTypeOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "histological_type_other")
    public JAXBElement<HistologicalTypeOther> createHistologicalTypeOther(HistologicalTypeOther value) {
        return new JAXBElement<HistologicalTypeOther>(_HistologicalTypeOther_QNAME, HistologicalTypeOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NeoplasmHistologicGrade }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "neoplasm_histologic_grade")
    public JAXBElement<NeoplasmHistologicGrade> createNeoplasmHistologicGrade(NeoplasmHistologicGrade value) {
        return new JAXBElement<NeoplasmHistologicGrade>(_NeoplasmHistologicGrade_QNAME, NeoplasmHistologicGrade.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TumorNecrosisPercent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "tumor_necrosis_percent")
    public JAXBElement<TumorNecrosisPercent> createTumorNecrosisPercent(TumorNecrosisPercent value) {
        return new JAXBElement<TumorNecrosisPercent>(_TumorNecrosisPercent_QNAME, TumorNecrosisPercent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherDxSite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "other_dx_site", defaultValue = "")
    public JAXBElement<OtherDxSite> createOtherDxSite(OtherDxSite value) {
        return new JAXBElement<OtherDxSite>(_OtherDxSite_QNAME, OtherDxSite.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetastaticDiagnosis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "metastatic_diagnosis")
    public JAXBElement<MetastaticDiagnosis> createMetastaticDiagnosis(MetastaticDiagnosis value) {
        return new JAXBElement<MetastaticDiagnosis>(_MetastaticDiagnosis_QNAME, MetastaticDiagnosis.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugTxIndicator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "drug_tx_indicator")
    public JAXBElement<DrugTxIndicator> createDrugTxIndicator(DrugTxIndicator value) {
        return new JAXBElement<DrugTxIndicator>(_DrugTxIndicator_QNAME, DrugTxIndicator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurgeryIndicator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "surgery_indicator")
    public JAXBElement<SurgeryIndicator> createSurgeryIndicator(SurgeryIndicator value) {
        return new JAXBElement<SurgeryIndicator>(_SurgeryIndicator_QNAME, SurgeryIndicator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FollicularPercent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/shared/2.7", name = "follicular_percent")
    public JAXBElement<FollicularPercent> createFollicularPercent(FollicularPercent value) {
        return new JAXBElement<FollicularPercent>(_FollicularPercent_QNAME, FollicularPercent.class, null, value);
    }

}
