//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *       &lt;attribute name="cde" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xsd_ver" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "days_to_dcc_upload")
public class DaysToDccUpload {

    @XmlValue
    protected BigInteger value;
    @XmlAttribute(name = "cde")
    protected String cde;
    @XmlAttribute(name = "precision")
    protected String precision;
    @XmlAttribute(name = "xsd_ver")
    protected String xsdVer;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValue(BigInteger value) {
        this.value = value;
    }

    /**
     * Gets the value of the cde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCde() {
        if (cde == null) {
            return "";
        } else {
            return cde;
        }
    }

    /**
     * Sets the value of the cde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCde(String value) {
        this.cde = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecision(String value) {
        this.precision = value;
    }

    /**
     * Gets the value of the xsdVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdVer() {
        if (xsdVer == null) {
            return "";
        } else {
            return xsdVer;
        }
    }

    /**
     * Sets the value of the xsdVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdVer(String value) {
        this.xsdVer = value;
    }

}
