//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="withdrawn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="date_of_withdraw" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="reason_for_withdraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "withdrawn",
    "dateOfWithdraw",
    "reasonForWithdraw"
})
@XmlRootElement(name = "patient_withdrawal")
public class PatientWithdrawal {

    @XmlElement(defaultValue = "false")
    protected boolean withdrawn;
    @XmlElement(name = "date_of_withdraw")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfWithdraw;
    @XmlElement(name = "reason_for_withdraw")
    protected String reasonForWithdraw;

    /**
     * Gets the value of the withdrawn property.
     * 
     */
    public boolean isWithdrawn() {
        return withdrawn;
    }

    /**
     * Sets the value of the withdrawn property.
     * 
     */
    public void setWithdrawn(boolean value) {
        this.withdrawn = value;
    }

    /**
     * Gets the value of the dateOfWithdraw property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfWithdraw() {
        return dateOfWithdraw;
    }

    /**
     * Sets the value of the dateOfWithdraw property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfWithdraw(XMLGregorianCalendar value) {
        this.dateOfWithdraw = value;
    }

    /**
     * Gets the value of the reasonForWithdraw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonForWithdraw() {
        return reasonForWithdraw;
    }

    /**
     * Sets the value of the reasonForWithdraw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonForWithdraw(String value) {
        this.reasonForWithdraw = value;
    }

}
