//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.kirc._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.administration._2.AdditionalStudies;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.kirc.shared.new_tumor_event._2_7._1.NewTumorEvents;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2.Drugs;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.radiation._2.Radiations;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.AgeAtInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfBirth;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfDeath;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfLastFollowup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfLastKnownAlive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToBirth;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToDeath;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToLastFollowup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToLastKnownAlive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.EasternCancerOncologyGroup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Ethnicity;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Icd10;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.IcdO3Histology;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.IcdO3Site;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.InformedConsentVerified;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.KarnofskyPerformanceScore;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.LactateDehydrogenaseResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.Laterality;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.LymphNodeExaminedCount;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfBirth;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfDeath;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfLastFollowup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfLastKnownAlive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.NumberPackYearsSmoked;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PerformanceStatusScaleTiming;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PersonNeoplasmCancerStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PostoperativeRxTx;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PrimaryLymphNodePresentationAssessment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PrimaryTherapyOutcomeSuccess;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RaceList;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RadiationTherapy;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.StoppedSmokingYear;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TargetedMolecularTherapy;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TissueProspectiveCollectionIndicator;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TissueRetrospectiveCollectionIndicator;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.TumorTissueSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.VitalStatus;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfBirth;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfDeath;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfInitialPathologicDiagnosis;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfLastFollowup;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfLastKnownAlive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfTobaccoSmokingOnset;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.ErythrocyteSedimentationRateResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.HemoglobinResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.NumberOfLymphnodesPositive;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.PlateletQualitativeResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.SerumCalciumResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.kirc_kirp._2.WhiteCellCountResult;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2.StageEvent;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.BcrPatientBarcode;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.BcrPatientUuid;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.Gender;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.HistologicalType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.HistoryOfNeoadjuvantTreatment;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.NeoplasmHistologicGrade;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.OtherDx;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.PatientId;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.TissueSourceSite;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.shared._2.TobaccoSmokingHistory;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/administration/2.7}additional_studies" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}tumor_tissue_site"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}histological_type"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}other_dx"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}gender"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}vital_status"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_birth"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_birth"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_birth"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_birth"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_last_known_alive"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_last_known_alive"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_last_known_alive"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_last_known_alive"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_death"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_death"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_death"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_death"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_last_followup"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_last_followup"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_last_followup"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_last_followup"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}race_list"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}bcr_patient_barcode"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}tissue_source_site"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}patient_id"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}bcr_patient_uuid"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}history_of_neoadjuvant_treatment"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}informed_consent_verified"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}icd_o_3_site"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}icd_o_3_histology"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}icd_10"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}tissue_prospective_collection_indicator" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}tissue_retrospective_collection_indicator" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}ethnicity"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}person_neoplasm_cancer_status"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}performance_status_scale_timing"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_initial_pathologic_diagnosis"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_initial_pathologic_diagnosis"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_initial_pathologic_diagnosis"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}age_at_initial_pathologic_diagnosis"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_initial_pathologic_diagnosis"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_form_completion"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_form_completion"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_form_completion"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_form_completion"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}stage_event"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}laterality"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}lactate_dehydrogenase_result"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7}serum_calcium_result"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7}hemoglobin_result"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7}platelet_qualitative_result"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7}white_cell_count_result"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7}erythrocyte_sedimentation_rate_result"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}lymph_node_examined_count"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7}number_of_lymphnodes_positive"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}karnofsky_performance_score"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}eastern_cancer_oncology_group"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}primary_lymph_node_presentation_assessment"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}neoplasm_histologic_grade"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/shared/2.7}tobacco_smoking_history"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_tobacco_smoking_onset"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}stopped_smoking_year"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}number_pack_years_smoked"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}targeted_molecular_therapy" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}postoperative_rx_tx" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}radiation_therapy" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}primary_therapy_outcome_success" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/kirc/shared/new_tumor_event/2.7/1.0}new_tumor_events" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}drugs"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/radiation/2.7}radiations"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/kirc/2.7}follow_ups"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "additionalStudies",
    "tumorTissueSite",
    "histologicalType",
    "otherDx",
    "gender",
    "vitalStatus",
    "dayOfBirth",
    "monthOfBirth",
    "yearOfBirth",
    "daysToBirth",
    "dayOfLastKnownAlive",
    "monthOfLastKnownAlive",
    "yearOfLastKnownAlive",
    "daysToLastKnownAlive",
    "dayOfDeath",
    "monthOfDeath",
    "yearOfDeath",
    "daysToDeath",
    "dayOfLastFollowup",
    "monthOfLastFollowup",
    "yearOfLastFollowup",
    "daysToLastFollowup",
    "raceList",
    "bcrPatientBarcode",
    "tissueSourceSite",
    "patientId",
    "bcrPatientUuid",
    "historyOfNeoadjuvantTreatment",
    "informedConsentVerified",
    "icdO3Site",
    "icdO3Histology",
    "icd10",
    "tissueProspectiveCollectionIndicator",
    "tissueRetrospectiveCollectionIndicator",
    "ethnicity",
    "personNeoplasmCancerStatus",
    "performanceStatusScaleTiming",
    "dayOfInitialPathologicDiagnosis",
    "monthOfInitialPathologicDiagnosis",
    "daysToInitialPathologicDiagnosis",
    "ageAtInitialPathologicDiagnosis",
    "yearOfInitialPathologicDiagnosis",
    "dayOfFormCompletion",
    "monthOfFormCompletion",
    "yearOfFormCompletion",
    "daysToFormCompletion",
    "stageEvent",
    "laterality",
    "lactateDehydrogenaseResult",
    "serumCalciumResult",
    "hemoglobinResult",
    "plateletQualitativeResult",
    "whiteCellCountResult",
    "erythrocyteSedimentationRateResult",
    "lymphNodeExaminedCount",
    "numberOfLymphnodesPositive",
    "karnofskyPerformanceScore",
    "easternCancerOncologyGroup",
    "primaryLymphNodePresentationAssessment",
    "neoplasmHistologicGrade",
    "tobaccoSmokingHistory",
    "yearOfTobaccoSmokingOnset",
    "stoppedSmokingYear",
    "numberPackYearsSmoked",
    "targetedMolecularTherapy",
    "postoperativeRxTx",
    "radiationTherapy",
    "primaryTherapyOutcomeSuccess",
    "newTumorEvents",
    "drugs",
    "radiations",
    "followUps"
})
@XmlRootElement(name = "patient")
public class Patient {

    @XmlElement(name = "additional_studies", namespace = "http://tcga.nci/bcr/xml/administration/2.7")
    protected AdditionalStudies additionalStudies;
    @XmlElement(name = "tumor_tissue_site", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected TumorTissueSite tumorTissueSite;
    @XmlElement(name = "histological_type", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true, nillable = true)
    protected HistologicalType histologicalType;
    @XmlElement(name = "other_dx", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected OtherDx otherDx;
    @XmlElement(namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected Gender gender;
    @XmlElement(name = "vital_status", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected VitalStatus vitalStatus;
    @XmlElement(name = "day_of_birth", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DayOfBirth dayOfBirth;
    @XmlElement(name = "month_of_birth", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected MonthOfBirth monthOfBirth;
    @XmlElement(name = "year_of_birth", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected YearOfBirth yearOfBirth;
    @XmlElement(name = "days_to_birth", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToBirth daysToBirth;
    @XmlElement(name = "day_of_last_known_alive", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DayOfLastKnownAlive dayOfLastKnownAlive;
    @XmlElement(name = "month_of_last_known_alive", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected MonthOfLastKnownAlive monthOfLastKnownAlive;
    @XmlElement(name = "year_of_last_known_alive", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected YearOfLastKnownAlive yearOfLastKnownAlive;
    @XmlElement(name = "days_to_last_known_alive", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToLastKnownAlive daysToLastKnownAlive;
    @XmlElement(name = "day_of_death", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DayOfDeath dayOfDeath;
    @XmlElement(name = "month_of_death", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected MonthOfDeath monthOfDeath;
    @XmlElement(name = "year_of_death", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected YearOfDeath yearOfDeath;
    @XmlElement(name = "days_to_death", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToDeath daysToDeath;
    @XmlElement(name = "day_of_last_followup", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected DayOfLastFollowup dayOfLastFollowup;
    @XmlElement(name = "month_of_last_followup", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected MonthOfLastFollowup monthOfLastFollowup;
    @XmlElement(name = "year_of_last_followup", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected YearOfLastFollowup yearOfLastFollowup;
    @XmlElement(name = "days_to_last_followup", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToLastFollowup daysToLastFollowup;
    @XmlElement(name = "race_list", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected RaceList raceList;
    @XmlElement(name = "bcr_patient_barcode", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected BcrPatientBarcode bcrPatientBarcode;
    @XmlElement(name = "tissue_source_site", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected TissueSourceSite tissueSourceSite;
    @XmlElement(name = "patient_id", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected PatientId patientId;
    @XmlElement(name = "bcr_patient_uuid", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected BcrPatientUuid bcrPatientUuid;
    @XmlElement(name = "history_of_neoadjuvant_treatment", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true)
    protected HistoryOfNeoadjuvantTreatment historyOfNeoadjuvantTreatment;
    @XmlElement(name = "informed_consent_verified", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected InformedConsentVerified informedConsentVerified;
    @XmlElement(name = "icd_o_3_site", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected IcdO3Site icdO3Site;
    @XmlElement(name = "icd_o_3_histology", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected IcdO3Histology icdO3Histology;
    @XmlElement(name = "icd_10", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected Icd10 icd10;
    @XmlElement(name = "tissue_prospective_collection_indicator", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected TissueProspectiveCollectionIndicator tissueProspectiveCollectionIndicator;
    @XmlElement(name = "tissue_retrospective_collection_indicator", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected TissueRetrospectiveCollectionIndicator tissueRetrospectiveCollectionIndicator;
    @XmlElement(namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected Ethnicity ethnicity;
    @XmlElement(name = "person_neoplasm_cancer_status", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected PersonNeoplasmCancerStatus personNeoplasmCancerStatus;
    @XmlElement(name = "performance_status_scale_timing", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected PerformanceStatusScaleTiming performanceStatusScaleTiming;
    @XmlElement(name = "day_of_initial_pathologic_diagnosis", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected DayOfInitialPathologicDiagnosis dayOfInitialPathologicDiagnosis;
    @XmlElement(name = "month_of_initial_pathologic_diagnosis", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected MonthOfInitialPathologicDiagnosis monthOfInitialPathologicDiagnosis;
    @XmlElement(name = "days_to_initial_pathologic_diagnosis", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToInitialPathologicDiagnosis daysToInitialPathologicDiagnosis;
    @XmlElement(name = "age_at_initial_pathologic_diagnosis", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected AgeAtInitialPathologicDiagnosis ageAtInitialPathologicDiagnosis;
    @XmlElement(name = "year_of_initial_pathologic_diagnosis", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected YearOfInitialPathologicDiagnosis yearOfInitialPathologicDiagnosis;
    @XmlElement(name = "day_of_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected DayOfFormCompletion dayOfFormCompletion;
    @XmlElement(name = "month_of_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected MonthOfFormCompletion monthOfFormCompletion;
    @XmlElement(name = "year_of_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected YearOfFormCompletion yearOfFormCompletion;
    @XmlElement(name = "days_to_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToFormCompletion daysToFormCompletion;
    @XmlElement(name = "stage_event", namespace = "http://tcga.nci/bcr/xml/clinical/shared/stage/2.7", required = true)
    protected StageEvent stageEvent;
    @XmlElement(namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected Laterality laterality;
    @XmlElement(name = "lactate_dehydrogenase_result", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected LactateDehydrogenaseResult lactateDehydrogenaseResult;
    @XmlElement(name = "serum_calcium_result", namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", required = true, nillable = true)
    protected SerumCalciumResult serumCalciumResult;
    @XmlElement(name = "hemoglobin_result", namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", required = true, nillable = true)
    protected HemoglobinResult hemoglobinResult;
    @XmlElement(name = "platelet_qualitative_result", namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", required = true, nillable = true)
    protected PlateletQualitativeResult plateletQualitativeResult;
    @XmlElement(name = "white_cell_count_result", namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", required = true, nillable = true)
    protected WhiteCellCountResult whiteCellCountResult;
    @XmlElement(name = "erythrocyte_sedimentation_rate_result", namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", required = true, nillable = true)
    protected ErythrocyteSedimentationRateResult erythrocyteSedimentationRateResult;
    @XmlElement(name = "lymph_node_examined_count", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected LymphNodeExaminedCount lymphNodeExaminedCount;
    @XmlElement(name = "number_of_lymphnodes_positive", namespace = "http://tcga.nci/bcr/xml/clinical/shared/kirc_kirp/2.7", required = true, nillable = true)
    protected NumberOfLymphnodesPositive numberOfLymphnodesPositive;
    @XmlElement(name = "karnofsky_performance_score", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected KarnofskyPerformanceScore karnofskyPerformanceScore;
    @XmlElement(name = "eastern_cancer_oncology_group", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected EasternCancerOncologyGroup easternCancerOncologyGroup;
    @XmlElement(name = "primary_lymph_node_presentation_assessment", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected PrimaryLymphNodePresentationAssessment primaryLymphNodePresentationAssessment;
    @XmlElement(name = "neoplasm_histologic_grade", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true, nillable = true)
    protected NeoplasmHistologicGrade neoplasmHistologicGrade;
    @XmlElement(name = "tobacco_smoking_history", namespace = "http://tcga.nci/bcr/xml/shared/2.7", required = true, nillable = true)
    protected TobaccoSmokingHistory tobaccoSmokingHistory;
    @XmlElement(name = "year_of_tobacco_smoking_onset", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected YearOfTobaccoSmokingOnset yearOfTobaccoSmokingOnset;
    @XmlElement(name = "stopped_smoking_year", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected StoppedSmokingYear stoppedSmokingYear;
    @XmlElement(name = "number_pack_years_smoked", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected NumberPackYearsSmoked numberPackYearsSmoked;
    @XmlElement(name = "targeted_molecular_therapy", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected TargetedMolecularTherapy targetedMolecularTherapy;
    @XmlElement(name = "postoperative_rx_tx", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected PostoperativeRxTx postoperativeRxTx;
    @XmlElement(name = "radiation_therapy", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected RadiationTherapy radiationTherapy;
    @XmlElement(name = "primary_therapy_outcome_success", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected PrimaryTherapyOutcomeSuccess primaryTherapyOutcomeSuccess;
    @XmlElement(name = "new_tumor_events", namespace = "http://tcga.nci/bcr/xml/clinical/kirc/shared/new_tumor_event/2.7/1.0")
    protected NewTumorEvents newTumorEvents;
    @XmlElement(namespace = "http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7", required = true)
    protected Drugs drugs;
    @XmlElement(namespace = "http://tcga.nci/bcr/xml/clinical/radiation/2.7", required = true)
    protected Radiations radiations;
    @XmlElement(name = "follow_ups", required = true)
    protected FollowUps followUps;

    /**
     * Gets the value of the additionalStudies property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStudies }
     *     
     */
    public AdditionalStudies getAdditionalStudies() {
        return additionalStudies;
    }

    /**
     * Sets the value of the additionalStudies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStudies }
     *     
     */
    public void setAdditionalStudies(AdditionalStudies value) {
        this.additionalStudies = value;
    }

    /**
     * Gets the value of the tumorTissueSite property.
     * 
     * @return
     *     possible object is
     *     {@link TumorTissueSite }
     *     
     */
    public TumorTissueSite getTumorTissueSite() {
        return tumorTissueSite;
    }

    /**
     * Sets the value of the tumorTissueSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TumorTissueSite }
     *     
     */
    public void setTumorTissueSite(TumorTissueSite value) {
        this.tumorTissueSite = value;
    }

    /**
     * Gets the value of the histologicalType property.
     * 
     * @return
     *     possible object is
     *     {@link HistologicalType }
     *     
     */
    public HistologicalType getHistologicalType() {
        return histologicalType;
    }

    /**
     * Sets the value of the histologicalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistologicalType }
     *     
     */
    public void setHistologicalType(HistologicalType value) {
        this.histologicalType = value;
    }

    /**
     * Gets the value of the otherDx property.
     * 
     * @return
     *     possible object is
     *     {@link OtherDx }
     *     
     */
    public OtherDx getOtherDx() {
        return otherDx;
    }

    /**
     * Sets the value of the otherDx property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherDx }
     *     
     */
    public void setOtherDx(OtherDx value) {
        this.otherDx = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the vitalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VitalStatus }
     *     
     */
    public VitalStatus getVitalStatus() {
        return vitalStatus;
    }

    /**
     * Sets the value of the vitalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VitalStatus }
     *     
     */
    public void setVitalStatus(VitalStatus value) {
        this.vitalStatus = value;
    }

    /**
     * Gets the value of the dayOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfBirth }
     *     
     */
    public DayOfBirth getDayOfBirth() {
        return dayOfBirth;
    }

    /**
     * Sets the value of the dayOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfBirth }
     *     
     */
    public void setDayOfBirth(DayOfBirth value) {
        this.dayOfBirth = value;
    }

    /**
     * Gets the value of the monthOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfBirth }
     *     
     */
    public MonthOfBirth getMonthOfBirth() {
        return monthOfBirth;
    }

    /**
     * Sets the value of the monthOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfBirth }
     *     
     */
    public void setMonthOfBirth(MonthOfBirth value) {
        this.monthOfBirth = value;
    }

    /**
     * Gets the value of the yearOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfBirth }
     *     
     */
    public YearOfBirth getYearOfBirth() {
        return yearOfBirth;
    }

    /**
     * Sets the value of the yearOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfBirth }
     *     
     */
    public void setYearOfBirth(YearOfBirth value) {
        this.yearOfBirth = value;
    }

    /**
     * Gets the value of the daysToBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToBirth }
     *     
     */
    public DaysToBirth getDaysToBirth() {
        return daysToBirth;
    }

    /**
     * Sets the value of the daysToBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToBirth }
     *     
     */
    public void setDaysToBirth(DaysToBirth value) {
        this.daysToBirth = value;
    }

    /**
     * Gets the value of the dayOfLastKnownAlive property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfLastKnownAlive }
     *     
     */
    public DayOfLastKnownAlive getDayOfLastKnownAlive() {
        return dayOfLastKnownAlive;
    }

    /**
     * Sets the value of the dayOfLastKnownAlive property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfLastKnownAlive }
     *     
     */
    public void setDayOfLastKnownAlive(DayOfLastKnownAlive value) {
        this.dayOfLastKnownAlive = value;
    }

    /**
     * Gets the value of the monthOfLastKnownAlive property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfLastKnownAlive }
     *     
     */
    public MonthOfLastKnownAlive getMonthOfLastKnownAlive() {
        return monthOfLastKnownAlive;
    }

    /**
     * Sets the value of the monthOfLastKnownAlive property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfLastKnownAlive }
     *     
     */
    public void setMonthOfLastKnownAlive(MonthOfLastKnownAlive value) {
        this.monthOfLastKnownAlive = value;
    }

    /**
     * Gets the value of the yearOfLastKnownAlive property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfLastKnownAlive }
     *     
     */
    public YearOfLastKnownAlive getYearOfLastKnownAlive() {
        return yearOfLastKnownAlive;
    }

    /**
     * Sets the value of the yearOfLastKnownAlive property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfLastKnownAlive }
     *     
     */
    public void setYearOfLastKnownAlive(YearOfLastKnownAlive value) {
        this.yearOfLastKnownAlive = value;
    }

    /**
     * Gets the value of the daysToLastKnownAlive property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToLastKnownAlive }
     *     
     */
    public DaysToLastKnownAlive getDaysToLastKnownAlive() {
        return daysToLastKnownAlive;
    }

    /**
     * Sets the value of the daysToLastKnownAlive property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToLastKnownAlive }
     *     
     */
    public void setDaysToLastKnownAlive(DaysToLastKnownAlive value) {
        this.daysToLastKnownAlive = value;
    }

    /**
     * Gets the value of the dayOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfDeath }
     *     
     */
    public DayOfDeath getDayOfDeath() {
        return dayOfDeath;
    }

    /**
     * Sets the value of the dayOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfDeath }
     *     
     */
    public void setDayOfDeath(DayOfDeath value) {
        this.dayOfDeath = value;
    }

    /**
     * Gets the value of the monthOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfDeath }
     *     
     */
    public MonthOfDeath getMonthOfDeath() {
        return monthOfDeath;
    }

    /**
     * Sets the value of the monthOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfDeath }
     *     
     */
    public void setMonthOfDeath(MonthOfDeath value) {
        this.monthOfDeath = value;
    }

    /**
     * Gets the value of the yearOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfDeath }
     *     
     */
    public YearOfDeath getYearOfDeath() {
        return yearOfDeath;
    }

    /**
     * Sets the value of the yearOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfDeath }
     *     
     */
    public void setYearOfDeath(YearOfDeath value) {
        this.yearOfDeath = value;
    }

    /**
     * Gets the value of the daysToDeath property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToDeath }
     *     
     */
    public DaysToDeath getDaysToDeath() {
        return daysToDeath;
    }

    /**
     * Sets the value of the daysToDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToDeath }
     *     
     */
    public void setDaysToDeath(DaysToDeath value) {
        this.daysToDeath = value;
    }

    /**
     * Gets the value of the dayOfLastFollowup property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfLastFollowup }
     *     
     */
    public DayOfLastFollowup getDayOfLastFollowup() {
        return dayOfLastFollowup;
    }

    /**
     * Sets the value of the dayOfLastFollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfLastFollowup }
     *     
     */
    public void setDayOfLastFollowup(DayOfLastFollowup value) {
        this.dayOfLastFollowup = value;
    }

    /**
     * Gets the value of the monthOfLastFollowup property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfLastFollowup }
     *     
     */
    public MonthOfLastFollowup getMonthOfLastFollowup() {
        return monthOfLastFollowup;
    }

    /**
     * Sets the value of the monthOfLastFollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfLastFollowup }
     *     
     */
    public void setMonthOfLastFollowup(MonthOfLastFollowup value) {
        this.monthOfLastFollowup = value;
    }

    /**
     * Gets the value of the yearOfLastFollowup property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfLastFollowup }
     *     
     */
    public YearOfLastFollowup getYearOfLastFollowup() {
        return yearOfLastFollowup;
    }

    /**
     * Sets the value of the yearOfLastFollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfLastFollowup }
     *     
     */
    public void setYearOfLastFollowup(YearOfLastFollowup value) {
        this.yearOfLastFollowup = value;
    }

    /**
     * Gets the value of the daysToLastFollowup property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToLastFollowup }
     *     
     */
    public DaysToLastFollowup getDaysToLastFollowup() {
        return daysToLastFollowup;
    }

    /**
     * Sets the value of the daysToLastFollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToLastFollowup }
     *     
     */
    public void setDaysToLastFollowup(DaysToLastFollowup value) {
        this.daysToLastFollowup = value;
    }

    /**
     * Gets the value of the raceList property.
     * 
     * @return
     *     possible object is
     *     {@link RaceList }
     *     
     */
    public RaceList getRaceList() {
        return raceList;
    }

    /**
     * Sets the value of the raceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceList }
     *     
     */
    public void setRaceList(RaceList value) {
        this.raceList = value;
    }

    /**
     * Gets the value of the bcrPatientBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link BcrPatientBarcode }
     *     
     */
    public BcrPatientBarcode getBcrPatientBarcode() {
        return bcrPatientBarcode;
    }

    /**
     * Sets the value of the bcrPatientBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrPatientBarcode }
     *     
     */
    public void setBcrPatientBarcode(BcrPatientBarcode value) {
        this.bcrPatientBarcode = value;
    }

    /**
     * Gets the value of the tissueSourceSite property.
     * 
     * @return
     *     possible object is
     *     {@link TissueSourceSite }
     *     
     */
    public TissueSourceSite getTissueSourceSite() {
        return tissueSourceSite;
    }

    /**
     * Sets the value of the tissueSourceSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TissueSourceSite }
     *     
     */
    public void setTissueSourceSite(TissueSourceSite value) {
        this.tissueSourceSite = value;
    }

    /**
     * Gets the value of the patientId property.
     * 
     * @return
     *     possible object is
     *     {@link PatientId }
     *     
     */
    public PatientId getPatientId() {
        return patientId;
    }

    /**
     * Sets the value of the patientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientId }
     *     
     */
    public void setPatientId(PatientId value) {
        this.patientId = value;
    }

    /**
     * Gets the value of the bcrPatientUuid property.
     * 
     * @return
     *     possible object is
     *     {@link BcrPatientUuid }
     *     
     */
    public BcrPatientUuid getBcrPatientUuid() {
        return bcrPatientUuid;
    }

    /**
     * Sets the value of the bcrPatientUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrPatientUuid }
     *     
     */
    public void setBcrPatientUuid(BcrPatientUuid value) {
        this.bcrPatientUuid = value;
    }

    /**
     * Gets the value of the historyOfNeoadjuvantTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryOfNeoadjuvantTreatment }
     *     
     */
    public HistoryOfNeoadjuvantTreatment getHistoryOfNeoadjuvantTreatment() {
        return historyOfNeoadjuvantTreatment;
    }

    /**
     * Sets the value of the historyOfNeoadjuvantTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryOfNeoadjuvantTreatment }
     *     
     */
    public void setHistoryOfNeoadjuvantTreatment(HistoryOfNeoadjuvantTreatment value) {
        this.historyOfNeoadjuvantTreatment = value;
    }

    /**
     * Gets the value of the informedConsentVerified property.
     * 
     * @return
     *     possible object is
     *     {@link InformedConsentVerified }
     *     
     */
    public InformedConsentVerified getInformedConsentVerified() {
        return informedConsentVerified;
    }

    /**
     * Sets the value of the informedConsentVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformedConsentVerified }
     *     
     */
    public void setInformedConsentVerified(InformedConsentVerified value) {
        this.informedConsentVerified = value;
    }

    /**
     * Gets the value of the icdO3Site property.
     * 
     * @return
     *     possible object is
     *     {@link IcdO3Site }
     *     
     */
    public IcdO3Site getIcdO3Site() {
        return icdO3Site;
    }

    /**
     * Sets the value of the icdO3Site property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcdO3Site }
     *     
     */
    public void setIcdO3Site(IcdO3Site value) {
        this.icdO3Site = value;
    }

    /**
     * Gets the value of the icdO3Histology property.
     * 
     * @return
     *     possible object is
     *     {@link IcdO3Histology }
     *     
     */
    public IcdO3Histology getIcdO3Histology() {
        return icdO3Histology;
    }

    /**
     * Sets the value of the icdO3Histology property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcdO3Histology }
     *     
     */
    public void setIcdO3Histology(IcdO3Histology value) {
        this.icdO3Histology = value;
    }

    /**
     * Gets the value of the icd10 property.
     * 
     * @return
     *     possible object is
     *     {@link Icd10 }
     *     
     */
    public Icd10 getIcd10() {
        return icd10;
    }

    /**
     * Sets the value of the icd10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Icd10 }
     *     
     */
    public void setIcd10(Icd10 value) {
        this.icd10 = value;
    }

    /**
     * Gets the value of the tissueProspectiveCollectionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link TissueProspectiveCollectionIndicator }
     *     
     */
    public TissueProspectiveCollectionIndicator getTissueProspectiveCollectionIndicator() {
        return tissueProspectiveCollectionIndicator;
    }

    /**
     * Sets the value of the tissueProspectiveCollectionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TissueProspectiveCollectionIndicator }
     *     
     */
    public void setTissueProspectiveCollectionIndicator(TissueProspectiveCollectionIndicator value) {
        this.tissueProspectiveCollectionIndicator = value;
    }

    /**
     * Gets the value of the tissueRetrospectiveCollectionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link TissueRetrospectiveCollectionIndicator }
     *     
     */
    public TissueRetrospectiveCollectionIndicator getTissueRetrospectiveCollectionIndicator() {
        return tissueRetrospectiveCollectionIndicator;
    }

    /**
     * Sets the value of the tissueRetrospectiveCollectionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TissueRetrospectiveCollectionIndicator }
     *     
     */
    public void setTissueRetrospectiveCollectionIndicator(TissueRetrospectiveCollectionIndicator value) {
        this.tissueRetrospectiveCollectionIndicator = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link Ethnicity }
     *     
     */
    public Ethnicity getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ethnicity }
     *     
     */
    public void setEthnicity(Ethnicity value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the personNeoplasmCancerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNeoplasmCancerStatus }
     *     
     */
    public PersonNeoplasmCancerStatus getPersonNeoplasmCancerStatus() {
        return personNeoplasmCancerStatus;
    }

    /**
     * Sets the value of the personNeoplasmCancerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNeoplasmCancerStatus }
     *     
     */
    public void setPersonNeoplasmCancerStatus(PersonNeoplasmCancerStatus value) {
        this.personNeoplasmCancerStatus = value;
    }

    /**
     * Gets the value of the performanceStatusScaleTiming property.
     * 
     * @return
     *     possible object is
     *     {@link PerformanceStatusScaleTiming }
     *     
     */
    public PerformanceStatusScaleTiming getPerformanceStatusScaleTiming() {
        return performanceStatusScaleTiming;
    }

    /**
     * Sets the value of the performanceStatusScaleTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformanceStatusScaleTiming }
     *     
     */
    public void setPerformanceStatusScaleTiming(PerformanceStatusScaleTiming value) {
        this.performanceStatusScaleTiming = value;
    }

    /**
     * Gets the value of the dayOfInitialPathologicDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfInitialPathologicDiagnosis }
     *     
     */
    public DayOfInitialPathologicDiagnosis getDayOfInitialPathologicDiagnosis() {
        return dayOfInitialPathologicDiagnosis;
    }

    /**
     * Sets the value of the dayOfInitialPathologicDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfInitialPathologicDiagnosis }
     *     
     */
    public void setDayOfInitialPathologicDiagnosis(DayOfInitialPathologicDiagnosis value) {
        this.dayOfInitialPathologicDiagnosis = value;
    }

    /**
     * Gets the value of the monthOfInitialPathologicDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfInitialPathologicDiagnosis }
     *     
     */
    public MonthOfInitialPathologicDiagnosis getMonthOfInitialPathologicDiagnosis() {
        return monthOfInitialPathologicDiagnosis;
    }

    /**
     * Sets the value of the monthOfInitialPathologicDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfInitialPathologicDiagnosis }
     *     
     */
    public void setMonthOfInitialPathologicDiagnosis(MonthOfInitialPathologicDiagnosis value) {
        this.monthOfInitialPathologicDiagnosis = value;
    }

    /**
     * Gets the value of the daysToInitialPathologicDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToInitialPathologicDiagnosis }
     *     
     */
    public DaysToInitialPathologicDiagnosis getDaysToInitialPathologicDiagnosis() {
        return daysToInitialPathologicDiagnosis;
    }

    /**
     * Sets the value of the daysToInitialPathologicDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToInitialPathologicDiagnosis }
     *     
     */
    public void setDaysToInitialPathologicDiagnosis(DaysToInitialPathologicDiagnosis value) {
        this.daysToInitialPathologicDiagnosis = value;
    }

    /**
     * Gets the value of the ageAtInitialPathologicDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link AgeAtInitialPathologicDiagnosis }
     *     
     */
    public AgeAtInitialPathologicDiagnosis getAgeAtInitialPathologicDiagnosis() {
        return ageAtInitialPathologicDiagnosis;
    }

    /**
     * Sets the value of the ageAtInitialPathologicDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeAtInitialPathologicDiagnosis }
     *     
     */
    public void setAgeAtInitialPathologicDiagnosis(AgeAtInitialPathologicDiagnosis value) {
        this.ageAtInitialPathologicDiagnosis = value;
    }

    /**
     * Gets the value of the yearOfInitialPathologicDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfInitialPathologicDiagnosis }
     *     
     */
    public YearOfInitialPathologicDiagnosis getYearOfInitialPathologicDiagnosis() {
        return yearOfInitialPathologicDiagnosis;
    }

    /**
     * Sets the value of the yearOfInitialPathologicDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfInitialPathologicDiagnosis }
     *     
     */
    public void setYearOfInitialPathologicDiagnosis(YearOfInitialPathologicDiagnosis value) {
        this.yearOfInitialPathologicDiagnosis = value;
    }

    /**
     * Gets the value of the dayOfFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfFormCompletion }
     *     
     */
    public DayOfFormCompletion getDayOfFormCompletion() {
        return dayOfFormCompletion;
    }

    /**
     * Sets the value of the dayOfFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfFormCompletion }
     *     
     */
    public void setDayOfFormCompletion(DayOfFormCompletion value) {
        this.dayOfFormCompletion = value;
    }

    /**
     * Gets the value of the monthOfFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfFormCompletion }
     *     
     */
    public MonthOfFormCompletion getMonthOfFormCompletion() {
        return monthOfFormCompletion;
    }

    /**
     * Sets the value of the monthOfFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfFormCompletion }
     *     
     */
    public void setMonthOfFormCompletion(MonthOfFormCompletion value) {
        this.monthOfFormCompletion = value;
    }

    /**
     * Gets the value of the yearOfFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfFormCompletion }
     *     
     */
    public YearOfFormCompletion getYearOfFormCompletion() {
        return yearOfFormCompletion;
    }

    /**
     * Sets the value of the yearOfFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfFormCompletion }
     *     
     */
    public void setYearOfFormCompletion(YearOfFormCompletion value) {
        this.yearOfFormCompletion = value;
    }

    /**
     * Gets the value of the daysToFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToFormCompletion }
     *     
     */
    public DaysToFormCompletion getDaysToFormCompletion() {
        return daysToFormCompletion;
    }

    /**
     * Sets the value of the daysToFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToFormCompletion }
     *     
     */
    public void setDaysToFormCompletion(DaysToFormCompletion value) {
        this.daysToFormCompletion = value;
    }

    /**
     * Gets the value of the stageEvent property.
     * 
     * @return
     *     possible object is
     *     {@link StageEvent }
     *     
     */
    public StageEvent getStageEvent() {
        return stageEvent;
    }

    /**
     * Sets the value of the stageEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link StageEvent }
     *     
     */
    public void setStageEvent(StageEvent value) {
        this.stageEvent = value;
    }

    /**
     * Gets the value of the laterality property.
     * 
     * @return
     *     possible object is
     *     {@link Laterality }
     *     
     */
    public Laterality getLaterality() {
        return laterality;
    }

    /**
     * Sets the value of the laterality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Laterality }
     *     
     */
    public void setLaterality(Laterality value) {
        this.laterality = value;
    }

    /**
     * Gets the value of the lactateDehydrogenaseResult property.
     * 
     * @return
     *     possible object is
     *     {@link LactateDehydrogenaseResult }
     *     
     */
    public LactateDehydrogenaseResult getLactateDehydrogenaseResult() {
        return lactateDehydrogenaseResult;
    }

    /**
     * Sets the value of the lactateDehydrogenaseResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link LactateDehydrogenaseResult }
     *     
     */
    public void setLactateDehydrogenaseResult(LactateDehydrogenaseResult value) {
        this.lactateDehydrogenaseResult = value;
    }

    /**
     * Gets the value of the serumCalciumResult property.
     * 
     * @return
     *     possible object is
     *     {@link SerumCalciumResult }
     *     
     */
    public SerumCalciumResult getSerumCalciumResult() {
        return serumCalciumResult;
    }

    /**
     * Sets the value of the serumCalciumResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerumCalciumResult }
     *     
     */
    public void setSerumCalciumResult(SerumCalciumResult value) {
        this.serumCalciumResult = value;
    }

    /**
     * Gets the value of the hemoglobinResult property.
     * 
     * @return
     *     possible object is
     *     {@link HemoglobinResult }
     *     
     */
    public HemoglobinResult getHemoglobinResult() {
        return hemoglobinResult;
    }

    /**
     * Sets the value of the hemoglobinResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link HemoglobinResult }
     *     
     */
    public void setHemoglobinResult(HemoglobinResult value) {
        this.hemoglobinResult = value;
    }

    /**
     * Gets the value of the plateletQualitativeResult property.
     * 
     * @return
     *     possible object is
     *     {@link PlateletQualitativeResult }
     *     
     */
    public PlateletQualitativeResult getPlateletQualitativeResult() {
        return plateletQualitativeResult;
    }

    /**
     * Sets the value of the plateletQualitativeResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlateletQualitativeResult }
     *     
     */
    public void setPlateletQualitativeResult(PlateletQualitativeResult value) {
        this.plateletQualitativeResult = value;
    }

    /**
     * Gets the value of the whiteCellCountResult property.
     * 
     * @return
     *     possible object is
     *     {@link WhiteCellCountResult }
     *     
     */
    public WhiteCellCountResult getWhiteCellCountResult() {
        return whiteCellCountResult;
    }

    /**
     * Sets the value of the whiteCellCountResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhiteCellCountResult }
     *     
     */
    public void setWhiteCellCountResult(WhiteCellCountResult value) {
        this.whiteCellCountResult = value;
    }

    /**
     * Gets the value of the erythrocyteSedimentationRateResult property.
     * 
     * @return
     *     possible object is
     *     {@link ErythrocyteSedimentationRateResult }
     *     
     */
    public ErythrocyteSedimentationRateResult getErythrocyteSedimentationRateResult() {
        return erythrocyteSedimentationRateResult;
    }

    /**
     * Sets the value of the erythrocyteSedimentationRateResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErythrocyteSedimentationRateResult }
     *     
     */
    public void setErythrocyteSedimentationRateResult(ErythrocyteSedimentationRateResult value) {
        this.erythrocyteSedimentationRateResult = value;
    }

    /**
     * Gets the value of the lymphNodeExaminedCount property.
     * 
     * @return
     *     possible object is
     *     {@link LymphNodeExaminedCount }
     *     
     */
    public LymphNodeExaminedCount getLymphNodeExaminedCount() {
        return lymphNodeExaminedCount;
    }

    /**
     * Sets the value of the lymphNodeExaminedCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link LymphNodeExaminedCount }
     *     
     */
    public void setLymphNodeExaminedCount(LymphNodeExaminedCount value) {
        this.lymphNodeExaminedCount = value;
    }

    /**
     * Gets the value of the numberOfLymphnodesPositive property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfLymphnodesPositive }
     *     
     */
    public NumberOfLymphnodesPositive getNumberOfLymphnodesPositive() {
        return numberOfLymphnodesPositive;
    }

    /**
     * Sets the value of the numberOfLymphnodesPositive property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfLymphnodesPositive }
     *     
     */
    public void setNumberOfLymphnodesPositive(NumberOfLymphnodesPositive value) {
        this.numberOfLymphnodesPositive = value;
    }

    /**
     * Gets the value of the karnofskyPerformanceScore property.
     * 
     * @return
     *     possible object is
     *     {@link KarnofskyPerformanceScore }
     *     
     */
    public KarnofskyPerformanceScore getKarnofskyPerformanceScore() {
        return karnofskyPerformanceScore;
    }

    /**
     * Sets the value of the karnofskyPerformanceScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link KarnofskyPerformanceScore }
     *     
     */
    public void setKarnofskyPerformanceScore(KarnofskyPerformanceScore value) {
        this.karnofskyPerformanceScore = value;
    }

    /**
     * Gets the value of the easternCancerOncologyGroup property.
     * 
     * @return
     *     possible object is
     *     {@link EasternCancerOncologyGroup }
     *     
     */
    public EasternCancerOncologyGroup getEasternCancerOncologyGroup() {
        return easternCancerOncologyGroup;
    }

    /**
     * Sets the value of the easternCancerOncologyGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link EasternCancerOncologyGroup }
     *     
     */
    public void setEasternCancerOncologyGroup(EasternCancerOncologyGroup value) {
        this.easternCancerOncologyGroup = value;
    }

    /**
     * Gets the value of the primaryLymphNodePresentationAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryLymphNodePresentationAssessment }
     *     
     */
    public PrimaryLymphNodePresentationAssessment getPrimaryLymphNodePresentationAssessment() {
        return primaryLymphNodePresentationAssessment;
    }

    /**
     * Sets the value of the primaryLymphNodePresentationAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryLymphNodePresentationAssessment }
     *     
     */
    public void setPrimaryLymphNodePresentationAssessment(PrimaryLymphNodePresentationAssessment value) {
        this.primaryLymphNodePresentationAssessment = value;
    }

    /**
     * Gets the value of the neoplasmHistologicGrade property.
     * 
     * @return
     *     possible object is
     *     {@link NeoplasmHistologicGrade }
     *     
     */
    public NeoplasmHistologicGrade getNeoplasmHistologicGrade() {
        return neoplasmHistologicGrade;
    }

    /**
     * Sets the value of the neoplasmHistologicGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link NeoplasmHistologicGrade }
     *     
     */
    public void setNeoplasmHistologicGrade(NeoplasmHistologicGrade value) {
        this.neoplasmHistologicGrade = value;
    }

    /**
     * Gets the value of the tobaccoSmokingHistory property.
     * 
     * @return
     *     possible object is
     *     {@link TobaccoSmokingHistory }
     *     
     */
    public TobaccoSmokingHistory getTobaccoSmokingHistory() {
        return tobaccoSmokingHistory;
    }

    /**
     * Sets the value of the tobaccoSmokingHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TobaccoSmokingHistory }
     *     
     */
    public void setTobaccoSmokingHistory(TobaccoSmokingHistory value) {
        this.tobaccoSmokingHistory = value;
    }

    /**
     * Gets the value of the yearOfTobaccoSmokingOnset property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfTobaccoSmokingOnset }
     *     
     */
    public YearOfTobaccoSmokingOnset getYearOfTobaccoSmokingOnset() {
        return yearOfTobaccoSmokingOnset;
    }

    /**
     * Sets the value of the yearOfTobaccoSmokingOnset property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfTobaccoSmokingOnset }
     *     
     */
    public void setYearOfTobaccoSmokingOnset(YearOfTobaccoSmokingOnset value) {
        this.yearOfTobaccoSmokingOnset = value;
    }

    /**
     * Gets the value of the stoppedSmokingYear property.
     * 
     * @return
     *     possible object is
     *     {@link StoppedSmokingYear }
     *     
     */
    public StoppedSmokingYear getStoppedSmokingYear() {
        return stoppedSmokingYear;
    }

    /**
     * Sets the value of the stoppedSmokingYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoppedSmokingYear }
     *     
     */
    public void setStoppedSmokingYear(StoppedSmokingYear value) {
        this.stoppedSmokingYear = value;
    }

    /**
     * Gets the value of the numberPackYearsSmoked property.
     * 
     * @return
     *     possible object is
     *     {@link NumberPackYearsSmoked }
     *     
     */
    public NumberPackYearsSmoked getNumberPackYearsSmoked() {
        return numberPackYearsSmoked;
    }

    /**
     * Sets the value of the numberPackYearsSmoked property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberPackYearsSmoked }
     *     
     */
    public void setNumberPackYearsSmoked(NumberPackYearsSmoked value) {
        this.numberPackYearsSmoked = value;
    }

    /**
     * Gets the value of the targetedMolecularTherapy property.
     * 
     * @return
     *     possible object is
     *     {@link TargetedMolecularTherapy }
     *     
     */
    public TargetedMolecularTherapy getTargetedMolecularTherapy() {
        return targetedMolecularTherapy;
    }

    /**
     * Sets the value of the targetedMolecularTherapy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetedMolecularTherapy }
     *     
     */
    public void setTargetedMolecularTherapy(TargetedMolecularTherapy value) {
        this.targetedMolecularTherapy = value;
    }

    /**
     * Gets the value of the postoperativeRxTx property.
     * 
     * @return
     *     possible object is
     *     {@link PostoperativeRxTx }
     *     
     */
    public PostoperativeRxTx getPostoperativeRxTx() {
        return postoperativeRxTx;
    }

    /**
     * Sets the value of the postoperativeRxTx property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostoperativeRxTx }
     *     
     */
    public void setPostoperativeRxTx(PostoperativeRxTx value) {
        this.postoperativeRxTx = value;
    }

    /**
     * Gets the value of the radiationTherapy property.
     * 
     * @return
     *     possible object is
     *     {@link RadiationTherapy }
     *     
     */
    public RadiationTherapy getRadiationTherapy() {
        return radiationTherapy;
    }

    /**
     * Sets the value of the radiationTherapy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadiationTherapy }
     *     
     */
    public void setRadiationTherapy(RadiationTherapy value) {
        this.radiationTherapy = value;
    }

    /**
     * Gets the value of the primaryTherapyOutcomeSuccess property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryTherapyOutcomeSuccess }
     *     
     */
    public PrimaryTherapyOutcomeSuccess getPrimaryTherapyOutcomeSuccess() {
        return primaryTherapyOutcomeSuccess;
    }

    /**
     * Sets the value of the primaryTherapyOutcomeSuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryTherapyOutcomeSuccess }
     *     
     */
    public void setPrimaryTherapyOutcomeSuccess(PrimaryTherapyOutcomeSuccess value) {
        this.primaryTherapyOutcomeSuccess = value;
    }

    /**
     * Gets the value of the newTumorEvents property.
     * 
     * @return
     *     possible object is
     *     {@link NewTumorEvents }
     *     
     */
    public NewTumorEvents getNewTumorEvents() {
        return newTumorEvents;
    }

    /**
     * Sets the value of the newTumorEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewTumorEvents }
     *     
     */
    public void setNewTumorEvents(NewTumorEvents value) {
        this.newTumorEvents = value;
    }

    /**
     * Gets the value of the drugs property.
     * 
     * @return
     *     possible object is
     *     {@link Drugs }
     *     
     */
    public Drugs getDrugs() {
        return drugs;
    }

    /**
     * Sets the value of the drugs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drugs }
     *     
     */
    public void setDrugs(Drugs value) {
        this.drugs = value;
    }

    /**
     * Gets the value of the radiations property.
     * 
     * @return
     *     possible object is
     *     {@link Radiations }
     *     
     */
    public Radiations getRadiations() {
        return radiations;
    }

    /**
     * Sets the value of the radiations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Radiations }
     *     
     */
    public void setRadiations(Radiations value) {
        this.radiations = value;
    }

    /**
     * Gets the value of the followUps property.
     * 
     * @return
     *     possible object is
     *     {@link FollowUps }
     *     
     */
    public FollowUps getFollowUps() {
        return followUps;
    }

    /**
     * Sets the value of the followUps property.
     * 
     * @param value
     *     allowed object is
     *     {@link FollowUps }
     *     
     */
    public void setFollowUps(FollowUps value) {
        this.followUps = value;
    }

}
