//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 05:01:33 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.brca.shared.new_tumor_event._2_7._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.new_tumor_event._2.NewTumorEventAfterInitialTreatment;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7}new_tumor_event_after_initial_treatment"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/brca/shared/new_tumor_event/2.7/1.0}new_tumor_event" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "newTumorEventAfterInitialTreatment",
    "newTumorEvent"
})
@XmlRootElement(name = "new_tumor_events")
public class NewTumorEvents {

    @XmlElement(name = "new_tumor_event_after_initial_treatment", namespace = "http://tcga.nci/bcr/xml/clinical/shared/new_tumor_event/2.7", required = true, nillable = true)
    protected NewTumorEventAfterInitialTreatment newTumorEventAfterInitialTreatment;
    @XmlElement(name = "new_tumor_event")
    protected List<NewTumorEvent> newTumorEvent;

    /**
     * Gets the value of the newTumorEventAfterInitialTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link NewTumorEventAfterInitialTreatment }
     *     
     */
    public NewTumorEventAfterInitialTreatment getNewTumorEventAfterInitialTreatment() {
        return newTumorEventAfterInitialTreatment;
    }

    /**
     * Sets the value of the newTumorEventAfterInitialTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewTumorEventAfterInitialTreatment }
     *     
     */
    public void setNewTumorEventAfterInitialTreatment(NewTumorEventAfterInitialTreatment value) {
        this.newTumorEventAfterInitialTreatment = value;
    }

    /**
     * Gets the value of the newTumorEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newTumorEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewTumorEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewTumorEvent }
     * 
     * 
     */
    public List<NewTumorEvent> getNewTumorEvent() {
        if (newTumorEvent == null) {
            newTumorEvent = new ArrayList<NewTumorEvent>();
        }
        return this.newTumorEvent;
    }

}
