//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 05:01:33 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tcga.nci/bcr/xml/clinical/brca/shared/new_tumor_event/2.7/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.brca.shared.new_tumor_event._2_7._1;
