//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.pharmaceutical._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DayOfFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.DaysToFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MeasureOfResponse;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MonthOfFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PharmRegimen;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.PharmRegimenOther;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RegimenIndication;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.RegimenIndicationNotes;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.YearOfFormCompletion;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DayOfStemCellTransplantation;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.DaysToStemCellTransplantation;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.MonthOfStemCellTransplantation;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.ocg._2.YearOfStemCellTransplantation;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}tx_on_clinical_trial"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}regimen_number"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}bcr_drug_barcode"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}bcr_drug_uuid"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}total_dose"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}total_dose_units"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}prescribed_dose"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}prescribed_dose_units"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}number_cycles"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}day_of_drug_therapy_start"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}month_of_drug_therapy_start"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}year_of_drug_therapy_start"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}days_to_drug_therapy_start"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}day_of_drug_therapy_end"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}month_of_drug_therapy_end"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}year_of_drug_therapy_end"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}days_to_drug_therapy_end"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}history_prior_systemic_therapy" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}therapy_types"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}drug_name"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}clinical_trail_drug_classification"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}stem_cell_transplantation" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}stem_cell_transplantation_type" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7}day_of_stem_cell_transplantation"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7}month_of_stem_cell_transplantation"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7}year_of_stem_cell_transplantation"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7}days_to_stem_cell_transplantation"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}pharm_regimen" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}pharm_regimen_other" minOccurs="0"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}regimen_indication"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}regimen_indication_notes"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}route_of_administrations"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/pharmaceutical/2.7}therapy_ongoing"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}measure_of_response"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}day_of_form_completion"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}month_of_form_completion"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}year_of_form_completion"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}days_to_form_completion"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "txOnClinicalTrial",
    "regimenNumber",
    "bcrDrugBarcode",
    "bcrDrugUuid",
    "totalDose",
    "totalDoseUnits",
    "prescribedDose",
    "prescribedDoseUnits",
    "numberCycles",
    "dayOfDrugTherapyStart",
    "monthOfDrugTherapyStart",
    "yearOfDrugTherapyStart",
    "daysToDrugTherapyStart",
    "dayOfDrugTherapyEnd",
    "monthOfDrugTherapyEnd",
    "yearOfDrugTherapyEnd",
    "daysToDrugTherapyEnd",
    "historyPriorSystemicTherapy",
    "therapyTypes",
    "drugName",
    "clinicalTrailDrugClassification",
    "stemCellTransplantation",
    "stemCellTransplantationType",
    "dayOfStemCellTransplantation",
    "monthOfStemCellTransplantation",
    "yearOfStemCellTransplantation",
    "daysToStemCellTransplantation",
    "pharmRegimen",
    "pharmRegimenOther",
    "regimenIndication",
    "regimenIndicationNotes",
    "routeOfAdministrations",
    "therapyOngoing",
    "measureOfResponse",
    "dayOfFormCompletion",
    "monthOfFormCompletion",
    "yearOfFormCompletion",
    "daysToFormCompletion"
})
@XmlRootElement(name = "drug")
public class Drug {

    @XmlElement(name = "tx_on_clinical_trial", required = true)
    protected TxOnClinicalTrial txOnClinicalTrial;
    @XmlElement(name = "regimen_number", required = true)
    protected RegimenNumber regimenNumber;
    @XmlElement(name = "bcr_drug_barcode", required = true)
    protected BcrDrugBarcode bcrDrugBarcode;
    @XmlElement(name = "bcr_drug_uuid", required = true)
    protected BcrDrugUuid bcrDrugUuid;
    @XmlElement(name = "total_dose", required = true)
    protected TotalDose totalDose;
    @XmlElement(name = "total_dose_units", required = true)
    protected TotalDoseUnits totalDoseUnits;
    @XmlElement(name = "prescribed_dose", required = true)
    protected PrescribedDose prescribedDose;
    @XmlElement(name = "prescribed_dose_units", required = true)
    protected PrescribedDoseUnits prescribedDoseUnits;
    @XmlElement(name = "number_cycles", required = true)
    protected NumberCycles numberCycles;
    @XmlElement(name = "day_of_drug_therapy_start")
    protected DayOfDrugTherapyStart dayOfDrugTherapyStart;
    @XmlElement(name = "month_of_drug_therapy_start")
    protected MonthOfDrugTherapyStart monthOfDrugTherapyStart;
    @XmlElement(name = "year_of_drug_therapy_start")
    protected YearOfDrugTherapyStart yearOfDrugTherapyStart;
    @XmlElement(name = "days_to_drug_therapy_start")
    protected DaysToDrugTherapyStart daysToDrugTherapyStart;
    @XmlElement(name = "day_of_drug_therapy_end")
    protected DayOfDrugTherapyEnd dayOfDrugTherapyEnd;
    @XmlElement(name = "month_of_drug_therapy_end")
    protected MonthOfDrugTherapyEnd monthOfDrugTherapyEnd;
    @XmlElement(name = "year_of_drug_therapy_end")
    protected YearOfDrugTherapyEnd yearOfDrugTherapyEnd;
    @XmlElement(name = "days_to_drug_therapy_end")
    protected DaysToDrugTherapyEnd daysToDrugTherapyEnd;
    @XmlElement(name = "history_prior_systemic_therapy", nillable = true)
    protected HistoryPriorSystemicTherapy historyPriorSystemicTherapy;
    @XmlElement(name = "therapy_types", required = true)
    protected TherapyTypes therapyTypes;
    @XmlElement(name = "drug_name", required = true)
    protected DrugName drugName;
    @XmlElement(name = "clinical_trail_drug_classification", required = true)
    protected ClinicalTrailDrugClassification clinicalTrailDrugClassification;
    @XmlElement(name = "stem_cell_transplantation")
    protected StemCellTransplantation stemCellTransplantation;
    @XmlElement(name = "stem_cell_transplantation_type")
    protected StemCellTransplantationType stemCellTransplantationType;
    @XmlElement(name = "day_of_stem_cell_transplantation", namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7")
    protected DayOfStemCellTransplantation dayOfStemCellTransplantation;
    @XmlElement(name = "month_of_stem_cell_transplantation", namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7")
    protected MonthOfStemCellTransplantation monthOfStemCellTransplantation;
    @XmlElement(name = "year_of_stem_cell_transplantation", namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7")
    protected YearOfStemCellTransplantation yearOfStemCellTransplantation;
    @XmlElement(name = "days_to_stem_cell_transplantation", namespace = "http://tcga.nci/bcr/xml/clinical/shared/ocg/2.7")
    protected DaysToStemCellTransplantation daysToStemCellTransplantation;
    @XmlElement(name = "pharm_regimen", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected PharmRegimen pharmRegimen;
    @XmlElement(name = "pharm_regimen_other", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected PharmRegimenOther pharmRegimenOther;
    @XmlElement(name = "regimen_indication", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected RegimenIndication regimenIndication;
    @XmlElement(name = "regimen_indication_notes", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true)
    protected RegimenIndicationNotes regimenIndicationNotes;
    @XmlElement(name = "route_of_administrations", required = true)
    protected RouteOfAdministrations routeOfAdministrations;
    @XmlElement(name = "therapy_ongoing", required = true)
    protected TherapyOngoing therapyOngoing;
    @XmlElement(name = "measure_of_response", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected MeasureOfResponse measureOfResponse;
    @XmlElement(name = "day_of_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected DayOfFormCompletion dayOfFormCompletion;
    @XmlElement(name = "month_of_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected MonthOfFormCompletion monthOfFormCompletion;
    @XmlElement(name = "year_of_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", nillable = true)
    protected YearOfFormCompletion yearOfFormCompletion;
    @XmlElement(name = "days_to_form_completion", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7")
    protected DaysToFormCompletion daysToFormCompletion;

    /**
     * Gets the value of the txOnClinicalTrial property.
     * 
     * @return
     *     possible object is
     *     {@link TxOnClinicalTrial }
     *     
     */
    public TxOnClinicalTrial getTxOnClinicalTrial() {
        return txOnClinicalTrial;
    }

    /**
     * Sets the value of the txOnClinicalTrial property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxOnClinicalTrial }
     *     
     */
    public void setTxOnClinicalTrial(TxOnClinicalTrial value) {
        this.txOnClinicalTrial = value;
    }

    /**
     * Gets the value of the regimenNumber property.
     * 
     * @return
     *     possible object is
     *     {@link RegimenNumber }
     *     
     */
    public RegimenNumber getRegimenNumber() {
        return regimenNumber;
    }

    /**
     * Sets the value of the regimenNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegimenNumber }
     *     
     */
    public void setRegimenNumber(RegimenNumber value) {
        this.regimenNumber = value;
    }

    /**
     * Gets the value of the bcrDrugBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link BcrDrugBarcode }
     *     
     */
    public BcrDrugBarcode getBcrDrugBarcode() {
        return bcrDrugBarcode;
    }

    /**
     * Sets the value of the bcrDrugBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrDrugBarcode }
     *     
     */
    public void setBcrDrugBarcode(BcrDrugBarcode value) {
        this.bcrDrugBarcode = value;
    }

    /**
     * Gets the value of the bcrDrugUuid property.
     * 
     * @return
     *     possible object is
     *     {@link BcrDrugUuid }
     *     
     */
    public BcrDrugUuid getBcrDrugUuid() {
        return bcrDrugUuid;
    }

    /**
     * Sets the value of the bcrDrugUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BcrDrugUuid }
     *     
     */
    public void setBcrDrugUuid(BcrDrugUuid value) {
        this.bcrDrugUuid = value;
    }

    /**
     * Gets the value of the totalDose property.
     * 
     * @return
     *     possible object is
     *     {@link TotalDose }
     *     
     */
    public TotalDose getTotalDose() {
        return totalDose;
    }

    /**
     * Sets the value of the totalDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalDose }
     *     
     */
    public void setTotalDose(TotalDose value) {
        this.totalDose = value;
    }

    /**
     * Gets the value of the totalDoseUnits property.
     * 
     * @return
     *     possible object is
     *     {@link TotalDoseUnits }
     *     
     */
    public TotalDoseUnits getTotalDoseUnits() {
        return totalDoseUnits;
    }

    /**
     * Sets the value of the totalDoseUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalDoseUnits }
     *     
     */
    public void setTotalDoseUnits(TotalDoseUnits value) {
        this.totalDoseUnits = value;
    }

    /**
     * Gets the value of the prescribedDose property.
     * 
     * @return
     *     possible object is
     *     {@link PrescribedDose }
     *     
     */
    public PrescribedDose getPrescribedDose() {
        return prescribedDose;
    }

    /**
     * Sets the value of the prescribedDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescribedDose }
     *     
     */
    public void setPrescribedDose(PrescribedDose value) {
        this.prescribedDose = value;
    }

    /**
     * Gets the value of the prescribedDoseUnits property.
     * 
     * @return
     *     possible object is
     *     {@link PrescribedDoseUnits }
     *     
     */
    public PrescribedDoseUnits getPrescribedDoseUnits() {
        return prescribedDoseUnits;
    }

    /**
     * Sets the value of the prescribedDoseUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescribedDoseUnits }
     *     
     */
    public void setPrescribedDoseUnits(PrescribedDoseUnits value) {
        this.prescribedDoseUnits = value;
    }

    /**
     * Gets the value of the numberCycles property.
     * 
     * @return
     *     possible object is
     *     {@link NumberCycles }
     *     
     */
    public NumberCycles getNumberCycles() {
        return numberCycles;
    }

    /**
     * Sets the value of the numberCycles property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberCycles }
     *     
     */
    public void setNumberCycles(NumberCycles value) {
        this.numberCycles = value;
    }

    /**
     * Gets the value of the dayOfDrugTherapyStart property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfDrugTherapyStart }
     *     
     */
    public DayOfDrugTherapyStart getDayOfDrugTherapyStart() {
        return dayOfDrugTherapyStart;
    }

    /**
     * Sets the value of the dayOfDrugTherapyStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfDrugTherapyStart }
     *     
     */
    public void setDayOfDrugTherapyStart(DayOfDrugTherapyStart value) {
        this.dayOfDrugTherapyStart = value;
    }

    /**
     * Gets the value of the monthOfDrugTherapyStart property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfDrugTherapyStart }
     *     
     */
    public MonthOfDrugTherapyStart getMonthOfDrugTherapyStart() {
        return monthOfDrugTherapyStart;
    }

    /**
     * Sets the value of the monthOfDrugTherapyStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfDrugTherapyStart }
     *     
     */
    public void setMonthOfDrugTherapyStart(MonthOfDrugTherapyStart value) {
        this.monthOfDrugTherapyStart = value;
    }

    /**
     * Gets the value of the yearOfDrugTherapyStart property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfDrugTherapyStart }
     *     
     */
    public YearOfDrugTherapyStart getYearOfDrugTherapyStart() {
        return yearOfDrugTherapyStart;
    }

    /**
     * Sets the value of the yearOfDrugTherapyStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfDrugTherapyStart }
     *     
     */
    public void setYearOfDrugTherapyStart(YearOfDrugTherapyStart value) {
        this.yearOfDrugTherapyStart = value;
    }

    /**
     * Gets the value of the daysToDrugTherapyStart property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToDrugTherapyStart }
     *     
     */
    public DaysToDrugTherapyStart getDaysToDrugTherapyStart() {
        return daysToDrugTherapyStart;
    }

    /**
     * Sets the value of the daysToDrugTherapyStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToDrugTherapyStart }
     *     
     */
    public void setDaysToDrugTherapyStart(DaysToDrugTherapyStart value) {
        this.daysToDrugTherapyStart = value;
    }

    /**
     * Gets the value of the dayOfDrugTherapyEnd property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfDrugTherapyEnd }
     *     
     */
    public DayOfDrugTherapyEnd getDayOfDrugTherapyEnd() {
        return dayOfDrugTherapyEnd;
    }

    /**
     * Sets the value of the dayOfDrugTherapyEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfDrugTherapyEnd }
     *     
     */
    public void setDayOfDrugTherapyEnd(DayOfDrugTherapyEnd value) {
        this.dayOfDrugTherapyEnd = value;
    }

    /**
     * Gets the value of the monthOfDrugTherapyEnd property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfDrugTherapyEnd }
     *     
     */
    public MonthOfDrugTherapyEnd getMonthOfDrugTherapyEnd() {
        return monthOfDrugTherapyEnd;
    }

    /**
     * Sets the value of the monthOfDrugTherapyEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfDrugTherapyEnd }
     *     
     */
    public void setMonthOfDrugTherapyEnd(MonthOfDrugTherapyEnd value) {
        this.monthOfDrugTherapyEnd = value;
    }

    /**
     * Gets the value of the yearOfDrugTherapyEnd property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfDrugTherapyEnd }
     *     
     */
    public YearOfDrugTherapyEnd getYearOfDrugTherapyEnd() {
        return yearOfDrugTherapyEnd;
    }

    /**
     * Sets the value of the yearOfDrugTherapyEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfDrugTherapyEnd }
     *     
     */
    public void setYearOfDrugTherapyEnd(YearOfDrugTherapyEnd value) {
        this.yearOfDrugTherapyEnd = value;
    }

    /**
     * Gets the value of the daysToDrugTherapyEnd property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToDrugTherapyEnd }
     *     
     */
    public DaysToDrugTherapyEnd getDaysToDrugTherapyEnd() {
        return daysToDrugTherapyEnd;
    }

    /**
     * Sets the value of the daysToDrugTherapyEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToDrugTherapyEnd }
     *     
     */
    public void setDaysToDrugTherapyEnd(DaysToDrugTherapyEnd value) {
        this.daysToDrugTherapyEnd = value;
    }

    /**
     * Gets the value of the historyPriorSystemicTherapy property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryPriorSystemicTherapy }
     *     
     */
    public HistoryPriorSystemicTherapy getHistoryPriorSystemicTherapy() {
        return historyPriorSystemicTherapy;
    }

    /**
     * Sets the value of the historyPriorSystemicTherapy property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryPriorSystemicTherapy }
     *     
     */
    public void setHistoryPriorSystemicTherapy(HistoryPriorSystemicTherapy value) {
        this.historyPriorSystemicTherapy = value;
    }

    /**
     * Gets the value of the therapyTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TherapyTypes }
     *     
     */
    public TherapyTypes getTherapyTypes() {
        return therapyTypes;
    }

    /**
     * Sets the value of the therapyTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TherapyTypes }
     *     
     */
    public void setTherapyTypes(TherapyTypes value) {
        this.therapyTypes = value;
    }

    /**
     * Gets the value of the drugName property.
     * 
     * @return
     *     possible object is
     *     {@link DrugName }
     *     
     */
    public DrugName getDrugName() {
        return drugName;
    }

    /**
     * Sets the value of the drugName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugName }
     *     
     */
    public void setDrugName(DrugName value) {
        this.drugName = value;
    }

    /**
     * Gets the value of the clinicalTrailDrugClassification property.
     * 
     * @return
     *     possible object is
     *     {@link ClinicalTrailDrugClassification }
     *     
     */
    public ClinicalTrailDrugClassification getClinicalTrailDrugClassification() {
        return clinicalTrailDrugClassification;
    }

    /**
     * Sets the value of the clinicalTrailDrugClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClinicalTrailDrugClassification }
     *     
     */
    public void setClinicalTrailDrugClassification(ClinicalTrailDrugClassification value) {
        this.clinicalTrailDrugClassification = value;
    }

    /**
     * Gets the value of the stemCellTransplantation property.
     * 
     * @return
     *     possible object is
     *     {@link StemCellTransplantation }
     *     
     */
    public StemCellTransplantation getStemCellTransplantation() {
        return stemCellTransplantation;
    }

    /**
     * Sets the value of the stemCellTransplantation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StemCellTransplantation }
     *     
     */
    public void setStemCellTransplantation(StemCellTransplantation value) {
        this.stemCellTransplantation = value;
    }

    /**
     * Gets the value of the stemCellTransplantationType property.
     * 
     * @return
     *     possible object is
     *     {@link StemCellTransplantationType }
     *     
     */
    public StemCellTransplantationType getStemCellTransplantationType() {
        return stemCellTransplantationType;
    }

    /**
     * Sets the value of the stemCellTransplantationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StemCellTransplantationType }
     *     
     */
    public void setStemCellTransplantationType(StemCellTransplantationType value) {
        this.stemCellTransplantationType = value;
    }

    /**
     * Gets the value of the dayOfStemCellTransplantation property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfStemCellTransplantation }
     *     
     */
    public DayOfStemCellTransplantation getDayOfStemCellTransplantation() {
        return dayOfStemCellTransplantation;
    }

    /**
     * Sets the value of the dayOfStemCellTransplantation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfStemCellTransplantation }
     *     
     */
    public void setDayOfStemCellTransplantation(DayOfStemCellTransplantation value) {
        this.dayOfStemCellTransplantation = value;
    }

    /**
     * Gets the value of the monthOfStemCellTransplantation property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfStemCellTransplantation }
     *     
     */
    public MonthOfStemCellTransplantation getMonthOfStemCellTransplantation() {
        return monthOfStemCellTransplantation;
    }

    /**
     * Sets the value of the monthOfStemCellTransplantation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfStemCellTransplantation }
     *     
     */
    public void setMonthOfStemCellTransplantation(MonthOfStemCellTransplantation value) {
        this.monthOfStemCellTransplantation = value;
    }

    /**
     * Gets the value of the yearOfStemCellTransplantation property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfStemCellTransplantation }
     *     
     */
    public YearOfStemCellTransplantation getYearOfStemCellTransplantation() {
        return yearOfStemCellTransplantation;
    }

    /**
     * Sets the value of the yearOfStemCellTransplantation property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfStemCellTransplantation }
     *     
     */
    public void setYearOfStemCellTransplantation(YearOfStemCellTransplantation value) {
        this.yearOfStemCellTransplantation = value;
    }

    /**
     * Gets the value of the daysToStemCellTransplantation property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToStemCellTransplantation }
     *     
     */
    public DaysToStemCellTransplantation getDaysToStemCellTransplantation() {
        return daysToStemCellTransplantation;
    }

    /**
     * Sets the value of the daysToStemCellTransplantation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToStemCellTransplantation }
     *     
     */
    public void setDaysToStemCellTransplantation(DaysToStemCellTransplantation value) {
        this.daysToStemCellTransplantation = value;
    }

    /**
     * Gets the value of the pharmRegimen property.
     * 
     * @return
     *     possible object is
     *     {@link PharmRegimen }
     *     
     */
    public PharmRegimen getPharmRegimen() {
        return pharmRegimen;
    }

    /**
     * Sets the value of the pharmRegimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmRegimen }
     *     
     */
    public void setPharmRegimen(PharmRegimen value) {
        this.pharmRegimen = value;
    }

    /**
     * Gets the value of the pharmRegimenOther property.
     * 
     * @return
     *     possible object is
     *     {@link PharmRegimenOther }
     *     
     */
    public PharmRegimenOther getPharmRegimenOther() {
        return pharmRegimenOther;
    }

    /**
     * Sets the value of the pharmRegimenOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmRegimenOther }
     *     
     */
    public void setPharmRegimenOther(PharmRegimenOther value) {
        this.pharmRegimenOther = value;
    }

    /**
     * Gets the value of the regimenIndication property.
     * 
     * @return
     *     possible object is
     *     {@link RegimenIndication }
     *     
     */
    public RegimenIndication getRegimenIndication() {
        return regimenIndication;
    }

    /**
     * Sets the value of the regimenIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegimenIndication }
     *     
     */
    public void setRegimenIndication(RegimenIndication value) {
        this.regimenIndication = value;
    }

    /**
     * Gets the value of the regimenIndicationNotes property.
     * 
     * @return
     *     possible object is
     *     {@link RegimenIndicationNotes }
     *     
     */
    public RegimenIndicationNotes getRegimenIndicationNotes() {
        return regimenIndicationNotes;
    }

    /**
     * Sets the value of the regimenIndicationNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegimenIndicationNotes }
     *     
     */
    public void setRegimenIndicationNotes(RegimenIndicationNotes value) {
        this.regimenIndicationNotes = value;
    }

    /**
     * Gets the value of the routeOfAdministrations property.
     * 
     * @return
     *     possible object is
     *     {@link RouteOfAdministrations }
     *     
     */
    public RouteOfAdministrations getRouteOfAdministrations() {
        return routeOfAdministrations;
    }

    /**
     * Sets the value of the routeOfAdministrations property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteOfAdministrations }
     *     
     */
    public void setRouteOfAdministrations(RouteOfAdministrations value) {
        this.routeOfAdministrations = value;
    }

    /**
     * Gets the value of the therapyOngoing property.
     * 
     * @return
     *     possible object is
     *     {@link TherapyOngoing }
     *     
     */
    public TherapyOngoing getTherapyOngoing() {
        return therapyOngoing;
    }

    /**
     * Sets the value of the therapyOngoing property.
     * 
     * @param value
     *     allowed object is
     *     {@link TherapyOngoing }
     *     
     */
    public void setTherapyOngoing(TherapyOngoing value) {
        this.therapyOngoing = value;
    }

    /**
     * Gets the value of the measureOfResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureOfResponse }
     *     
     */
    public MeasureOfResponse getMeasureOfResponse() {
        return measureOfResponse;
    }

    /**
     * Sets the value of the measureOfResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureOfResponse }
     *     
     */
    public void setMeasureOfResponse(MeasureOfResponse value) {
        this.measureOfResponse = value;
    }

    /**
     * Gets the value of the dayOfFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfFormCompletion }
     *     
     */
    public DayOfFormCompletion getDayOfFormCompletion() {
        return dayOfFormCompletion;
    }

    /**
     * Sets the value of the dayOfFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfFormCompletion }
     *     
     */
    public void setDayOfFormCompletion(DayOfFormCompletion value) {
        this.dayOfFormCompletion = value;
    }

    /**
     * Gets the value of the monthOfFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfFormCompletion }
     *     
     */
    public MonthOfFormCompletion getMonthOfFormCompletion() {
        return monthOfFormCompletion;
    }

    /**
     * Sets the value of the monthOfFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfFormCompletion }
     *     
     */
    public void setMonthOfFormCompletion(MonthOfFormCompletion value) {
        this.monthOfFormCompletion = value;
    }

    /**
     * Gets the value of the yearOfFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfFormCompletion }
     *     
     */
    public YearOfFormCompletion getYearOfFormCompletion() {
        return yearOfFormCompletion;
    }

    /**
     * Sets the value of the yearOfFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfFormCompletion }
     *     
     */
    public void setYearOfFormCompletion(YearOfFormCompletion value) {
        this.yearOfFormCompletion = value;
    }

    /**
     * Gets the value of the daysToFormCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToFormCompletion }
     *     
     */
    public DaysToFormCompletion getDaysToFormCompletion() {
        return daysToFormCompletion;
    }

    /**
     * Sets the value of the daysToFormCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToFormCompletion }
     *     
     */
    public void setDaysToFormCompletion(DaysToFormCompletion value) {
        this.daysToFormCompletion = value;
    }

}
