//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}pathologic_T"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}pathologic_N"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}pathologic_M"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pathologicT",
    "pathologicN",
    "pathologicM"
})
@XmlRootElement(name = "pathologic_categories")
public class PathologicCategories {

    @XmlElement(name = "pathologic_T", required = true)
    protected PathologicT pathologicT;
    @XmlElement(name = "pathologic_N", required = true)
    protected PathologicN pathologicN;
    @XmlElement(name = "pathologic_M", required = true)
    protected PathologicM pathologicM;

    /**
     * Gets the value of the pathologicT property.
     * 
     * @return
     *     possible object is
     *     {@link PathologicT }
     *     
     */
    public PathologicT getPathologicT() {
        return pathologicT;
    }

    /**
     * Sets the value of the pathologicT property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathologicT }
     *     
     */
    public void setPathologicT(PathologicT value) {
        this.pathologicT = value;
    }

    /**
     * Gets the value of the pathologicN property.
     * 
     * @return
     *     possible object is
     *     {@link PathologicN }
     *     
     */
    public PathologicN getPathologicN() {
        return pathologicN;
    }

    /**
     * Sets the value of the pathologicN property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathologicN }
     *     
     */
    public void setPathologicN(PathologicN value) {
        this.pathologicN = value;
    }

    /**
     * Gets the value of the pathologicM property.
     * 
     * @return
     *     possible object is
     *     {@link PathologicM }
     *     
     */
    public PathologicM getPathologicM() {
        return pathologicM;
    }

    /**
     * Sets the value of the pathologicM property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathologicM }
     *     
     */
    public void setPathologicM(PathologicM value) {
        this.pathologicM = value;
    }

}
