//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 06:01:48 AM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared.stage._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}psa_value" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}day_of_psa"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}month_of_psa"/>
 *             &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}year_of_psa"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/stage/2.7}days_to_psa"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psaValue",
    "dayOfPsa",
    "monthOfPsa",
    "yearOfPsa",
    "daysToPsa"
})
@XmlRootElement(name = "psa")
public class Psa {

    @XmlElement(name = "psa_value")
    protected PsaValue psaValue;
    @XmlElement(name = "day_of_psa")
    protected DayOfPsa dayOfPsa;
    @XmlElement(name = "month_of_psa")
    protected MonthOfPsa monthOfPsa;
    @XmlElement(name = "year_of_psa")
    protected YearOfPsa yearOfPsa;
    @XmlElement(name = "days_to_psa")
    protected DaysToPsa daysToPsa;

    /**
     * Gets the value of the psaValue property.
     * 
     * @return
     *     possible object is
     *     {@link PsaValue }
     *     
     */
    public PsaValue getPsaValue() {
        return psaValue;
    }

    /**
     * Sets the value of the psaValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PsaValue }
     *     
     */
    public void setPsaValue(PsaValue value) {
        this.psaValue = value;
    }

    /**
     * Gets the value of the dayOfPsa property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfPsa }
     *     
     */
    public DayOfPsa getDayOfPsa() {
        return dayOfPsa;
    }

    /**
     * Sets the value of the dayOfPsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfPsa }
     *     
     */
    public void setDayOfPsa(DayOfPsa value) {
        this.dayOfPsa = value;
    }

    /**
     * Gets the value of the monthOfPsa property.
     * 
     * @return
     *     possible object is
     *     {@link MonthOfPsa }
     *     
     */
    public MonthOfPsa getMonthOfPsa() {
        return monthOfPsa;
    }

    /**
     * Sets the value of the monthOfPsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthOfPsa }
     *     
     */
    public void setMonthOfPsa(MonthOfPsa value) {
        this.monthOfPsa = value;
    }

    /**
     * Gets the value of the yearOfPsa property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfPsa }
     *     
     */
    public YearOfPsa getYearOfPsa() {
        return yearOfPsa;
    }

    /**
     * Sets the value of the yearOfPsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfPsa }
     *     
     */
    public void setYearOfPsa(YearOfPsa value) {
        this.yearOfPsa = value;
    }

    /**
     * Gets the value of the daysToPsa property.
     * 
     * @return
     *     possible object is
     *     {@link DaysToPsa }
     *     
     */
    public DaysToPsa getDaysToPsa() {
        return daysToPsa;
    }

    /**
     * Sets the value of the daysToPsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysToPsa }
     *     
     */
    public void setDaysToPsa(DaysToPsa value) {
        this.daysToPsa = value;
    }

}
