//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 05:01:33 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.brca._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MolecularAbnormalityResults;
import org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.shared._2.MolecularAbnormalityResultsOther;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}molecular_abnormality_results"/>
 *         &lt;element ref="{http://tcga.nci/bcr/xml/clinical/shared/2.7}molecular_abnormality_results_other"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "molecularAbnormalityResults",
    "molecularAbnormalityResultsOther"
})
@XmlRootElement(name = "molecular_marker")
public class MolecularMarker {

    @XmlElement(name = "molecular_abnormality_results", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected MolecularAbnormalityResults molecularAbnormalityResults;
    @XmlElement(name = "molecular_abnormality_results_other", namespace = "http://tcga.nci/bcr/xml/clinical/shared/2.7", required = true, nillable = true)
    protected MolecularAbnormalityResultsOther molecularAbnormalityResultsOther;

    /**
     * Gets the value of the molecularAbnormalityResults property.
     * 
     * @return
     *     possible object is
     *     {@link MolecularAbnormalityResults }
     *     
     */
    public MolecularAbnormalityResults getMolecularAbnormalityResults() {
        return molecularAbnormalityResults;
    }

    /**
     * Sets the value of the molecularAbnormalityResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link MolecularAbnormalityResults }
     *     
     */
    public void setMolecularAbnormalityResults(MolecularAbnormalityResults value) {
        this.molecularAbnormalityResults = value;
    }

    /**
     * Gets the value of the molecularAbnormalityResultsOther property.
     * 
     * @return
     *     possible object is
     *     {@link MolecularAbnormalityResultsOther }
     *     
     */
    public MolecularAbnormalityResultsOther getMolecularAbnormalityResultsOther() {
        return molecularAbnormalityResultsOther;
    }

    /**
     * Sets the value of the molecularAbnormalityResultsOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link MolecularAbnormalityResultsOther }
     *     
     */
    public void setMolecularAbnormalityResultsOther(MolecularAbnormalityResultsOther value) {
        this.molecularAbnormalityResultsOther = value;
    }

}
