//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 05:01:33 PM IST 
//


package org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.brca._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.brca._2 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AxillaryLymphNodeStageMethodType_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "axillary_lymph_node_stage_method_type");
    private final static QName _SurgicalProcedurePurposeOtherText_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "surgical_procedure_purpose_other_text");
    private final static QName _DistantMetastasisPresentInd2_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "distant_metastasis_present_ind2");
    private final static QName _BreastCancerSurgeryMarginStatus_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "breast_cancer_surgery_margin_status");
    private final static QName _BreastCarcinomaPrimarySurgicalProcedureName_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "breast_carcinoma_primary_surgical_procedure_name");
    private final static QName _CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "cytokeratin_immunohistochemistry_staining_method_micrometastasis_indicator");
    private final static QName _BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "breast_carcinoma_immunohistochemistry_progesterone_receptor_pos_finding_scale");
    private final static QName _BreastCarcinomaImmunohistochemistryErPosFindingScale_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "breast_carcinoma_immunohistochemistry_er_pos_finding_scale");
    private final static QName _AxillaryLymphNodeStageOtherMethodDescriptiveText_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "axillary_lymph_node_stage_other_method_descriptive_text");
    private final static QName _BreastNeoplasmOtherSurgicalProcedureDescriptiveText_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "breast_neoplasm_other_surgical_procedure_descriptive_text");
    private final static QName _BreastCarcinomaSurgicalProcedureName_QNAME = new QName("http://tcga.nci/bcr/xml/clinical/brca/2.7", "breast_carcinoma_surgical_procedure_name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cbio.gdcpipeline.model.gdc.nci.tcga.bcr.xml.clinical.brca._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator }
     * 
     */
    public CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator createCytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator() {
        return new CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator();
    }

    /**
     * Create an instance of {@link BreastCarcinomaPrimarySurgicalProcedureName }
     * 
     */
    public BreastCarcinomaPrimarySurgicalProcedureName createBreastCarcinomaPrimarySurgicalProcedureName() {
        return new BreastCarcinomaPrimarySurgicalProcedureName();
    }

    /**
     * Create an instance of {@link DistantMetastasisPresentInd2 }
     * 
     */
    public DistantMetastasisPresentInd2 createDistantMetastasisPresentInd2() {
        return new DistantMetastasisPresentInd2();
    }

    /**
     * Create an instance of {@link TcgaBcr }
     * 
     */
    public TcgaBcr createTcgaBcr() {
        return new TcgaBcr();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link AnatomicNeoplasmSubdivisions }
     * 
     */
    public AnatomicNeoplasmSubdivisions createAnatomicNeoplasmSubdivisions() {
        return new AnatomicNeoplasmSubdivisions();
    }

    /**
     * Create an instance of {@link AxillaryLymphNodeStageMethodType }
     * 
     */
    public AxillaryLymphNodeStageMethodType createAxillaryLymphNodeStageMethodType() {
        return new AxillaryLymphNodeStageMethodType();
    }

    /**
     * Create an instance of {@link AxillaryLymphNodeStageOtherMethodDescriptiveText }
     * 
     */
    public AxillaryLymphNodeStageOtherMethodDescriptiveText createAxillaryLymphNodeStageOtherMethodDescriptiveText() {
        return new AxillaryLymphNodeStageOtherMethodDescriptiveText();
    }

    /**
     * Create an instance of {@link BreastCarcinomaSurgicalProcedureName }
     * 
     */
    public BreastCarcinomaSurgicalProcedureName createBreastCarcinomaSurgicalProcedureName() {
        return new BreastCarcinomaSurgicalProcedureName();
    }

    /**
     * Create an instance of {@link BreastNeoplasmOtherSurgicalProcedureDescriptiveText }
     * 
     */
    public BreastNeoplasmOtherSurgicalProcedureDescriptiveText createBreastNeoplasmOtherSurgicalProcedureDescriptiveText() {
        return new BreastNeoplasmOtherSurgicalProcedureDescriptiveText();
    }

    /**
     * Create an instance of {@link SurgicalProcedurePurposeOtherText }
     * 
     */
    public SurgicalProcedurePurposeOtherText createSurgicalProcedurePurposeOtherText() {
        return new SurgicalProcedurePurposeOtherText();
    }

    /**
     * Create an instance of {@link BreastCarcinomaImmunohistochemistryErPosFindingScale }
     * 
     */
    public BreastCarcinomaImmunohistochemistryErPosFindingScale createBreastCarcinomaImmunohistochemistryErPosFindingScale() {
        return new BreastCarcinomaImmunohistochemistryErPosFindingScale();
    }

    /**
     * Create an instance of {@link BreastCancerSurgeryMarginStatus }
     * 
     */
    public BreastCancerSurgeryMarginStatus createBreastCancerSurgeryMarginStatus() {
        return new BreastCancerSurgeryMarginStatus();
    }

    /**
     * Create an instance of {@link FirstNonlymphNodeMetastasisAnatomicSites }
     * 
     */
    public FirstNonlymphNodeMetastasisAnatomicSites createFirstNonlymphNodeMetastasisAnatomicSites() {
        return new FirstNonlymphNodeMetastasisAnatomicSites();
    }

    /**
     * Create an instance of {@link BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale }
     * 
     */
    public BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale createBreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale() {
        return new BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale();
    }

    /**
     * Create an instance of {@link MolecularMarkers }
     * 
     */
    public MolecularMarkers createMolecularMarkers() {
        return new MolecularMarkers();
    }

    /**
     * Create an instance of {@link MolecularMarker }
     * 
     */
    public MolecularMarker createMolecularMarker() {
        return new MolecularMarker();
    }

    /**
     * Create an instance of {@link FollowUps }
     * 
     */
    public FollowUps createFollowUps() {
        return new FollowUps();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AxillaryLymphNodeStageMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "axillary_lymph_node_stage_method_type")
    public JAXBElement<AxillaryLymphNodeStageMethodType> createAxillaryLymphNodeStageMethodType(AxillaryLymphNodeStageMethodType value) {
        return new JAXBElement<AxillaryLymphNodeStageMethodType>(_AxillaryLymphNodeStageMethodType_QNAME, AxillaryLymphNodeStageMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurgicalProcedurePurposeOtherText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "surgical_procedure_purpose_other_text")
    public JAXBElement<SurgicalProcedurePurposeOtherText> createSurgicalProcedurePurposeOtherText(SurgicalProcedurePurposeOtherText value) {
        return new JAXBElement<SurgicalProcedurePurposeOtherText>(_SurgicalProcedurePurposeOtherText_QNAME, SurgicalProcedurePurposeOtherText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DistantMetastasisPresentInd2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "distant_metastasis_present_ind2")
    public JAXBElement<DistantMetastasisPresentInd2> createDistantMetastasisPresentInd2(DistantMetastasisPresentInd2 value) {
        return new JAXBElement<DistantMetastasisPresentInd2>(_DistantMetastasisPresentInd2_QNAME, DistantMetastasisPresentInd2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreastCancerSurgeryMarginStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "breast_cancer_surgery_margin_status")
    public JAXBElement<BreastCancerSurgeryMarginStatus> createBreastCancerSurgeryMarginStatus(BreastCancerSurgeryMarginStatus value) {
        return new JAXBElement<BreastCancerSurgeryMarginStatus>(_BreastCancerSurgeryMarginStatus_QNAME, BreastCancerSurgeryMarginStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreastCarcinomaPrimarySurgicalProcedureName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "breast_carcinoma_primary_surgical_procedure_name")
    public JAXBElement<BreastCarcinomaPrimarySurgicalProcedureName> createBreastCarcinomaPrimarySurgicalProcedureName(BreastCarcinomaPrimarySurgicalProcedureName value) {
        return new JAXBElement<BreastCarcinomaPrimarySurgicalProcedureName>(_BreastCarcinomaPrimarySurgicalProcedureName_QNAME, BreastCarcinomaPrimarySurgicalProcedureName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "cytokeratin_immunohistochemistry_staining_method_micrometastasis_indicator")
    public JAXBElement<CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator> createCytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator(CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator value) {
        return new JAXBElement<CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator>(_CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator_QNAME, CytokeratinImmunohistochemistryStainingMethodMicrometastasisIndicator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "breast_carcinoma_immunohistochemistry_progesterone_receptor_pos_finding_scale")
    public JAXBElement<BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale> createBreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale(BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale value) {
        return new JAXBElement<BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale>(_BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale_QNAME, BreastCarcinomaImmunohistochemistryProgesteroneReceptorPosFindingScale.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreastCarcinomaImmunohistochemistryErPosFindingScale }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "breast_carcinoma_immunohistochemistry_er_pos_finding_scale")
    public JAXBElement<BreastCarcinomaImmunohistochemistryErPosFindingScale> createBreastCarcinomaImmunohistochemistryErPosFindingScale(BreastCarcinomaImmunohistochemistryErPosFindingScale value) {
        return new JAXBElement<BreastCarcinomaImmunohistochemistryErPosFindingScale>(_BreastCarcinomaImmunohistochemistryErPosFindingScale_QNAME, BreastCarcinomaImmunohistochemistryErPosFindingScale.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AxillaryLymphNodeStageOtherMethodDescriptiveText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "axillary_lymph_node_stage_other_method_descriptive_text")
    public JAXBElement<AxillaryLymphNodeStageOtherMethodDescriptiveText> createAxillaryLymphNodeStageOtherMethodDescriptiveText(AxillaryLymphNodeStageOtherMethodDescriptiveText value) {
        return new JAXBElement<AxillaryLymphNodeStageOtherMethodDescriptiveText>(_AxillaryLymphNodeStageOtherMethodDescriptiveText_QNAME, AxillaryLymphNodeStageOtherMethodDescriptiveText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreastNeoplasmOtherSurgicalProcedureDescriptiveText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "breast_neoplasm_other_surgical_procedure_descriptive_text")
    public JAXBElement<BreastNeoplasmOtherSurgicalProcedureDescriptiveText> createBreastNeoplasmOtherSurgicalProcedureDescriptiveText(BreastNeoplasmOtherSurgicalProcedureDescriptiveText value) {
        return new JAXBElement<BreastNeoplasmOtherSurgicalProcedureDescriptiveText>(_BreastNeoplasmOtherSurgicalProcedureDescriptiveText_QNAME, BreastNeoplasmOtherSurgicalProcedureDescriptiveText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreastCarcinomaSurgicalProcedureName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tcga.nci/bcr/xml/clinical/brca/2.7", name = "breast_carcinoma_surgical_procedure_name")
    public JAXBElement<BreastCarcinomaSurgicalProcedureName> createBreastCarcinomaSurgicalProcedureName(BreastCarcinomaSurgicalProcedureName value) {
        return new JAXBElement<BreastCarcinomaSurgicalProcedureName>(_BreastCarcinomaSurgicalProcedureName_QNAME, BreastCarcinomaSurgicalProcedureName.class, null, value);
    }

}
